var airportOptionList = [{value:"AAL", label:"Aalborg Airport/AALBORG, Denmark(AAL)"},
{value:"AAR", label:"Aarhus Tirstrup Airport/AARHUS, Denmark(AAR)"},
{value:"ABD", label:"Abadan/ABADAN, Iran (Islamic Republic Of)(ABD)"},
{value:"ABA", label:"Abakan/ABAKAN, Russian Federation(ABA)"},
{value:"ABZ", label:"Aberdeen/ABERDEEN, United Kingdom(ABZ)"},
{value:"AHB", label:"Abha Regional Airport/ABHA, Saudi Arabia(AHB)"},
{value:"ABJ", label:"Abidjan/ABIDJAN, Cote Divoire(ABJ)"},
{value:"ABI", label:"Abilene/ABILENE, United States(ABI)"},
{value:"AUH", label:"Abu Dhabi/ABU DHABI, United Arab Emirates(AUH)"},
{value:"ABV", label:"Abuja/ABUJA, Nigeria(ABV)"},
{value:"ACA", label:"Acapulco/ACAPULCO, Mexico(ACA)"},
{value:"ACC", label:"Accra/ACCRA, Ghana(ACC)"},
{value:"ADA", label:"Adana/ADANA, Turkey(ADA)"},
{value:"ADD", label:"Addis Ababa Bole Intl/ADDIS ABABA, Ethiopia(ADD)"},
{value:"ADL", label:"Adelaide/ADELAIDE, Australia(ADL)"},
{value:"ADE", label:"Aden/ADEN, Yemen, Republic Of(ADE)"},
{value:"ADB", label:"Adnan Menderesapt Izmir/IZMIR, Turkey(ADB)"},
{value:"AGA", label:"Agadir/AGADIR, Morocco(AGA)"},
{value:"IXA", label:"Agartala/AGARTALA, India(IXA)"},
{value:"AMD", label:"Ahmedabad/AHMEDABAD, India(AMD)"},
{value:"AJA", label:"Ajaccio/AJACCIO, France(AJA)"},
{value:"AXT", label:"Akita/AKITA, Japan(AXT)"},
{value:"CAK", label:"Akron Canton/AKRON, United States(CAK)"},
{value:"AKU", label:"Aksu/AKSU, China(AKU)"},
{value:"FJR", label:"Al - Fujairah/AL-FUJAIRAH, United Arab Emirates(FJR)"},
{value:"AAN", label:"Al Ain/AL AIN, United Arab Emirates(AAN)"},
{value:"AAC", label:"Al Arish/AL-ARISH, Egypt(AAC)"},
{value:"DWC", label:"Al Maktoum Intl Airport/DUBAI, United Arab Emirates(DWC)"},
{value:"BGW", label:"Al Muthana Baghdad/BAGHDAD, Iraq(BGW)"},
{value:"HOF", label:"Al-Ahsa Domestic Airport/HOFUF, Saudi Arabia(HOF)"},
{value:"ALB", label:"Albany County Usa/ALBANY COUNTY NY, United States(ALB)"},
{value:"LBI", label:"Albi/ALBI, France(LBI)"},
{value:"ABQ", label:"Albuquerque/ALBUQUERQU, United States(ABQ)"},
{value:"ABX", label:"Albury/ALBURY, Australia(ABX)"},
{value:"ALP", label:"Aleppo/ALEPPO, Syrian Arab Republic(ALP)"},
{value:"HBE", label:"Alexandria Borg El Arab/ALEXANDRIA, Egypt(HBE)"},
{value:"ALY", label:"Alexandria Egypt/ALEXANDRIA, Egypt(ALY)"},
{value:"AEX", label:"Alexandria England Afb Usa/ALEXANDRIA ENGLAND AFB, United States(AEX)"},
{value:"VUP", label:"Alfonso Lopez Pumarego Apt/VALLEDUPAR, Colombia(VUP)"},
{value:"LET", label:"Alfredo Vasquez Cobo Intl Apt/LETICIA, Colombia(LET)"},
{value:"ALG", label:"Algiers/ALGIERS, Algeria(ALG)"},
{value:"ALC", label:"Alicante/ALICANTE, Spain And Canary Islands(ALC)"},
{value:"ASP", label:"Alice Spring/ALICE SPRINGS, Australia(ASP)"},
{value:"NGQ", label:"Alikunsha/SHIQUANHE, China(NGQ)"},
{value:"ABE", label:"Allentown Bethlehem Easton/ALLENTOWN, United States(ABE)"},
{value:"ALA", label:"Almaty/ALMATY, Kazakhstan(ALA)"},
{value:"LEI", label:"Almeria/ALMERIA, Spain And Canary Islands(LEI)"},
{value:"AOR", label:"Alor Setar/ALOR SETAR, Malaysia(AOR)"},
{value:"ASJ", label:"Amami/AMAMI O SHIMA, Japan(ASJ)"},
{value:"AMA", label:"Amarillo/AMARILLO, United States(AMA)"},
{value:"AMM", label:"Amman/Queen Alia Intl/AMMAN, Jordan(AMM)"},
{value:"ATQ", label:"Amritsar/AMRITSAR, India(ATQ)"},
{value:"AMS", label:"Amsterdam/Schiphol/AMSTERDAM, Netherlands(AMS)"},
{value:"AAQ", label:"Anapa/ANAPA, Russian Federation(AAQ)"},
{value:"ANC", label:"Anchorage/ANCHORAGE, United States(ANC)"},
{value:"AXA", label:"Anguilla/ANGUILLA, Anguilla(AXA)"},
{value:"ANK", label:"Ankara/ANKARA, Turkey(ANK)"},
{value:"ESB", label:"Ankara Esenboga/ANKARA, Turkey(ESB)"},
{value:"NCY", label:"Annecy/ANNECY, France(NCY)"},
{value:"AQG", label:"Anqing/ANQING, China(AQG)"},
{value:"AYT", label:"Antalya/ANTALYA, Turkey(AYT)"},
{value:"ANU", label:"Antique/ANTIGUA, Antigua And Barbuda(ANU)"},
{value:"ANF", label:"Antofagasta/ANTOFAGASTA, Chile(ANF)"},
{value:"ANR", label:"Antwerp Deurne Airport/ANTWERP, Belgium(ANR)"},
{value:"AOJ", label:"Aomori/AOMORI, Japan(AOJ)"},
{value:"APO", label:"Apartado Airport/APARTADO, Colombia(APO)"},
{value:"AQJ", label:"Aqaba/AQABA, Jordan(AQJ)"},
{value:"AJU", label:"Aracaju/ARACAJU, Brazil(AJU)"},
{value:"ACV", label:"Arcata Eureka/ARCATA, United States(ACV)"},
{value:"AQP", label:"Arequipa/AREQUIPA, Peru(AQP)"},
{value:"ARI", label:"Arica/ARICA, Chile(ARI)"},
{value:"ARM", label:"Armidale/ARMIDALE, Australia(ARM)"},
{value:"AUA", label:"Aruba/ARUBA, Aruba(AUA)"},
{value:"AJR", label:"Arvidsjaur/ARVIDSJAUR, Sweden(AJR)"},
{value:"AKJ", label:"Asahikawa/ASAHIKAWA, Japan(AKJ)"},
{value:"AVL", label:"Asheville/ASHEVILLE, United States(AVL)"},
{value:"LBD", label:"Ashkabad/KHUDZHAND, Tadjikistan(LBD)"},
{value:"ASB", label:"Ashkhabad/ASHKHABAD, Turkmenistan(ASB)"},
{value:"ASM", label:"Asmara Yohanes Iv/ASMARA YOHANES IV, Eritrea(ASM)"},
{value:"ASE", label:"Aspen/ASPEN, United States(ASE)"},
{value:"ASF", label:"Astrakhan/ASTRAKHAN, Russian Federation(ASF)"},
{value:"OVD", label:"Asturias/ASTURIAS, Spain And Canary Islands(OVD)"},
{value:"ASU", label:"Asuncion/ASUNCION, Paraguay(ASU)"},
{value:"ATH", label:"Athens/ATHENS, Greece(ATH)"},
{value:"ATL", label:"Atlanta/ATLANTA, United States(ATL)"},
{value:"ATK", label:"Atqasuk/ATQASUK, United States(ATK)"},
{value:"AKL", label:"Auckland/AUCKLAND, New Zealand(AKL)"},
{value:"AGS", label:"Augusta Bush Field/AUGUSTA GA, United States(AGS)"},
{value:"IXU", label:"Aurangabad/AURANGABAD, India(IXU)"},
{value:"AUR", label:"Aurillac/AURILLAC, France(AUR)"},
{value:"AUS", label:"Austin/AUSTIN, United States(AUS)"},
{value:"AVV", label:"Avalon/AVALON, Australia(AVV)"},
{value:"AYP", label:"Ayacucho/AYACUCHO, Peru(AYP)"},
{value:"AYQ", label:"Ayers Rock/AYERS ROCK, Australia(AYQ)"},
{value:"BJZ", label:"Badajoz/BADAJOZ, Spain And Canary Islands(BJZ)"},
{value:"IXB", label:"Bagdogra/BAGDOGRA, India(IXB)"},
{value:"SDA", label:"Baghdad/BAGHDAD, Iraq(SDA)"},
{value:"BHI", label:"Bahia Blanca Airport/BAHIA BLANCA, Argentina(BHI)"},
{value:"BAH", label:"Bahrain/BAHRAIN, Bahrain(BAH)"},
{value:"NBS", label:"Baishan/BAISHAN, China(NBS)"},
{value:"BFL", label:"Bakersfield/BAKERSFIELD, United States(BFL)"},
{value:"BAK", label:"Baku/BAKU, Azerbaijan(BAK)"},
{value:"GYD", label:"Baku/BAKU, Azerbaijan(GYD)"},
{value:"DPS", label:"Bali/Denpasar/DENPASAR/BALI, Indonesia(DPS)"},
{value:"BNK", label:"Ballina/BALLINA NS, Australia(BNK)"},
{value:"BBA", label:"Balmaceda/BALMACEDA, Chile(BBA)"},
{value:"BWI", label:"Baltimore/BALTIMORE, United States(BWI)"},
{value:"BWN", label:"Bandar Seri Begawan/BANDAR SERI BEGAWAN, Brunei Darussalam(BWN)"},
{value:"BLR", label:"Bangalore/BENGALURU, India(BLR)"},
{value:"BKK", label:"Bangkok/Suvarnabhumi/BANGKOK, Thailand(BKK)"},
{value:"BGR", label:"Bangor/BANGOR, United States(BGR)"},
{value:"BVB", label:"Bao Vista Intl Airport/BOA VISTA, Brazil(BVB)"},
{value:"BSD", label:"Baoshan/BAOSHAN, China(BSD)"},
{value:"BAV", label:"Baotou/BAOTOU, China(BAV)"},
{value:"BCN", label:"Barcelona/BARCELONA, Spain And Canary Islands(BCN)"},
{value:"BRI", label:"Bari/BARI, Italy(BRI)"},
{value:"BAX", label:"Barnaul/BARNAUL, Russian Federation(BAX)"},
{value:"BRR", label:"Barra/BARRA, United Kingdom(BRR)"},
{value:"BAQ", label:"Barrabguilla/BARRANQUILLA, Colombia(BAQ)"},
{value:"BRW", label:"Barrow/BARROW, United States(BRW)"},
{value:"BWB", label:"Barrow Island/BARROW ISLAND, Australia(BWB)"},
{value:"BSL", label:"Basle/BASLE, Switzerland(BSL)"},
{value:"BSR", label:"Basrah International/BASRA, Iraq(BSR)"},
{value:"BIA", label:"Bastia/BASTIA, France(BIA)"},
{value:"BTH", label:"Batam/Hang Nadim/BATAM, Indonesia(BTH)"},
{value:"BTR", label:"Baton Rouge Ryan Apt/BATON ROUGE, United States(BTR)"},
{value:"BTL", label:"Battle Creek/BATTLE CREEK, United States(BTL)"},
{value:"BUS", label:"Batumi/BATUMI, Georgia(BUS)"},
{value:"RLK", label:"Bayannur/BAYANNUR, China(RLK)"},
{value:"BPT", label:"Beaumont/BEAUMONT, United States(BPT)"},
{value:"EIS", label:"Beef Island/BEEF ISLAND, Virgin Islands, (British)(EIS)"},
{value:"BHY", label:"Beihai/BEIHAI, China(BHY)"},
{value:"PEK", label:"Beijing(Peking)/BEIJING, China(PEK)"},
{value:"BEY", label:"Beirut Intl/BEIRUT, Lebanon(BEY)"},
{value:"BEL", label:"Belem/BELEM, Brazil(BEL)"},
{value:"BFS", label:"Belfast/BELFAST INTERNATIONAL, United Kingdom(BFS)"},
{value:"BHD", label:"Belfast City Apt/BELFAST INTERNATIONAL, United Kingdom(BHD)"},
{value:"BZE", label:"Belize/BELIZE, Belize(BZE)"},
{value:"BLI", label:"Bellingham/BELLINGHAM, United States(BLI)"},
{value:"CNF", label:"Belo Horizonte/BELO HORIZONTE, Brazil(CNF)"},
{value:"BEB", label:"Benbecula/BENBECULA, United Kingdom(BEB)"},
{value:"BEN", label:"Benghazi/BENGHAZI, Libyan Arab Jamahiriya(BEN)"},
{value:"NVA", label:"Benito Sales Airport/NEIVA, Colombia(NVA)"},
{value:"BGO", label:"Bergen/BERGEN, Norway(BGO)"},
{value:"SXF", label:"Berlin Schonefeld/BERLIN, Germany(SXF)"},
{value:"THF", label:"Berlin Tempelhof/BERLIN, Germany(THF)"},
{value:"TXL", label:"Berlin/Tegel/BERLIN, Germany(TXL)"},
{value:"BDA", label:"Bermuda/BERMUDA, Bermuda(BDA)"},
{value:"BRN", label:"Berne Belp/BERNE, Switzerland(BRN)"},
{value:"BET", label:"Bethel Municipal Apt/BETHEL, United States(BET)"},
{value:"BHU", label:"Bhavnagar/BHAVNAGAR, India(BHU)"},
{value:"BHO", label:"Bhopal/BHOPAL, India(BHO)"},
{value:"BBI", label:"Bhubaneswar/BHUBANESWAR, India(BBI)"},
{value:"BHJ", label:"Bhuj/BHUJ, India(BHJ)"},
{value:"BIO", label:"Bilbao/BILBAO, Spain And Canary Islands(BIO)"},
{value:"BIL", label:"Billings/BILLINGS, United States(BIL)"},
{value:"BLL", label:"Billund/BILLUND, Denmark(BLL)"},
{value:"BGM", label:"Binghamton/BINGHAMTON, United States(BGM)"},
{value:"BTU", label:"Bintulu/BINTULU, Malaysia(BTU)"},
{value:"BHX", label:"Birmingham Intl Uk/BIRMINGHAM, United Kingdom(BHX)"},
{value:"BHM", label:"Birmingham Usa/BIRMINGHAM, United States(BHM)"},
{value:"FRU", label:"Bishkek/FRUNZE, Kyrgstan(FRU)"},
{value:"BIS", label:"Bismarck/BISMARCK, United States(BIS)"},
{value:"BLK", label:"Blackpool/BLACKPOOL, United Kingdom(BLK)"},
{value:"BLT", label:"Blackwater/BLACKWATER, Australia(BLT)"},
{value:"BQS", label:"Blagoveshchensk/BLAGOVESHCHENSK, Russian Federation(BQS)"},
{value:"BHE", label:"Blenheim/BLENHEIM, New Zealand(BHE)"},
{value:"BMI", label:"Bloomington - Nromal/BLOOMINGTON-NORMAL, United States(BMI)"},
{value:"BOO", label:"Bodo/BODO, Norway(BOO)"},
{value:"BJV", label:"Bodrum/BODRUM, Turkey(BJV)"},
{value:"BOG", label:"Bogota/BOGOTA, Colombia(BOG)"},
{value:"BOI", label:"Boise/BOISE, United States(BOI)"},
{value:"BLQ", label:"Bologna/BOLOGNA, Italy(BLQ)"},
{value:"BON", label:"Bonaire/BONAIRE, Netherlands Antilles(BON)"},
{value:"BOD", label:"Bordeaux/BORDEAUX, France(BOD)"},
{value:"BOS", label:"Boston/BOSTON, United States(BOS)"},
{value:"BOJ", label:"Bourgas/BOURGAS, Bulgaria(BOJ)"},
{value:"BOH", label:"Bournemouth/BOURNEMOUTH, United Kingdom(BOH)"},
{value:"BZN", label:"Bozeman/BOZEMAN, United States(BZN)"},
{value:"SRQ", label:"Bradenton/BRADENTON, United States(SRQ)"},
{value:"BSB", label:"Brasilia/BRASILIA, Brazil(BSB)"},
{value:"BTS", label:"Bratislava/BRATISLAVA, Slovakia(BTS)"},
{value:"BTK", label:"Bratsk/BRATSK, Russian Federation(BTK)"},
{value:"BWE", label:"Braunschweig/BRAUNSCHWEG, Germany(BWE)"},
{value:"BRE", label:"Bremen/BREMEN, Germany(BRE)"},
{value:"BES", label:"Brest/BREST, France(BES)"},
{value:"BDR", label:"Bridgeport/BRIDGEPORT, United States(BDR)"},
{value:"BGI", label:"Bridgetown/BARBADOS, Barbados(BGI)"},
{value:"BDS", label:"Brindisi/BRINDISI, Italy(BDS)"},
{value:"BNE", label:"Brisbane/BRISBANE, Australia(BNE)"},
{value:"BRS", label:"Bristol/BRISTOL, United Kingdom(BRS)"},
{value:"BVE", label:"Brive - La - Gaillarde/BRIVE-LA-GAIL, France(BVE)"},
{value:"BME", label:"Broome/BROOME, Australia(BME)"},
{value:"BRO", label:"Brownsville/BROWNSVILLE, United States(BRO)"},
{value:"BRU", label:"Brussels/BRUSSELS, Belgium(BRU)"},
{value:"BGA", label:"Bucaramanga/BUCARAMANGA, Colombia(BGA)"},
{value:"BBU", label:"Bucharest/Baneasa/BUCHAREST, Romania(BBU)"},
{value:"OTP", label:"Bucharest/Otopeni/BUCHAREST, Romania(OTP)"},
{value:"BUD", label:"Budapest/Ferihegy/BUDAPEST, Hungary(BUD)"},
{value:"BUE", label:"Buenos Aires Airport/BUENOS AIRES, Argentina(BUE)"},
{value:"AEP", label:"Buenos Aires, Argentina/BUENOS AIRES, Argentina(AEP)"},
{value:"BUF", label:"Buffalo/BUFFALO, United States(BUF)"},
{value:"BDB", label:"Bundaberg/BUNDABERG, Australia(BDB)"},
{value:"BUR", label:"Burbank/LOS ANGELES, United States(BUR)"},
{value:"BTV", label:"Burlington Intl/BURLINGTON VT, United States(BTV)"},
{value:"BRL", label:"Burlington Municipal/BURLINGTON, United States(BRL)"},
{value:"BWT", label:"Burnie/BURNIE, Australia(BWT)"},
{value:"PUS", label:"Busan/BUSAN, Korea, Republic Of(PUS)"},
{value:"BTM", label:"Butte/BUTTE, United States(BTM)"},
{value:"CAG", label:"Cagliari Elmas Italy/CAGLIARI, Italy(CAG)"},
{value:"CNS", label:"Cairns/CAIRNS, Australia(CNS)"},
{value:"CAI", label:"Cairo/CAIRO, Egypt(CAI)"},
{value:"CJA", label:"Cajamarca/CAJAMARCA, Peru(CJA)"},
{value:"CJC", label:"Calama/CALAMA, Chile(CJC)"},
{value:"YYC", label:"Calgary/CALGARY, Canada(YYC)"},
{value:"CLO", label:"Cali/CALI, Colombia(CLO)"},
{value:"CCJ", label:"Calicut/CALICUT, India(CCJ)"},
{value:"CLY", label:"Calvi/CALVI, France(CLY)"},
{value:"CGR", label:"Cam Grande/CAM GRANDE, Brazil(CGR)"},
{value:"CUC", label:"Camilo Daza Intl Apt/CUCUTA, Colombia(CUC)"},
{value:"CAL", label:"Campbeltown/CAMPBELTOWN, United Kingdom(CAL)"},
{value:"CBR", label:"Canberra/CANBERRA, Australia(CBR)"},
{value:"CUN", label:"Cancun/CANCUN, Mexico(CUN)"},
{value:"CIW", label:"Canouan Island/CANOUAN ISLAND, Saint Vincent And The Grenadines(CIW)"},
{value:"CAP", label:"Cap Haitien/CAP HAITIEN, Haiti(CAP)"},
{value:"CGI", label:"Cape Girardeau Municipal/CAPE GIRARDEAU, United States(CGI)"},
{value:"CPT", label:"Cape Town/CAPE TOWN, South Africa(CPT)"},
{value:"CCS", label:"Caracas/CARACAS, Venezuela(CCS)"},
{value:"CWL", label:"Cardiff/CARDIFF, United Kingdom(CWL)"},
{value:"CLD", label:"Carlsbad/CARLSBAD CA, United States(CLD)"},
{value:"CTG", label:"Cartagena/CARTAGENA, Colombia(CTG)"},
{value:"CAS", label:"Casablanca Anfa/CASABLANCA, Morocco(CAS)"},
{value:"CMN", label:"Casablanca Mohamed V/CASABLANCA, Morocco(CMN)"},
{value:"DCM", label:"Castres/CASTRES, France(DCM)"},
{value:"CTA", label:"Catania/CATANIA, Italy(CTA)"},
{value:"CAY", label:"Cayenne/CAYENNE, French Guiana(CAY)"},
{value:"CEB", label:"Cebu/CEBU, Philippines(CEB)"},
{value:"CID", label:"Cedar Rapids/CEDAR RAPI, United States(CID)"},
{value:"CMF", label:"Chambery/CHAMBERY, France(CMF)"},
{value:"CMI", label:"Champaign/CHAMPAIGN, United States(CMI)"},
{value:"IXC", label:"Chandigarh/CHANDIGARH, India(IXC)"},
{value:"CGQ", label:"Changchun/CHANGCHUN, China(CGQ)"},
{value:"CSX", label:"Changsha/CHANGSHA, China(CSX)"},
{value:"CIH", label:"Changzhi/CHANGZHI, China(CIH)"},
{value:"CZX", label:"Changzhou/CHANGZHOU, China(CZX)"},
{value:"CHQ", label:"Chania/CHANIA, Greece(CHQ)"},
{value:"CHG", label:"Chaoyang/CHAOYANG, China(CHG)"},
{value:"CHS", label:"Charleston Municipal/CHARLESTON SC, United States(CHS)"},
{value:"CRW", label:"Charleston Yeager/CHARLESTON WV, United States(CRW)"},
{value:"CTL", label:"Charleville/CHARLEVIL, Australia(CTL)"},
{value:"CLT", label:"Charlotte/CHARLOTTE, United States(CLT)"},
{value:"CHO", label:"Charlottesville/CHARLOTTES, United States(CHO)"},
{value:"CHA", label:"Chattanooga/CHATTANOOG, United States(CHA)"},
{value:"CJU", label:"Cheju/JEJU, Korea, Republic Of(CJU)"},
{value:"CEK", label:"Chelyabinsk/CHELYABINSK, Russian Federation(CEK)"},
{value:"CTU", label:"Chengdu/Shuangliu/CHENGDU, China(CTU)"},
{value:"MAA", label:"Chennai/CHENNAI, India(MAA)"},
{value:"CJJ", label:"Cheong Ju City/CHEONG JU CITY, Korea, Republic Of(CJJ)"},
{value:"CTM", label:"Chetumal/CHETUMAI, Mexico(CTM)"},
{value:"CNX", label:"Chiang Mai/CHIANG MAI, Thailand(CNX)"},
{value:"CEI", label:"Chiang Rai/CHIANG RAI, Thailand(CEI)"},
{value:"ORD", label:"Chicago/O&acute;Hare Intl/CHICAGO, United States(ORD)"},
{value:"CIX", label:"Chiclayo/CHICLAYO, Peru(CIX)"},
{value:"CIF", label:"Chifeng/CHIFENG, China(CIF)"},
{value:"CUU", label:"Chihuahua/CHIHUAHUA, Mexico(CUU)"},
{value:"YAI", label:"Chillan/CHILLAN, Chile(YAI)"},
{value:"CIT", label:"Chimkent/CHIMKENT, Kazakhstan(CIT)"},
{value:"HTA", label:"Chita/CHITA, Russian Federation(HTA)"},
{value:"CKG", label:"Chongqing/CHONGQING, China(CKG)"},
{value:"CHC", label:"Christchurch/CHRISTCHURCH, New Zealand(CHC)"},
{value:"CVG", label:"Cincinnati/CINCINNATI, United States(CVG)"},
{value:"CME", label:"Ciudad Del Carmen/CIUDAD DEL CARMEN, Mexico(CME)"},
{value:"AGT", label:"Ciudad Pred Stroessner/CIUDAD D ESTE, Paraguay(AGT)"},
{value:"CRK", label:"Clark/Luzon Island/CLARK/LUZON ISLAND, Philippines(CRK)"},
{value:"CFE", label:"Clermont-Ferrand/CLERMONT-FERRAND, France(CFE)"},
{value:"CLE", label:"Cleveland Hopkins/CLEVELAND, United States(CLE)"},
{value:"COK", label:"Cochin/COCHIN, India(COK)"},
{value:"CFS", label:"Coffs Harbour/COFFS HARBOUR, Australia(CFS)"},
{value:"CJB", label:"Coimbatore/COIMBATORE, India(CJB)"},
{value:"CLL", label:"College Station/COLLEGE STATION, United States(CLL)"},
{value:"CGN", label:"Cologne/COLOGNE, Germany(CGN)"},
{value:"CMB", label:"Colombo/Katunayake/COLOMBO, Sri Lanka(CMB)"},
{value:"COS", label:"Colorado Springs/COLORADO SPRINGS, United States(COS)"},
{value:"CAE", label:"Columbia Metropolitan Apt/COLUMBIA SC, United States(CAE)"},
{value:"COU", label:"Columbia Regional/COLUMBIA MO, United States(COU)"},
{value:"CMH", label:"Columbus/COLUMBUS OH, United States(CMH)"},
{value:"CSG", label:"Columbus Metroplitan Apt/COLUMBIA GA, United States(CSG)"},
{value:"CRD", label:"Comodoro Rivadavia/COMODORO RIVA, Argentina(CRD)"},
{value:"CCP", label:"Concepcion/CONCEPCION, Chile(CCP)"},
{value:"OOL", label:"Coolangatta/Gold Coast/COOLANGATTA/GOLD COAST, Australia(OOL)"},
{value:"CPH", label:"Copenhagen/COPENHAGEN, Denmark(CPH)"},
{value:"CPO", label:"Copiapo/COPIAPO, Chile(CPO)"},
{value:"COR", label:"Cordoba/CORDOBA, Argentina(COR)"},
{value:"CDV", label:"Cordova Mudhole Smith Apt/CORDOVA, United States(CDV)"},
{value:"ORK", label:"Cork/CORK, Ireland(ORK)"},
{value:"CRP", label:"Corpus Christi/CORPUS CHRISTI, United States(CRP)"},
{value:"CVT", label:"Coventry/COVENTRY, United Kingdom(CVT)"},
{value:"CZM", label:"Cozumel/COZUMEL, Mexico(CZM)"},
{value:"CUE", label:"Cuenca/CUENCA, Spain And Canary Islands(CUE)"},
{value:"CGB", label:"Cuiaba/CUIBA, Brazil(CGB)"},
{value:"CUL", label:"Culiacan/CULIACAN, Mexico(CUL)"},
{value:"YCU", label:"Cullaton Lake/YUN CHENG, China(YCU)"},
{value:"CUR", label:"Curacao/CURACAO, Netherlands Antilles(CUR)"},
{value:"CWB", label:"Curitiba/CURITIBA, Brazil(CWB)"},
{value:"CUH", label:"Cushing/CUSHING, United States(CUH)"},
{value:"CUZ", label:"Cuzco/CUSCO, Peru(CUZ)"},
{value:"DKR", label:"Dakar/DAKAR, Senegal(DKR)"},
{value:"DLM", label:"Dalaman/DALAMAN, Turkey(DLM)"},
{value:"DLU", label:"Dali City/DALI CITY, China(DLU)"},
{value:"DLC", label:"Dalian/DALIAN, China(DLC)"},
{value:"DFW", label:"Dallas/Fort Worth/DALLAS/FORTWORTH, United States(DFW)"},
{value:"DAM", label:"Damascus Intl/DAMASCUS, Syrian Arab Republic(DAM)"},
{value:"DMM", label:"Dammam King Fahd Intl/DAMMAM, Saudi Arabia(DMM)"},
{value:"DAD", label:"Danang/DA NANG, Vietnam(DAD)"},
{value:"DDG", label:"Dandong/DANDONG, China(DDG)"},
{value:"DCY", label:"Daocheng Yading Airport/DAOCHENG, China(DCY)"},
{value:"DQA", label:"Daqing/DAQING, China(DQA)"},
{value:"DAR", label:"Dar Es Salaam/DAR ES SALAAM, Tanzania, United Republic(DAR)"},
{value:"DRW", label:"Darwin/DARWIN, Australia(DRW)"},
{value:"DAT", label:"Datong/DATONG, China(DAT)"},
{value:"DAX", label:"Daxian/DAXIAN, China(DAX)"},
{value:"DYG", label:"Dayong/DAYONG, China(DYG)"},
{value:"DAY", label:"Dayton/DAYTON, United States(DAY)"},
{value:"DAB", label:"Daytona Beach/DAYTONA BEACH, United States(DAB)"},
{value:"DEC", label:"Decatur/DECATUR, United States(DEC)"},
{value:"DED", label:"Dehradun/DEHRA DUN, India(DED)"},
{value:"DEL", label:"Delhi/DELHI, India(DEL)"},
{value:"DEN", label:"Denver/DENVER, United States(DEN)"},
{value:"FMO", label:"Der-Muenster/MUENSTER, Germany(FMO)"},
{value:"DSM", label:"Des Moines/DES MOINES, United States(DSM)"},
{value:"DTW", label:"Detroit/Metropolitan/DETROIT, United States(DTW)"},
{value:"DPO", label:"Devonport/DEVONPORT, Australia(DPO)"},
{value:"DHA", label:"Dhahran/DHAHRAN, Saudi Arabia(DHA)"},
{value:"DAC", label:"Dhaka/DHAKA, Bangladesh(DAC)"},
{value:"DIL", label:"Dili/DILI, Indonesia(DIL)"},
{value:"DLG", label:"Dillingham/DILLINGHAM, United States(DLG)"},
{value:"DMU", label:"Dimapur/DIMAPUR, India(DMU)"},
{value:"DIG", label:"Diqing/DIQING, China(DIG)"},
{value:"DIU", label:"Diu/DIU, India(DIU)"},
{value:"DJE", label:"Djerba/DJERBA, Tunisia(DJE)"},
{value:"JIB", label:"Djibouti/DJIBOUTI, Djibouti(JIB)"},
{value:"DOH", label:"Doha/DOHA, Qatar(DOH)"},
{value:"DOM", label:"Dominica/DOMINICA, Dominica(DOM)"},
{value:"CFN", label:"Donegal/CARRICKFINN, Ireland(CFN)"},
{value:"DSN", label:"Dongsheng/DONGSHENG, China(DSN)"},
{value:"DOY", label:"Dongying/DONGYING, China(DOY)"},
{value:"DTM", label:"Dortmund/DORTMUND, Germany(DTM)"},
{value:"DRS", label:"Dresden/DRESEDN, Germany(DRS)"},
{value:"DXB", label:"Dubai/DUBAI, United Arab Emirates(DXB)"},
{value:"DBO", label:"Dubbo/DUBBO, Australia(DBO)"},
{value:"DUB", label:"Dublin/DUBLIN, Ireland(DUB)"},
{value:"DBV", label:"Dubrovnik/DUBROVNIK, Croatia(DBV)"},
{value:"DBQ", label:"Dubuque/DUBUQUE, United States(DBQ)"},
{value:"DLH", label:"Duluth/DULUTH, United States(DLH)"},
{value:"DUD", label:"Dunedin/DUNEDIN, New Zealand(DUD)"},
{value:"DNH", label:"Dunhuang/DUNHUANG, China(DNH)"},
{value:"DRO", label:"Durango/DURANGO, United States(DRO)"},
{value:"DUR", label:"Durban/DURBAN, South Africa(DUR)"},
{value:"DYU", label:"Dushanbe/DUSHANBE, Tadjikistan(DYU)"},
{value:"DUS", label:"Dusseldorf/DUSSELDORF, Germany(DUS)"},
{value:"DUT", label:"Dutch Harbour/DUTCH HARB, United States(DUT)"},
{value:"IPC", label:"Easter Island/EASTER ISLAND, Chile(IPC)"},
{value:"SHV", label:"Eceport Regional Apt/SHREVEPORT, United States(SHV)"},
{value:"EOI", label:"Eday/EDAY ISLAND, United Kingdom(EOI)"},
{value:"EDI", label:"Edinburgh/EDINBURGH, United Kingdom(EDI)"},
{value:"YEG", label:"Edmonton/EDMONTON, Canada(YEG)"},
{value:"EIN", label:"Eindhoven Airport/EINDHOVEN, Netherlands(EIN)"},
{value:"EYP", label:"El Alcaravan Airport/EL YOPAL, Colombia(EYP)"},
{value:"FTE", label:"El Calafate/EL CALAFATE, Argentina(FTE)"},
{value:"UIB", label:"El Carano Apt/QUIBDO, Colombia(UIB)"},
{value:"ELP", label:"El Paso/EL PASO, United States(ELP)"},
{value:"ESR", label:"El Salvador/EL SALVADOR, Chile(ESR)"},
{value:"ELM", label:"Elmira Corning/CORNING, United States(ELM)"},
{value:"EMD", label:"Emerald/EMERALD, Australia(EMD)"},
{value:"NBE", label:"Enfidha/ENFIDHA, Tunisia(NBE)"},
{value:"ENF", label:"Enontekio/ENONTEKIO, Finland(ENF)"},
{value:"EOH", label:"Enrique Olaya Herrera Apt/MEDELLIN, Colombia(EOH)"},
{value:"ENH", label:"Enshi/ENSHI, China(ENH)"},
{value:"EBB", label:"Entebbe/ENTEBBE, Uganda(EBB)"},
{value:"EBL", label:"Erbil/ERBIL, Iraq(EBL)"},
{value:"ERF", label:"Erfurt/ERFURT, Germany(ERF)"},
{value:"ERI", label:"Erie/ERIE, United States(ERI)"},
{value:"EBJ", label:"Esbjerg Airport/ESBJERG, Denmark(EBJ)"},
{value:"IFN", label:"Esfahan/ISFAHAN, Iran (Islamic Republic Of)(IFN)"},
{value:"EUG", label:"Eugene/EUGENE, United States(EUG)"},
{value:"EAP", label:"Euroairport/BASLE, Switzerland(EAP)"},
{value:"EVV", label:"Evansville/EVANSVILLE, United States(EVV)"},
{value:"EXT", label:"Exeter/EXETER, United Kingdom(EXT)"},
{value:"FIE", label:"Fair Isle/FAIR ISLE, United Kingdom(FIE)"},
{value:"FAI", label:"Fairbanks/FAIRBANKS, United States(FAI)"},
{value:"LYP", label:"Faisalabad/FAISALABAD, Pakistan(LYP)"},
{value:"FAR", label:"Fargo/FARGO, United States(FAR)"},
{value:"FAO", label:"Faro/FARO, Portugal(FAO)"},
{value:"FAE", label:"Faroe Islands/FAROE ISLAND, Denmark(FAE)"},
{value:"FYV", label:"Fayetteville/FAYETTEVI, United States(FYV)"},
{value:"FAY", label:"Fayetteville Municipal Apt/FAYETTEVIL, United States(FAY)"},
{value:"XNA", label:"Fayetteville Northwest/FAYETTEVI, United States(XNA)"},
{value:"FEG", label:"Fergana/FERGANA, Uzbekistan(FEG)"},
{value:"FSC", label:"Figari/FIGARI CORSIC, France(FSC)"},
{value:"NAN", label:"Fiji Nandi International/NADI/FIJI, Fiji(NAN)"},
{value:"FNT", label:"Flint/FLINT, United States(FNT)"},
{value:"FLO", label:"Florence/FLORENCE SC, United States(FLO)"},
{value:"FLR", label:"Florence Amerigo Vespucci/FLORENCE, Italy(FLR)"},
{value:"FLN", label:"Florianopolis H Luz/FLORIANOPOLIS H LUZ, Brazil(FLN)"},
{value:"FRL", label:"Forli/FORLI, Italy(FRL)"},
{value:"FDF", label:"Fort De France/FT DE FRANCE, Martinique(FDF)"},
{value:"FLL", label:"Fort Lauderdale/FORT LAUDERDALE, United States(FLL)"},
{value:"TBN", label:"Fort Leonard Wood Forney/FORT LEONARD WOOD, United States(TBN)"},
{value:"FMY", label:"Fort Meyers/FT MYERS, United States(FMY)"},
{value:"RSW", label:"Fort Myers/FT MYERS, United States(RSW)"},
{value:"FSM", label:"Fort Smith Municipal/FT SMITH, United States(FSM)"},
{value:"VPS", label:"Fort Walton Beach/EGLIN AIR FORCE BASE, United States(VPS)"},
{value:"FWA", label:"Fort Wayne/FORT WAYNE, United States(FWA)"},
{value:"FOR", label:"Fortaleza/FORTALEZA, Brazil(FOR)"},
{value:"FOA", label:"Foula/FOULA, Italy(FOA)"},
{value:"FRA", label:"Frankfurt/FRANKFURT, Germany(FRA)"},
{value:"FPO", label:"Freeport/FREEPORT, Bahamas(FPO)"},
{value:"FNA", label:"Freetown Lungi Intl Apt/FREETOWN, Sierra Leone(FNA)"},
{value:"FAT", label:"Fresno/FRESNO, United States(FAT)"},
{value:"FDH", label:"Friedrichshafen/FRIEDRICHSHAF, Germany(FDH)"},
{value:"FOC", label:"Fu Zhou/FUZHOU, China(FOC)"},
{value:"FUE", label:"Fuerteventura/FUERTEVENTURA, Spain And Canary Islands(FUE)"},
{value:"FUK", label:"Fukuoka/FUKUOKA, Japan(FUK)"},
{value:"FKS", label:"Fukushima/FUKUSHIMA, Japan(FKS)"},
{value:"FNC", label:"Funchal/FUNCHAL, Portugal(FNC)"},
{value:"FUG", label:"Fuyang/FUYANG, China(FUG)"},
{value:"GBE", label:"Gaborone Sir Seretse Khama/GABORONE, Botswana(GBE)"},
{value:"GNV", label:"Gainesville/GAINESVILLE, United States(GNV)"},
{value:"GPS", label:"Galapagos/GALAPAGOS, Ecuador(GPS)"},
{value:"SCY", label:"Galapagos San Cristobal/GALAPAGOS, Ecuador(SCY)"},
{value:"GWY", label:"Galway/GALWAY, Ireland(GWY)"},
{value:"YQX", label:"Gander/GANDER, Canada(YQX)"},
{value:"KOW", label:"Ganzhou/GANZHOU, China(KOW)"},
{value:"YZY", label:"Ganzhou/ZHANGYE, China(YZY)"},
{value:"GCK", label:"Garden City/GARDEN CITY KS, United States(GCK)"},
{value:"XHK", label:"Gare De Valence Tgv/VALENCE, France(XHK)"},
{value:"ELQ", label:"Gassim/GASSIM, Saudi Arabia(ELQ)"},
{value:"GAU", label:"Gauhati/GAWAHATI, India(GAU)"},
{value:"GZP", label:"Gazipasa/GAZIPASA, Turkey(GZP)"},
{value:"BDT", label:"Gbadolite/GBADOLITE, Zaire(BDT)"},
{value:"GDN", label:"Gdansk/GDANSK, Poland(GDN)"},
{value:"DLD", label:"Geilo/GEILO, Norway(DLD)"},
{value:"MKE", label:"Gen Mitchell Intl/MILWAUKEE, United States(MKE)"},
{value:"GVA", label:"Geneva/GENEVA, Switzerland(GVA)"},
{value:"GOA", label:"Genova/GENOA, Italy(GOA)"},
{value:"GRJ", label:"George/GEORGE, South Africa(GRJ)"},
{value:"GGT", label:"George Town/GEORGE TOWN, Bahamas(GGT)"},
{value:"GET", label:"Geraldton/GERALDTOWN, Australia(GET)"},
{value:"GRO", label:"Gerona/GERONA, Spain And Canary Islands(GRO)"},
{value:"GIB", label:"Gibraltar/GIBRALTAR, Gibraltar(GIB)"},
{value:"GBW", label:"Ginbata Airpor/JIMBLEBAR MINE, Australia(GBW)"},
{value:"GLT", label:"Gladstone/GLADSTONE, Australia(GLT)"},
{value:"GLA", label:"Glasgow/GLASGOW, United Kingdom(GLA)"},
{value:"GOI", label:"Goa/GOA, India(GOI)"},
{value:"GYN", label:"Goiania/GOIANIA, Brazil(GYN)"},
{value:"GOQ", label:"Golmud/GOLMUD, China(GOQ)"},
{value:"GOT", label:"Goteborg/Landvetter/GOTHENBURG, Sweden(GOT)"},
{value:"GOV", label:"Gove/GOVE, Australia(GOV)"},
{value:"GFN", label:"Grafton/GRAFTON, Australia(GFN)"},
{value:"GRX", label:"Granada/GRANADA, Spain And Canary Islands(GRX)"},
{value:"FLG", label:"Grand Canyon Pulliam Field/GRAND CANYON, United States(FLG)"},
{value:"GCM", label:"Grand Cayman/GRAND CAYMAN, Caynan Islands(GCM)"},
{value:"GRI", label:"Grand Island Army Airfield/GRAND ISLAND, United States(GRI)"},
{value:"GJT", label:"Grand Junction/GRAND JUNCTION, United States(GJT)"},
{value:"GRR", label:"Grand Rapids/GRAND RAPIDS MI, United States(GRR)"},
{value:"GRZ", label:"Graz/GRAZ, Austria(GRZ)"},
{value:"GTF", label:"Great Falls Intl Apt/GREAT FALLS, United States(GTF)"},
{value:"GRB", label:"Green Bay/GREEN BAY, United States(GRB)"},
{value:"GSO", label:"Greensboro/GREENSBORO, United States(GSO)"},
{value:"GSP", label:"Greenville/GREENVILLE SC, United States(GSP)"},
{value:"GND", label:"Grenada/GRENOBLE, France(GND)"},
{value:"GNB", label:"Grenoble/GRENOBLE, France(GNB)"},
{value:"PGV", label:"Greville/GREENVILLE NC, United States(PGV)"},
{value:"GDL", label:"Guadalajara/GUADALAJARA, Mexico(GDL)"},
{value:"GUM", label:"Guam/GUAM, Guam(GUM)"},
{value:"GYS", label:"Guang Yuan/GUANG YUAN, China(GYS)"},
{value:"CAN", label:"Guangzhou(Canton)/GUANGZHOU, China(CAN)"},
{value:"GUA", label:"Guatemala City/GUATEMALA CTY, Guatemala(GUA)"},
{value:"GYE", label:"Guayaguil/GUAYAQUIL, Ecuador(GYE)"},
{value:"GCI", label:"Guernsey/GUERNSEY, United Kingdom(GCI)"},
{value:"KWL", label:"Guilin/GUILIN, China(KWL)"},
{value:"KWE", label:"Guiyang/GUIYANG, China(KWE)"},
{value:"GPT", label:"Gulfport Biloxi/GULFPORT, United States(GPT)"},
{value:"GUC", label:"Gunnison/GUNNISON, United States(GUC)"},
{value:"ADZ", label:"Gustavo Rojas Pinilla/SAN ANDRES, Colombia(ADZ)"},
{value:"LWN", label:"Gyoumri/GYOUMRI, Armenia(LWN)"},
{value:"HAK", label:"Haikou/HAIKOU, China(HAK)"},
{value:"HLD", label:"Hailar/HAILAR, China(HLD)"},
{value:"HKD", label:"Hakodate/HAKODATE, Japan(HKD)"},
{value:"YHZ", label:"Halifax/HALIFAX, Canada(YHZ)"},
{value:"HAM", label:"Hamburg/HAMBURG, Germany(HAM)"},
{value:"HMI", label:"Hami Airport/HAMI, China(HMI)"},
{value:"HLZ", label:"Hamilton/HAMILTON, New Zealand(HLZ)"},
{value:"HTI", label:"Hamilton Island/HAMILTON ISLAND, Australia(HTI)"},
{value:"HLT", label:"Hamilton Vic/HAMILTON, Australia(HLT)"},
{value:"HDG", label:"Handan/HANDAN, China(HDG)"},
{value:"HND", label:"Haneda/TOKYO, Japan(HND)"},
{value:"HGH", label:"Hangzhou/Xiaoshan/HANGZHOU, China(HGH)"},
{value:"HAN", label:"Hanoi/HANOI, Vietnam(HAN)"},
{value:"HAJ", label:"Hanover/HANOVER, Germany(HAJ)"},
{value:"HZG", label:"Hanzhong Airport/HANZHONG, China(HZG)"},
{value:"HRE", label:"Harare/HARARE, Zimbabwe(HRE)"},
{value:"HGA", label:"Hargeisa/HARGEISA, Somalia(HGA)"},
{value:"HSB", label:"Harigbury/Raleigh/HARIGBURY/RALEIGH, United States(HSB)"},
{value:"HRL", label:"Harligen/HARLINGEN, United States(HRL)"},
{value:"HAR", label:"Harrisburg Skyport Airport/HARRISBURG, United States(HAR)"},
{value:"BDL", label:"Hartford Bradley Intl/HARTFORD, United States(BDL)"},
{value:"HME", label:"Hassi Messaou/HASSI MESSAOU, Algeria(HME)"},
{value:"HAV", label:"Havana/HAVANA, Cuba(HAV)"},
{value:"HDN", label:"Hayden Yampa Valley/STEAMBT SPRINGS, United States(HDN)"},
{value:"HIS", label:"Hayman Island/HAYMAN ISLAND, Australia(HIS)"},
{value:"HFE", label:"Hefei/HEFEI, China(HFE)"},
{value:"HEK", label:"Heihe/HEIHE, China(HEK)"},
{value:"HLN", label:"Helena/HELENA, United States(HLN)"},
{value:"HEL", label:"Helsinki/HELSINKI, Finland(HEL)"},
{value:"HER", label:"Heraklion/HERAKLION, Greece(HER)"},
{value:"HDF", label:"Heringsdorf/HERINGSDORF, Germany(HDF)"},
{value:"HMO", label:"Hermosillo/HERMOSILLO, Mexico(HMO)"},
{value:"HVB", label:"Hervey Bay/HERVEY BAY, Australia(HVB)"},
{value:"ITO", label:"Hilo/HILO, United States(ITO)"},
{value:"HHH", label:"Hilton Head Island/HILTON HEAD, United States(HHH)"},
{value:"HIJ", label:"Hiroshima/HIROSHIMA, Japan(HIJ)"},
{value:"HIW", label:"Hiroshima West/HIROSHIMA, Japan(HIW)"},
{value:"SGN", label:"Ho Chi Minh City/HO CHI MINH CITY, Vietnam(SGN)"},
{value:"HBA", label:"Hobart/HOBART, Australia(HBA)"},
{value:"HDS", label:"Hoedspruit/HOEDSPRUIT, South Africa(HDS)"},
{value:"HET", label:"Hohhot/HOHHOT, China(HET)"},
{value:"HKG", label:"Hong Kong/HONG KONG, Hong Kong,SAR(HKG)"},
{value:"AHJ", label:"Hongyuan/HONGYUAN, China(AHJ)"},
{value:"HNL", label:"Honolulu/HONOLULU HI, United States(HNL)"},
{value:"HID", label:"Horn Island/HORN ISLAND, Australia(HID)"},
{value:"HTN", label:"Hotan/HOTAN, China(HTN)"},
{value:"EFD", label:"Houston Ellington Field/HOUSTON, United States(EFD)"},
{value:"HOU", label:"Houston/Hobby/HOUSTON, United States(HOU)"},
{value:"IAH", label:"Houston/Intercontinental/HOUSTON, United States(IAH)"},
{value:"HIA", label:"Huaian/HUAIAN, China(HIA)"},
{value:"HHA", label:"Huanghua/Changsha, China(HHA)"},
{value:"HYN", label:"Huangyan/HUANGYAN, China(HYN)"},
{value:"HUX", label:"Huatulco/STA CRUZ HUAT, Mexico(HUX)"},
{value:"HUY", label:"Humberside/HUMBERSIDE, United Kingdom(HUY)"},
{value:"HTS", label:"Huntington/HUNTINGTON, United States(HTS)"},
{value:"HSV", label:"Huntsville/HUNTSVILLE, United States(HSV)"},
{value:"HRG", label:"Hurghada/HURGHADA, Egypt(HRG)"},
{value:"HYD", label:"Hyderabad/HYDERABAD, India(HYD)"},
{value:"IAS", label:"Iasi/IASI, Romania(IAS)"},
{value:"IBZ", label:"Ibiza/IBIZA, Spain And Canary Islands(IBZ)"},
{value:"IDA", label:"Idaho Falls/IDAHO FALLS, United States(IDA)"},
{value:"IGU", label:"Iguassu Falls/IGUASSU FALLS, Brazil(IGU)"},
{value:"IGR", label:"Iguazu, Argentina/IGUAZU, Argentina(IGR)"},
{value:"MOB", label:"Ile Municipal Airport/MOBILE, United States(MOB)"},
{value:"IOS", label:"Ilheus/ILHEUS, Brazil(IOS)"},
{value:"IKA", label:"Imam Khomeini/TEHRAN, Iran (Islamic Republic Of)(IKA)"},
{value:"IMP", label:"Imperatriz Airport/IMPERATRIZ, Brazil(IMP)"},
{value:"ICN", label:"Incheon/SEOUL, Korea, Republic Of(ICN)"},
{value:"IND", label:"Indianapolis/INDIANAPOLIS, United States(IND)"},
{value:"IDR", label:"Indore/INDORE, India(IDR)"},
{value:"INN", label:"Innsbruck/INNSBRUCK, Austria(INN)"},
{value:"IVC", label:"Invercargill/INVERCARGILL, New Zealand(IVC)"},
{value:"INV", label:"Inverness/INVERNESS, United Kingdom(INV)"},
{value:"CFU", label:"Ioannies Kapodistrias/CORFU, Greece(CFU)"},
{value:"IQQ", label:"Iquique/IQUIQUE, Chile(IQQ)"},
{value:"IQT", label:"Iquitos/IQUITOS, Peru(IQT)"},
{value:"IKT", label:"Irkutsk/IRKUTSK, Russian Federation(IKT)"},
{value:"ISG", label:"Ishigaki/ISHIGAKI, Japan(ISG)"},
{value:"ISB", label:"Islamabad/ISLAMABAD, Pakistan(ISB)"},
{value:"ILY", label:"Islay/ISLAY, United Kingdom(ILY)"},
{value:"IOM", label:"Isle Of Man/ISLE OF MAN, United Kingdom(IOM)"},
{value:"ISP", label:"Islip/ISLIP, United States(ISP)"},
{value:"IST", label:"Istanbul/ISTANBUL, Turkey(IST)"},
{value:"ITM", label:"Itami/OSAKA, Japan(ITM)"},
{value:"ITH", label:"Ithaca/ITHACA, United States(ITH)"},
{value:"IVL", label:"Ivalo/IVALO, Finland(IVL)"},
{value:"ZIH", label:"Ixtapa/Zihuatanejo/ZIHUATANEJO, Mexico(ZIH)"},
{value:"IZO", label:"Izumo/IZUMO, Japan(IZO)"},
{value:"JAC", label:"Jackson/JACKSON WY, United States(JAC)"},
{value:"MKL", label:"Jackson/JACKSON, United States(MKL)"},
{value:"JAN", label:"Jackson Thompson Field/JACKSON MS, United States(JAN)"},
{value:"OAJ", label:"Jacksonville/JACKSONVILLE NC, United States(OAJ)"},
{value:"JAX", label:"Jacksonville International/JACKSONVILLE FL, United States(JAX)"},
{value:"JAI", label:"Jaipur/JAIPUR, India(JAI)"},
{value:"CGK", label:"Jakarta/JAKARTA, Indonesia(CGK)"},
{value:"IXJ", label:"Jammu/JAMMU, India(IXJ)"},
{value:"JED", label:"Jeddah/King Abdul Aziz Intl/JEDDAH, Saudi Arabia(JED)"},
{value:"XRY", label:"Jerez De La Frontera/JEREZ DE LA FRONTERA, Spain And Canary Islands(XRY)"},
{value:"JER", label:"Jersey/JERSEY, United Kingdom(JER)"},
{value:"JGS", label:"Ji An/Jing Gang Shan/JI AN/JING GANG SHAN, China(JGS)"},
{value:"JGD", label:"Jiagedaqi/JIAGEDAQI, China(JGD)"},
{value:"JMU", label:"Jiamusi/JIAMUSI, China(JMU)"},
{value:"JGN", label:"Jiayuquan/JIAYUGUAN, China(JGN)"},
{value:"TNA", label:"Jinan/JINAN, China(TNA)"},
{value:"JDZ", label:"Jingdezhen/JINGDEZHEN, China(JDZ)"},
{value:"JHG", label:"Jinghong/JINGHONG, China(JHG)"},
{value:"JNG", label:"Jining/JINING, China(JNG)"},
{value:"JJN", label:"Jinjiang/JINJIANG, China(JJN)"},
{value:"JNZ", label:"Jinzhou/JINZHOU, China(JNZ)"},
{value:"JPA", label:"Joa Pessoa/JOA PESSOA, Brazil(JPA)"},
{value:"JDH", label:"Jodhpur/JODHPUR, India(JDH)"},
{value:"JOE", label:"Joensuu/JOENSUU, Finland(JOE)"},
{value:"JNB", label:"Johannesburg/JOHANNESBURG, South Africa(JNB)"},
{value:"JHB", label:"Johor Baru/JOHOR BAHRU, Malaysia(JHB)"},
{value:"JOI", label:"Joinville/JOINVILLE, Brazil(JOI)"},
{value:"JLN", label:"Joplin Municipal/JOPLIN, United States(JLN)"},
{value:"JRH", label:"Jorhat/JORHAT, India(JRH)"},
{value:"JUL", label:"Juliaca/JULIACA, Peru(JUL)"},
{value:"JNU", label:"Juneau/JUNEAU, United States(JNU)"},
{value:"JUZ", label:"Juzhow/JUZHOU, China(JUZ)"},
{value:"JYV", label:"Jyvaskyla/JYVASKYLA, Finland(JYV)"},
{value:"KOJ", label:"Kagoshima/KAGOSHIMA, Japan(KOJ)"},
{value:"OGG", label:"Kahului/KAHULUI, United States(OGG)"},
{value:"KAJ", label:"Kajaani/KAJAANI, Finland(KAJ)"},
{value:"KLX", label:"Kalamata/KALAMATA, Greece(KLX)"},
{value:"AZO", label:"Kalamazoo/KALAMAZOO, United States(AZO)"},
{value:"KGI", label:"Kalgoorlie/KALGOORLIE, Australia(KGI)"},
{value:"KGD", label:"Kaliningrad/KALININGRAD, Russian Federation(KGD)"},
{value:"FCA", label:"Kalispell/KALISPELL, United States(FCA)"},
{value:"UKK", label:"Kamenogorsk/UST-KAMENOGORSK, Kazakhstan(UKK)"},
{value:"YKA", label:"Kamloops/KAMLOOPS, Canada(YKA)"},
{value:"KGT", label:"Kangding/KANGDING, China(KGT)"},
{value:"SFJ", label:"Kangerlussuaq/SONDRE STROMF, Greenland(SFJ)"},
{value:"KAN", label:"Kano/KANO, Nigeria(KAN)"},
{value:"MCI", label:"Kansas/KANSAS CITY DOWN TOWN, United States(MCI)"},
{value:"MKC", label:"Kansas City Downtown Apt/KANSAS CITY DOWN TOWN, United States(MKC)"},
{value:"KHH", label:"Kaohsiung(Gaoxiong)/KAOHSIUNG, Taiwan(KHH)"},
{value:"KMZ", label:"Kaoma/KAOMA, Zambia(KMZ)"},
{value:"KHI", label:"Karachi/KARACHI, Pakistan(KHI)"},
{value:"FKB", label:"Karlsruhe/Baden/KARLSRUHE/BADEN, Germany(FKB)"},
{value:"AOK", label:"Karpathos/KARPATHOS, Greece(AOK)"},
{value:"KTA", label:"Karratha/KARRATHA, Australia(KTA)"},
{value:"KHG", label:"Kashi/KASHI, China(KHG)"},
{value:"KSF", label:"Kassel/KASSEL, Germany(KSF)"},
{value:"KTM", label:"Kathmandu/KATHMANDU, Nepal(KTM)"},
{value:"KTW", label:"Katowice/KATOWICE, Poland(KTW)"},
{value:"LIH", label:"Kauai Island/KAUAI ISLAND, United States(LIH)"},
{value:"KVA", label:"Kavala/KAVALA, Greece(KVA)"},
{value:"ASR", label:"Kayseri/KAYSERI, Turkey(ASR)"},
{value:"KZN", label:"Kazan/KAZAN, Russian Federation(KZN)"},
{value:"EFL", label:"Kefalhnia/KEFALLINIA, Greece(EFL)"},
{value:"YLW", label:"Kelowna/KELOWNA, Canada(YLW)"},
{value:"KEJ", label:"Kemerovo/KEMEROVO, Russian Federation(KEJ)"},
{value:"KEM", label:"Kemi/Tornio/KEMI, Finland(KEM)"},
{value:"KPS", label:"Kempsey/KEMPSEY, Australia(KPS)"},
{value:"KIR", label:"Kerry Country/KERRY COUNTY, Ireland(KIR)"},
{value:"KTN", label:"Ketchikan/KETCHIKAN, United States(KTN)"},
{value:"EYW", label:"Key West/KEY WEST, United States(EYW)"},
{value:"KHV", label:"Khabarovsk/KHABAROVSK, Russian Federation(KHV)"},
{value:"HJR", label:"Khajuraho/HKAJURAHO, India(HJR)"},
{value:"KRT", label:"Khartoum/KHARTOUM, Sudan(KRT)"},
{value:"KBP", label:"Kiev/UKRAINE, Ukraine(KBP)"},
{value:"KGL", label:"Kigali/KIGALI, Rwanda(KGL)"},
{value:"JRO", label:"Kilimanjaro/KILIMANJARO, Tanzania, United Republic(JRO)"},
{value:"ILE", label:"Killeen/KILLEEN, United States(ILE)"},
{value:"AKN", label:"King Salmon/KING SALMON, United States(AKN)"},
{value:"KGC", label:"Kingscote/KINGSCOTE, Australia(KGC)"},
{value:"KIN", label:"Kingston/KINGSTON, Jamaica(KIN)"},
{value:"KKN", label:"Kirkenes/KIRKENES, Norway(KKN)"},
{value:"IRK", label:"Kirksville Municipal/KIRKSVILLE, United States(IRK)"},
{value:"KOI", label:"Kirkwall/KIRKWALL, United Kingdom(KOI)"},
{value:"KIV", label:"Kishinev/KISHIEV, Moldova, Republic Of(KIV)"},
{value:"YKF", label:"Kitchener/KITCHENER/WATERLOO, Canada(YKF)"},
{value:"KTT", label:"Kittila/KITTILA, Finland(KTT)"},
{value:"KLU", label:"Klagenfurt/KLAGENFURT, Austria(KLU)"},
{value:"LMT", label:"Klamath Falls/KLAMATH FALLS, United States(LMT)"},
{value:"NOC", label:"Knock/CONNAUGHT, Ireland(NOC)"},
{value:"TYS", label:"Knoxville/KNOXVILLE, United States(TYS)"},
{value:"UKB", label:"Kobe/KOBE, Japan(UKB)"},
{value:"KCZ", label:"Kochi/KOCHI, Japan(KCZ)"},
{value:"ADQ", label:"Kodiak Airport/KODIAK MUNICIPAL, United States(ADQ)"},
{value:"USM", label:"Koh Samui/KOH SAMUI, Thailand(USM)"},
{value:"KOK", label:"Kokkola/Pietarsaari/KOKKOLA, Finland(KOK)"},
{value:"KKJ", label:"Kokura/KITA KYUSHU, Japan(KKJ)"},
{value:"CCU", label:"Kolkata/KOLKATA, India(CCU)"},
{value:"KMQ", label:"Komatsu/KOMATSU, Japan(KMQ)"},
{value:"KOA", label:"Kona/KONA, United States(KOA)"},
{value:"KUT", label:"Kopitnari/KUTAISI, Georgia(KUT)"},
{value:"KRL", label:"Korla/KORLA, China(KRL)"},
{value:"KGS", label:"Kos/KOS, Greece(KGS)"},
{value:"BKI", label:"Kota Kinabalu/KOTA KINABALU, Malaysia(BKI)"},
{value:"OTZ", label:"Kotzebue/KOTZEBUE, United States(OTZ)"},
{value:"KBV", label:"Krabi/KRABI, Thailand(KBV)"},
{value:"KRK", label:"Krakow/KRAKOW, Poland(KRK)"},
{value:"KRR", label:"Krasnodar/KRASNODAR, Russian Federation(KRR)"},
{value:"KJA", label:"Krasnoyarsk/KRASNOYARSK, Russian Federation(KJA)"},
{value:"MQP", label:"Kruger Mpumalanga Nelspruit/NELSPRUIT, South Africa(MQP)"},
{value:"KUL", label:"Kuala Lumpur/KUALA LUMPUR, Malaysia(KUL)"},
{value:"KNO", label:"Kuala Namu Intl Airport/MEDAN, Indonesia(KNO)"},
{value:"TGG", label:"Kuala Terengganu/KUALA TERENGG, Malaysia(TGG)"},
{value:"KUA", label:"Kuantan/KUANTAN, Malaysia(KUA)"},
{value:"KCH", label:"Kuching/KUCHING, Malaysia(KCH)"},
{value:"TJU", label:"Kulob/KULOB, Tadjikistan(TJU)"},
{value:"KMJ", label:"Kumamoto/KUMAMOTO, Japan(KMJ)"},
{value:"UEO", label:"Kume Jima/KUMEJIMA, Japan(UEO)"},
{value:"KMG", label:"Kunming Wujiaba/KUNMING, China(KMG)"},
{value:"KNX", label:"Kununurra/KUNUNURRA, Australia(KNX)"},
{value:"KUO", label:"Kuopio/KUOPIO, Finland(KUO)"},
{value:"KUH", label:"Kushiro/KUSHIRO, Japan(KUH)"},
{value:"KAO", label:"Kuusamo/KUUSAMO, Finland(KAO)"},
{value:"KWI", label:"Kuwait/KUWAIT, Kuwait(KWI)"},
{value:"KWJ", label:"Kwanju/KWANGJU, Korea, Republic Of(KWJ)"},
{value:"LCG", label:"La Coruna/LA CORUNA, Spain And Canary Islands(LCG)"},
{value:"LSE", label:"La Crosse/LA CROSSE, United States(LSE)"},
{value:"LPB", label:"La Paz El Alto/LA PAZ, Bolivia(LPB)"},
{value:"LAP", label:"La Paz Leon/LA PAZ MEX, Mexico(LAP)"},
{value:"LRH", label:"La Rochelle/LA ROCHELLE, France(LRH)"},
{value:"LRM", label:"La Romana/LA ROMANA, Dominican Republic(LRM)"},
{value:"LSC", label:"La Serena/LA SERENA, Chile(LSC)"},
{value:"LBU", label:"Labuan/LABUAN, Malaysia(LBU)"},
{value:"LFT", label:"Lafayette Regional/LAFAYETTE LA, United States(LFT)"},
{value:"LAF", label:"Lafayette Usa/LAFAYETTE IN, United States(LAF)"},
{value:"LOS", label:"Lagos/LAGOS, Nigeria(LOS)"},
{value:"LHE", label:"Lahore/LAHORE, Pakistan(LHE)"},
{value:"LCH", label:"Lake Charles/LAKE CHARLES, United States(LCH)"},
{value:"LKL", label:"Lakselv/LAKSELV, Norway(LKL)"},
{value:"SUF", label:"Lamezia Terme/LAMEZIA-TERME, Italy(SUF)"},
{value:"LPT", label:"Lampang/LAMPANG, Thailand(LPT)"},
{value:"LNY", label:"Lanal City/LANAI, United States(LNY)"},
{value:"LGK", label:"Langkawi/LANGKAWI, Malaysia(LGK)"},
{value:"LAI", label:"Lannion/LANNION, France(LAI)"},
{value:"LAN", label:"Lansing/LANSING, United States(LAN)"},
{value:"ACE", label:"Lanzarote/Canary Island/LANZAROTE, Spain And Canary Islands(ACE)"},
{value:"LHW", label:"Lanzhou/LANZHOU, China(LHW)"},
{value:"LPP", label:"Lappeenranta/LAPPEENRANTA, Finland(LPP)"},
{value:"LRD", label:"Laredo/LAREDO, United States(LRD)"},
{value:"LCA", label:"Larnaca Intl/Nicosia/LARNACA, Cyprus(LCA)"},
{value:"LPA", label:"Las Palmas/GRAN CANARIA, Spain And Canary Islands(LPA)"},
{value:"LAS", label:"Las Vegas/LAS VEGAS, United States(LAS)"},
{value:"LST", label:"Launceston/LAUNCESTON, Australia(LST)"},
{value:"PIB", label:"Laurel/Pine Belt Regional/LAUREL, United States(PIB)"},
{value:"LAW", label:"Lawton/LAWTON, United States(LAW)"},
{value:"LEA", label:"Learmonth/LEARMONTH, Australia(LEA)"},
{value:"LBA", label:"Leeds Bradford/LEEDS, United Kingdom(LBA)"},
{value:"IXL", label:"Leh/LEH, India(IXL)"},
{value:"LER", label:"Leinster/LEINSTER, Australia(LER)"},
{value:"LEJ", label:"Leipzig/LEIPZIG, Germany(LEJ)"},
{value:"LEN", label:"Leon/LEON, Spain And Canary Islands(LEN)"},
{value:"BJX", label:"Leon-Guanajuato/LEON GUANAJUATO, Mexico(BJX)"},
{value:"LWS", label:"Lewiston/LEWISTON, United States(LWS)"},
{value:"LEX", label:"Lexington Blue Grass Apt/LEXINGTON, United States(LEX)"},
{value:"LXA", label:"Lhasa/LHASA, China(LXA)"},
{value:"LCX", label:"Liancheng/LIANCHENG, China(LCX)"},
{value:"LYG", label:"Lianyungang/LIANYUNGANG, China(LYG)"},
{value:"LIR", label:"Liberia/LIBERIA, Costa Rica(LIR)"},
{value:"LJG", label:"Lijiang/LIJIANG, China(LJG)"},
{value:"LIL", label:"Lille Lesquin Airport/LILLE, France(LIL)"},
{value:"XDB", label:"Lille Rail Service/LILLE RAIL SERVICE, France(XDB)"},
{value:"LLW", label:"Lilongwe/LILONGWE, Malawi(LLW)"},
{value:"LIM", label:"Lima/LIMA, Peru(LIM)"},
{value:"LNJ", label:"Lincang/LINCANG, China(LNJ)"},
{value:"LNK", label:"Lincoln/LINCOLN, United States(LNK)"},
{value:"LLF", label:"Lingling/YONGZHOU, China(LLF)"},
{value:"LYI", label:"Linyi/LINYI, China(LYI)"},
{value:"LNZ", label:"Linz/LINZ, Austria(LNZ)"},
{value:"LZY", label:"Linzhi/LINZHI, China(LZY)"},
{value:"LIS", label:"Lisbon/LISBON, Portugal(LIS)"},
{value:"LIT", label:"Little Rock/LITTLE ROCK, United States(LIT)"},
{value:"LZH", label:"Liuzhou/LIUZHOU, China(LZH)"},
{value:"LPL", label:"Liverpool/LIVERPOOL, United Kingdom(LPL)"},
{value:"LVI", label:"Livingstone/LIVINGSTONE, Zambia(LVI)"},
{value:"LJU", label:"Ljubljana/LJUBLJANA, Slovenia(LJU)"},
{value:"RJL", label:"Logrono/LOGRONO, Spain And Canary Islands(RJL)"},
{value:"LCY", label:"London City Airport/LONDON, United Kingdom(LCY)"},
{value:"LTN", label:"London Luton Airport/LONDON, United Kingdom(LTN)"},
{value:"LGW", label:"London/Gatwick/LONDON, United Kingdom(LGW)"},
{value:"LHR", label:"London/Heathrow/LONDON, United Kingdom(LHR)"},
{value:"STN", label:"London/Stansted/LONDON, United Kingdom(STN)"},
{value:"LDY", label:"Londonderry/LONDONDERRY, United Kingdom(LDY)"},
{value:"LGB", label:"Long Beach/LONG BEACH, United States(LGB)"},
{value:"LDB", label:"Longrina/LONGRINA, Brazil(LDB)"},
{value:"GGG", label:"Longview/LONGVIEW, United States(GGG)"},
{value:"LYR", label:"Longyearbyen/LONGYEARBYEN, Norway(LYR)"},
{value:"LDH", label:"Lord Howe Island/LORD HOWE ISLAND, Australia(LDH)"},
{value:"LTO", label:"Loreto/LORETO, Mexico(LTO)"},
{value:"LAX", label:"Los Angeles/LOS ANGELES, United States(LAX)"},
{value:"MTR", label:"Los Garzones Monteria/MONTERIA, Colombia(MTR)"},
{value:"SDF", label:"Louisville/LOUISVILLE, United States(SDF)"},
{value:"LDE", label:"Lourdes Tarbes/LOURDES/TARBE, France(LDE)"},
{value:"LAD", label:"Luanda/LUANDA, Angola(LAD)"},
{value:"LPQ", label:"Luang Prabang/LUANG PRABANG, Lao People's Democratic Republic(LPQ)"},
{value:"LBB", label:"Lubbock/LUBBOCK, United States(LBB)"},
{value:"LKO", label:"Lucknow/LUCKNOW, India(LKO)"},
{value:"LUG", label:"Lugano/LUGANO, Switzerland(LUG)"},
{value:"SBP", label:"Luis Obispo/SAN LUIS, United States(SBP)"},
{value:"LYA", label:"Luoyang/LUOYANG, China(LYA)"},
{value:"LUN", label:"Lusaka/LUSAKA, Zambia(LUN)"},
{value:"LUX", label:"Luxembourg/LUXEMBOURG, Luxembourg(LUX)"},
{value:"LUM", label:"Luxi/LUXI, China(LUM)"},
{value:"LXR", label:"Luxor/LUXOR, Egypt(LXR)"},
{value:"LZO", label:"Luzhou/LUZHOU, China(LZO)"},
{value:"LYH", label:"Lynchburg/LYNCHBURG, United States(LYH)"},
{value:"XYD", label:"Lyon Part-Dieu Rail Station/LYON PART-DIEU RAIL STATION, France(XYD)"},
{value:"LYS", label:"Lyon Satolas Apt/LYON, France(LYS)"},
{value:"MST", label:"Maastricht Aachen De Apt/MAASTRICHT, Netherlands(MST)"},
{value:"MCP", label:"Macapa Intl Airport/MACAPA, Brazil(MCP)"},
{value:"MFM", label:"Macau/MACAU, Macau, SAR(MFM)"},
{value:"MCZ", label:"Maceio/MACEIO, Brazil(MCZ)"},
{value:"MKY", label:"Mackay/MACKAY, Australia(MKY)"},
{value:"MED", label:"Madinah/MEDINA, Saudi Arabia(MED)"},
{value:"MSN", label:"Madison/MADISON, United States(MSN)"},
{value:"MAD", label:"Madrid/Barajas/MADRID, Spain And Canary Islands(MAD)"},
{value:"IXM", label:"Madurai/MADURAI, India(IXM)"},
{value:"GDX", label:"Magodan/MAGODAN, Russian Federation(GDX)"},
{value:"SEZ", label:"Mahe Seychelles Intl/MAHE ISLAND, Seychelles(SEZ)"},
{value:"SSG", label:"Malabo/MALABO, Equatorial Guinea(SSG)"},
{value:"AGP", label:"Malaga/MALAGA, Spain And Canary Islands(AGP)"},
{value:"MLE", label:"Male Intl/Maldives/MALE, Maldives(MLE)"},
{value:"MLA", label:"Malta/MALTA, Malta(MLA)"},
{value:"MMH", label:"Mammoth Lakes Airport/MAMMOTH LAKES, United States(MMH)"},
{value:"MGA", label:"Managua/MANAGUA, Nicaragua(MGA)"},
{value:"MAO", label:"Manaus/MANAUS, Brazil(MAO)"},
{value:"MHT", label:"Manchester Municipal Usa/MANCHESTER, United States(MHT)"},
{value:"MAN", label:"Manchester Uk/MANCHESTER, United Kingdom(MAN)"},
{value:"MDL", label:"Mandalay/Annisaton/MANDALAY, Myanmar(MDL)"},
{value:"IXE", label:"Mangalore/MANGALORE, India(IXE)"},
{value:"MHK", label:"Manhattan/MANHATTAN, United States(MHK)"},
{value:"MNL", label:"Manila/MANILA, Philippines(MNL)"},
{value:"ZLO", label:"Manzanillo/MANZANILLO, Mexico(ZLO)"},
{value:"NZH", label:"Manzhouli/MANZHOULI, China(NZH)"},
{value:"MTS", label:"Manzini/MANZINI, Swaziland(MTS)"},
{value:"MPM", label:"Maputo Intl/MAPUTO, Mozambique(MPM)"},
{value:"MAB", label:"Maraba Airport/MARABA, Brazil(MAB)"},
{value:"MAR", label:"Maracaibo/MARACAIBO, Venezuela(MAR)"},
{value:"MTH", label:"Marathon/MARATHON, United States(MTH)"},
{value:"MBX", label:"Maribor Int'L Airport/MARIBOR, Slovenia(MBX)"},
{value:"MHQ", label:"Mariehamn/MARIEHAMN, Finland(MHQ)"},
{value:"MWA", label:"Marion/MARION, United States(MWA)"},
{value:"MQT", label:"Marquette Country Airport/MARQUETTE, United States(MQT)"},
{value:"RAK", label:"Marrakech/MARRAKECH, Morocco(RAK)"},
{value:"RMF", label:"Marsa Alam/MARSA ALAM, Egypt(RMF)"},
{value:"MRS", label:"Marseille/MARSEILLE, France(MRS)"},
{value:"MHH", label:"Marsh Harbour/MARSH HARBOUR, Bahamas(MHH)"},
{value:"MBH", label:"Maryborough/MARYBOROUGH, Australia(MBH)"},
{value:"MHD", label:"Mashad/MASHAD, Iran (Islamic Republic Of)(MHD)"},
{value:"MMJ", label:"Matsumoto/MATSUMOTO, Japan(MMJ)"},
{value:"MYJ", label:"Matsuyama/MATSUYAMA, Japan(MYJ)"},
{value:"HRI", label:"Mattala Rajapaksa Intl Apt/MATTALA RAJAPAKSA, Sri Lanka(HRI)"},
{value:"MRU", label:"Mauritius/MAURITIUS, Mauritus(MRU)"},
{value:"MAZ", label:"Mayaguez/MAYAGUEZ, Puerto Rico(MAZ)"},
{value:"MZT", label:"Mazatlan/MAZATLAN, Mexico(MZT)"},
{value:"MES", label:"Medan/Polonia/MEDAN, Indonesia(MES)"},
{value:"MDE", label:"Medellin/MEDELLIN, Colombia(MDE)"},
{value:"MFR", label:"Medford/MEDFORD, United States(MFR)"},
{value:"MEL", label:"Melbourne/MELBOURNE, Australia(MEL)"},
{value:"MLB", label:"Melbourne Beach/MELBOURNE BEACH, United States(MLB)"},
{value:"MLN", label:"Melilla/MELILLA, Spain And Canary Islands(MLN)"},
{value:"MMB", label:"Memanbetsu/MEMANBETSU, Japan(MMB)"},
{value:"FMM", label:"Memmingen/MEMMINGEN, Germany(FMM)"},
{value:"MEM", label:"Memphis/MEMPHIS, United States(MEM)"},
{value:"MDZ", label:"Mendoza/MENDOZA, Argentina(MDZ)"},
{value:"MAH", label:"Menorca/MAHON, Spain And Canary Islands(MAH)"},
{value:"MID", label:"Merida/MERIDA, Mexico(MID)"},
{value:"MEI", label:"Meridian/MERIDIAN, United States(MEI)"},
{value:"ETZ", label:"Metz Nancy/METZ/NANCY, France(ETZ)"},
{value:"MXL", label:"Mexicall/MEXICALI, Mexico(MXL)"},
{value:"MEX", label:"Mexico/MEXICO CITY, Mexico(MEX)"},
{value:"MIA", label:"Miami/MIAMI, United States(MIA)"},
{value:"MDT", label:"Middletown/HARRISBURG, United States(MDT)"},
{value:"ZYR", label:"Midi Railway Station/MIDI RAILWAY STATION, Belgium(ZYR)"},
{value:"MAF", label:"Midland/MIDLAND, United States(MAF)"},
{value:"MDW", label:"Midway-Chicago/CHICAGO, United States(MDW)"},
{value:"CND", label:"Mihail Kogalniceanu/CONSTANTA, Romania(CND)"},
{value:"JMK", label:"Mikonos/MIKONOS, Greece(JMK)"},
{value:"LIN", label:"Milan Linate/MILAN, Italy(LIN)"},
{value:"BGY", label:"Milan Orio Serio/MILAN, Italy(BGY)"},
{value:"MXP", label:"Milan/Malpensa/MILAN, Italy(MXP)"},
{value:"MQL", label:"Mildura/MILDURA, Australia(MQL)"},
{value:"MTT", label:"Minatitlan/MINATITLAN, Mexico(MTT)"},
{value:"MRV", label:"Mineralnye Vody/MINERALNYE, Russian Federation(MRV)"},
{value:"EZE", label:"Ministro Pistarini/BUENOS AIRES, Argentina(EZE)"},
{value:"MSP", label:"Minniapolis/MINNEAPOL, United States(MSP)"},
{value:"MSQ", label:"Minsk/MINSK, Belarus(MSQ)"},
{value:"MTY", label:"Minterrey/MONTERREY, Mexico(MTY)"},
{value:"MYY", label:"Miri/MIRI, Malaysia(MYY)"},
{value:"MJZ", label:"Mirny/MIRNY, Russian Federation(MJZ)"},
{value:"MSJ", label:"Misawa/MISAWA, Japan(MSJ)"},
{value:"MFE", label:"Mission/MC ALLEN, United States(MFE)"},
{value:"MSO", label:"Missoula/MISSOULA, United States(MSO)"},
{value:"MMY", label:"Miyako Jima/MIYAKO, Japan(MMY)"},
{value:"KMI", label:"Miyazaki/MIYAZAKI, Japan(KMI)"},
{value:"MLI", label:"Moline/MOLINE, United States(MLI)"},
{value:"MBA", label:"Mombasa/MOMBASA, Kenya(MBA)"},
{value:"MIR", label:"Monastir/MONASTIR, Tunisia(MIR)"},
{value:"MLU", label:"Monroe/MONROE, United States(MLU)"},
{value:"ROB", label:"Monrovia Roberts International/MONROVIA, Liberia(ROB)"},
{value:"MRY", label:"Monterey/MONTEREY, United States(MRY)"},
{value:"MVD", label:"Montevideo/MONTEVIDEO, Uruguay(MVD)"},
{value:"MGM", label:"Montgomery/MONTGOMERY, United States(MGM)"},
{value:"MPL", label:"Montpellier/MONTPELLIER, France(MPL)"},
{value:"YMX", label:"Montreal Mirabel/MONTREAL, Canada(YMX)"},
{value:"YUL", label:"Montreal/Dorval/MONTREAL, Canada(YUL)"},
{value:"MTJ", label:"Montrose/MONTROSE, United States(MTJ)"},
{value:"MOV", label:"Moranbah/MORANBAH, Australia(MOV)"},
{value:"MRZ", label:"Moree/MOREE, Australia(MRZ)"},
{value:"MLM", label:"Morelia/MORELIA, Mexico(MLM)"},
{value:"HNA", label:"Morikora/MORIOKA, Japan(HNA)"},
{value:"DME", label:"Moscow Domodedovo Airport/MOSCOW, Russian Federation(DME)"},
{value:"SVO", label:"Moscow/Sheremetyevo/MOSCOW, Russian Federation(SVO)"},
{value:"VKO", label:"Moscow/Vnukovo/MOSCOW, Russian Federation(VKO)"},
{value:"CWA", label:"Mosinee/WAUSAU, United States(CWA)"},
{value:"MBJ", label:"Motego Bay/MONTEGO BAY, Jamaica(MBJ)"},
{value:"ISA", label:"Mount Isa/MOUNT ISA, Australia(ISA)"},
{value:"WME", label:"Mount Keith/MOUNT KEITH, Australia(WME)"},
{value:"MPN", label:"Mount Pleasant/MOUNT PLEASANT, Falkland Islands(MPN)"},
{value:"MWX", label:"Muan/MUAN, Korea, Republic Of(MWX)"},
{value:"MDG", label:"Mudanjiang/MUDANJIANG, China(MDG)"},
{value:"MUX", label:"Multan/MULTAN, Pakistan(MUX)"},
{value:"BOM", label:"Mumbai/MUMBAI, India(BOM)"},
{value:"MUC", label:"Munich/MUNICH, Germany(MUC)"},
{value:"MIG", label:"Munich Neubiberg Ab/MIAN YANG, China(MIG)"},
{value:"MJV", label:"Murica/MURCIA, Spain And Canary Islands(MJV)"},
{value:"MMK", label:"Murmansk/MURMANSK, Russian Federation(MMK)"},
{value:"MCT", label:"Muscat/MUSCAT, Oman(MCT)"},
{value:"MYR", label:"Myrtle Beach Afb/MYRTLE BEACH, United States(MYR)"},
{value:"MJT", label:"Mytilene/MYTILENE, Greece(MJT)"},
{value:"NDR", label:"Nador/NADOR, Morocco(NDR)"},
{value:"NYM", label:"Nadym/NADYM, Russian Federation(NYM)"},
{value:"NGS", label:"Nagasaki/NAGASAKI, Japan(NGS)"},
{value:"NGO", label:"Nagoya Chubu Centrair/NAGOYA, Japan(NGO)"},
{value:"NKM", label:"Nagoya Komaki Airport/NAGOYA, Japan(NKM)"},
{value:"NAG", label:"Nagpur/NAGPUR, India(NAG)"},
{value:"NBO", label:"Nairobi/NAIROBI, Kenya(NBO)"},
{value:"NJF", label:"Najaf/NAJAF, Iraq(NJF)"},
{value:"KHN", label:"Nanchang/NANCHANG, China(KHN)"},
{value:"NAO", label:"Nanchong/NANCHONG, China(NAO)"},
{value:"NKG", label:"Nanjing/NANJING, China(NKG)"},
{value:"SHM", label:"Nanki-Shirahama/SHIRAHAMA, Japan(SHM)"},
{value:"NNG", label:"Nanning Wuxu/NANNING, China(NNG)"},
{value:"NTE", label:"Nantes Atlantique Airport/NANTES, France(NTE)"},
{value:"NTG", label:"Nantong/NANTONG, China(NTG)"},
{value:"ACK", label:"Nantucket/NANTUCKET, United States(ACK)"},
{value:"APF", label:"Naples/NAPLES, United States(APF)"},
{value:"NAP", label:"Naples/Capodichino Mil/NAPLES, Italy(NAP)"},
{value:"NAA", label:"Narrabri/NARRABRI, Australia(NAA)"},
{value:"BNA", label:"Nashville/NASHVILLE, United States(BNA)"},
{value:"NAS", label:"Nassau/NASSAU, Bahamas(NAS)"},
{value:"NAT", label:"Natal/NATAL, Brazil(NAT)"},
{value:"QJZ", label:"Nates Rail Station/NANTES RAILWAY STATION, France(QJZ)"},
{value:"NVT", label:"Navegantes/NAVEGANTES, Brazil(NVT)"},
{value:"NYT", label:"Nay Pyi Daw Airport/NAY PYI TAW, Myanmar(NYT)"},
{value:"NLA", label:"Ndola/NDOLA, Zambia(NLA)"},
{value:"NSN", label:"Nelson/NELSON, New Zealand(NSN)"},
{value:"NQN", label:"Neuquen/NEUQUEN, Argentina(NQN)"},
{value:"EWN", label:"New Bern/NEW BERN, United States(EWN)"},
{value:"HVN", label:"New Haven/NEW HAVEN, United States(HVN)"},
{value:"MSY", label:"New Orleans/NEW ORLEANS, United States(MSY)"},
{value:"JFK", label:"New York/J.F. Kennedy/NEW YORK, United States(JFK)"},
{value:"LGA", label:"New York/La Guardia/NEW YORK, United States(LGA)"},
{value:"EWR", label:"New York/Newark Intl/NEW YORK, United States(EWR)"},
{value:"SWF", label:"Newburge/NEWBURGH, United States(SWF)"},
{value:"NEV", label:"Newcastle Airport/Nevis Island/NEVIS, Saint Kitts And Nevis(NEV)"},
{value:"NCL", label:"Newcastle Uk/NEWCASTLE, United Kingdom(NCL)"},
{value:"ZNE", label:"Newman/NEWMAN, Australia(ZNE)"},
{value:"PHF", label:"Newport News/NEWPOER NEW HAMP, United States(PHF)"},
{value:"NQY", label:"Newquay/NEWQUAY, United Kingdom(NQY)"},
{value:"NCE", label:"Nice/NICE, France(NCE)"},
{value:"KIJ", label:"Niigata/NIIGATA, Japan(KIJ)"},
{value:"FNI", label:"Nimes/NIMES, France(FNI)"},
{value:"NGB", label:"Ningbo/NINGBO, China(NGB)"},
{value:"NBC", label:"Nizhnekamsk/NIZHNEKAMSK, Russian Federation(NBC)"},
{value:"NJC", label:"Nizhnevartovsk/NIZHNEVARTOVSK, Russian Federation(NJC)"},
{value:"GOJ", label:"Nizhniy Novogorod/NIZHNIY NOVGOROD, Russian Federation(GOJ)"},
{value:"OME", label:"Nome/NOME, United States(OME)"},
{value:"ORF", label:"Norfolk/NORFOLK VA, United States(ORF)"},
{value:"ORF", label:"Norfolk/QUERETARO, United States(ORF)"},
{value:"NSK", label:"Norilsk/NORILSK, Russian Federation(NSK)"},
{value:"OTH", label:"North Bend/NORTH BEND, United States(OTH)"},
{value:"ELH", label:"North Eleuthera/NORTH ELEUTHERA, United States(ELH)"},
{value:"NRL", label:"North Ronaldsay/N RONALDSAY, United Kingdom(NRL)"},
{value:"NOU", label:"Noumea/NOUMEA, New Caledonia(NOU)"},
{value:"NOZ", label:"Novokuznetsk/NOVOKUZNETSK, Russian Federation(NOZ)"},
{value:"OVB", label:"Novosibirsk/NOVOSIBIRSK, Russian Federation(OVB)"},
{value:"NUX", label:"Novyj Urengoj/NOVYJ URENGOJ, Russian Federation(NUX)"},
{value:"NLD", label:"Nuevo Lavedo/NUEVO LAREDO, Mexico(NLD)"},
{value:"NUE", label:"Nurnberg/NUREMBERG, Germany(NUE)"},
{value:"OAK", label:"Oakland/OAKLAND, United States(OAK)"},
{value:"OAX", label:"Oaxaca/OAXACA, Mexico(OAX)"},
{value:"OBF", label:"Oberpfaffenhofen/OBERPFAFFENHO, Germany(OBF)"},
{value:"OBO", label:"Obihiro/OBIHIRO, Japan(OBO)"},
{value:"ODE", label:"Odense Airport/ODENSE, Denmark(ODE)"},
{value:"ODS", label:"Odessa/ODESSA, Ukraine(ODS)"},
{value:"OIT", label:"Oita/OITA, Japan(OIT)"},
{value:"OKC", label:"Okalahoma/OKLAHOMA CITY, United States(OKC)"},
{value:"OKJ", label:"Okayama/OKAYAMA, Japan(OKJ)"},
{value:"OKI", label:"Oki Island/OKI ISLAND, Japan(OKI)"},
{value:"OKA", label:"Okinawa Naha/OKINAWA, Japan(OKA)"},
{value:"OLB", label:"Olbia/OLBIA, Italy(OLB)"},
{value:"OLH", label:"Old Harbour/OLD HARBOR, United States(OLH)"},
{value:"OLP", label:"Olympic Dam/OLYMPIC DAM, Australia(OLP)"},
{value:"OMA", label:"Omaha/OMAHA, United States(OMA)"},
{value:"OMS", label:"Omsk/OMSK, Russian Federation(OMS)"},
{value:"ONT", label:"Ontario/ONTARIO CA, United States(ONT)"},
{value:"REN", label:"Orenburg Tsentralny/ORENBURG, Russian Federation(REN)"},
{value:"ORL", label:"Orlando Herndon Airport/ORLANDO, United States(ORL)"},
{value:"MCO", label:"Orlando/International/ORLANDO, United States(MCO)"},
{value:"KIX", label:"Osaka/Kansai/OSAKA, Japan(KIX)"},
{value:"OSS", label:"Osh/OSH, Kazakhstan(OSS)"},
{value:"OSL", label:"Oslo Airport/OSLO, Norway(OSL)"},
{value:"ZOS", label:"Osorno/OSORNO, Chile(ZOS)"},
{value:"YOW", label:"Ottawa/OTTAWA, Canada(YOW)"},
{value:"OUL", label:"Oulu/OULU, Finland(OUL)"},
{value:"OUK", label:"Outer Skerries/OUTER SKEERIES, United Kingdom(OUK)"},
{value:"OVL", label:"Oviedo/OVIEDO, United States(OVL)"},
{value:"OWB", label:"Owensboro/OWENSBORO, United States(OWB)"},
{value:"PAD", label:"Paderborn/PADERBORN, Germany(PAD)"},
{value:"PAH", label:"Paducah/PADUCAH, United States(PAH)"},
{value:"PMO", label:"Palermo/PALERMO, Italy(PMO)"},
{value:"PSP", label:"Palm Springs/PALM SPRINGS, United States(PSP)"},
{value:"PMW", label:"Palmas/PALMAS, Brazil(PMW)"},
{value:"PMR", label:"Palmerston North/PALMERSTON, New Zealand(PMR)"},
{value:"PNA", label:"Pamplona/PAMPLONA, Spain And Canary Islands(PNA)"},
{value:"PZI", label:"Pan Zhi Hua/PAN ZHI HUA, China(PZI)"},
{value:"PTY", label:"Panama City/PANAMA CITY, Panama(PTY)"},
{value:"PSV", label:"Papa Stour/PAPA STOUR, Brazil(PSV)"},
{value:"PPW", label:"Papa Westray/PAPA WESTRAY, United Kingdom(PPW)"},
{value:"PPT", label:"Papeete/Tahiti Faaa/PAPEETE, French Polynesia(PPT)"},
{value:"PFO", label:"Paphos/PAPHOS, Cyprus(PFO)"},
{value:"PBO", label:"Paraburdoo/PARABURDOO, Australia(PBO)"},
{value:"CDG", label:"Paris/Charles De Gaulle/PARIS, France(CDG)"},
{value:"ORY", label:"Paris/Orly/PARIS, France(ORY)"},
{value:"PSC", label:"Pasco/PASCO, United States(PSC)"},
{value:"PAT", label:"Patna/PATNA, India(PAT)"},
{value:"GPA", label:"Patras/PATRAS, Greece(GPA)"},
{value:"PWQ", label:"Pavlodar/PAVLODAR, Kazakhstan(PWQ)"},
{value:"PEN", label:"Penang/PENANG, Malaysia(PEN)"},
{value:"PDT", label:"Pendleton/PENDLETON, United States(PDT)"},
{value:"PNS", label:"Pensacola Municipal Apt/PENSACOLA, United States(PNS)"},
{value:"IBE", label:"Perales Airport/IBAGUE, Colombia(IBE)"},
{value:"PEI", label:"Pereira/PEREIRA, Colombia(PEI)"},
{value:"PEE", label:"Perm/PERM, Russian Federation(PEE)"},
{value:"PIA", label:"Peroria/PERORIA, United States(PIA)"},
{value:"PGF", label:"Perpignan/PERPIGNAN, France(PGF)"},
{value:"PER", label:"Perth/PERTH, Australia(PER)"},
{value:"PEW", label:"Peshawar/PESHAWAR, Pakistan(PEW)"},
{value:"PSG", label:"Petersburg/PETERSBURG, United States(PSG)"},
{value:"PKC", label:"Petropavlovsk/PETROPAVLOVSK-KAMCHATSKY, Russian Federation(PKC)"},
{value:"PES", label:"Petrozavodsk/PETROPALOVSK, Russian Federation(PES)"},
{value:"PHL", label:"Philadelphia/PHILADELPHIA, United States(PHL)"},
{value:"PNH", label:"Phnom-Penh/PHNOM PENH, Cambodia(PNH)"},
{value:"PHX", label:"Phoenix/PHOENIX, United States(PHX)"},
{value:"HKT", label:"Phuket/PHUKET, Thailand(HKT)"},
{value:"PSA", label:"Pisa/PISA, Italy(PSA)"},
{value:"PIT", label:"Pittsburgh/PITTSBURGH, United States(PIT)"},
{value:"PIU", label:"Piura/PIURA, Peru(PIU)"},
{value:"PMI", label:"Plama Mallorca/PALMA MALLORC, Spain And Canary Islands(PMI)"},
{value:"PDV", label:"Plovdiv/PLOVDIV, Bulgaria(PDV)"},
{value:"PLH", label:"Plymouth/PLYMOUTH, United Kingdom(PLH)"},
{value:"PIH", label:"Pocatello/POCATELLO, United States(PIH)"},
{value:"PTP", label:"Pointe A Pitre/POINTE A PITRE, Guadeloupe(PTP)"},
{value:"XOP", label:"Poitiers/POITIERS, France(XOP)"},
{value:"PIS", label:"Poitiers Biard Airport/POITIERS, France(PIS)"},
{value:"PDL", label:"Ponta Delgada/PARNDANA, Portugal(PDL)"},
{value:"PBD", label:"Porbandar/PORBANDAR, India(PBD)"},
{value:"POR", label:"Pori/PORI, Finland(POR)"},
{value:"CLM", label:"Port Angeles/PORT ANGELES, United States(CLM)"},
{value:"PAP", label:"Port Au Prince/PORT AU PRINC, Haiti(PAP)"},
{value:"IXZ", label:"Port Blair/PORT BLAIR, India(IXZ)"},
{value:"PLZ", label:"Port Elizabeth/PT ELIZABETH, South Africa(PLZ)"},
{value:"PHE", label:"Port Headland/PORT HEADLAND, Australia(PHE)"},
{value:"PLO", label:"Port Lincoln/PORT LINCOLN, Australia(PLO)"},
{value:"PQQ", label:"Port Macquarie/PORT MACQUARIE, Australia(PQQ)"},
{value:"POM", label:"Port Moresby/PORT MORESBY, Papua New Guinea(POM)"},
{value:"VLI", label:"Port Vila Vanuatu/PORT VILA, Vanuatu(VLI)"},
{value:"PWM", label:"Portland Intl Me Usa/PORTLAND ME, United States(PWM)"},
{value:"PDX", label:"Portland Intl Or Usa/PORTLAND OR, United States(PDX)"},
{value:"OPO", label:"Porto/PORTO, Portugal(OPO)"},
{value:"POA", label:"Porto Alegre/PORTO ALEGRE, Brazil(POA)"},
{value:"BPS", label:"Porto Seguro Airport/PTO SEGURO, Brazil(BPS)"},
{value:"PVH", label:"Porto Velho/PORTO VELHO, Brazil(PVH)"},
{value:"POZ", label:"Poznan/POZNAN, Poland(POZ)"},
{value:"PRG", label:"Prague/PRAGUE, Czech Republic(PRG)"},
{value:"PRC", label:"Prescott/PRESCOTT, United States(PRC)"},
{value:"PIK", label:"Prestwick/GLASGOW, United Kingdom(PIK)"},
{value:"PVK", label:"Preveza/Lefkas/PREVEZA/LEFKA, Greece(PVK)"},
{value:"PPP", label:"Proserpine/PROSERPINE, Australia(PPP)"},
{value:"PVD", label:"Providence/PROVIDENCE, United States(PVD)"},
{value:"PLS", label:"Providenciales/PROVIDENCIALE, Turks And Caicos Islands(PLS)"},
{value:"SCC", label:"Prudhoe Bay/Deadhorse/DEADHORSE, United States(SCC)"},
{value:"PCL", label:"Pucallpa/PUCALLPA, Peru(PCL)"},
{value:"ZPC", label:"Pucon/PUCON, Chile(ZPC)"},
{value:"PBC", label:"Puebla/PUEBLA, Mexico(PBC)"},
{value:"PEM", label:"Puerto Maldon/PUERTO MALDON, Peru(PEM)"},
{value:"PMC", label:"Puerto Monti/PUERTO MONTT, Chile(PMC)"},
{value:"POP", label:"Puerto Plata/PUERTO PLATA, Dominican Republic(POP)"},
{value:"PVR", label:"Puerto Vallarta/PURETO VALLAR, Mexico(PVR)"},
{value:"PUY", label:"Pula/PULA, Croatia(PUY)"},
{value:"PUW", label:"Pullman/PULLMAN, United States(PUW)"},
{value:"PNQ", label:"Pune/PUNE, India(PNQ)"},
{value:"PUQ", label:"Punta Arenas/PUNTA ARENAS, Chile(PUQ)"},
{value:"PUJ", label:"Punta Cana/PUNTA CANA, Dominican Republic(PUJ)"},
{value:"PXM", label:"Puoto Escond/PUERTO ESCOND, Mexico(PXM)"},
{value:"FNJ", label:"Pyongyang/PYONGYANG, Korea, Democratic People's Republic(FNJ)"},
{value:"TAO", label:"Qingdao/QINGDAO, China(TAO)"},
{value:"XIC", label:"Qingshan/XICHANG, China(XIC)"},
{value:"SHP", label:"Qinhuangdao/QINHUANGDAO, China(SHP)"},
{value:"NDG", label:"Qiqihaer/QIQIHAR, China(NDG)"},
{value:"YQB", label:"Quebec Intl Airport/QUEBEC, Canada(YQB)"},
{value:"ZQN", label:"Queenstown/QUEENSTOWN, New Zealand(ZQN)"},
{value:"QRO", label:"Queretaro/QUERETARO, Mexico(QRO)"},
{value:"UIN", label:"Quincy/QUINCY, United States(UIN)"},
{value:"UIO", label:"Quito/QUITO, Ecuador(UIO)"},
{value:"RBA", label:"Rabat/RABAT, United Kingdom(RBA)"},
{value:"RPR", label:"Raipur/RAIPUR, India(RPR)"},
{value:"RJA", label:"Rajahmundry/RAJAHMUNDRY, India(RJA)"},
{value:"RAJ", label:"Rajkot/RAJKOT, India(RAJ)"},
{value:"RDU", label:"Raleigh/Durham/RALEIGH DURHAM, United States(RDU)"},
{value:"IXR", label:"Ranchi/RANCHI, India(IXR)"},
{value:"RGN", label:"Rangoon/YANGON, Myanmar(RGN)"},
{value:"RAP", label:"Rapid City Municipal Apt/RAPID CITY, United States(RAP)"},
{value:"RKT", label:"Ras Al Khaimah/RAS AL KHAIMA, United Arab Emirates(RKT)"},
{value:"UTP", label:"Rayong/Utapao/UTAPAO, Thailand(UTP)"},
{value:"REC", label:"Recife/RECIFE, Brazil(REC)"},
{value:"RGK", label:"Red Wing/RED WING, United States(RGK)"},
{value:"RDD", label:"Redding/REDDING, United States(RDD)"},
{value:"RDM", label:"Redmond/REDMOND, United States(RDM)"},
{value:"RNS", label:"Rennes/RENNES, France(RNS)"},
{value:"RNO", label:"Reno/RENO, United States(RNO)"},
{value:"REU", label:"Reus/REUS, Spain And Canary Islands(REU)"},
{value:"KEF", label:"Reykjavik Keflavik Airport/REYKJAVIK, Iceland(KEF)"},
{value:"REX", label:"Reynosa/REYNOSA, Mexico(REX)"},
{value:"RHO", label:"Rhodos/RHODES, Greece(RHO)"},
{value:"RAO", label:"Ribeirao Preto/RIBEIRAO PRETO, Brazil(RAO)"},
{value:"RCB", label:"Richards Bay/RICHARDS BAY, South Africa(RCB)"},
{value:"RIC", label:"Richmond/RICHMOND, United States(RIC)"},
{value:"RIX", label:"Riga/RIGA, Latvia(RIX)"},
{value:"RJK", label:"Rijeka/RIJEKA, Croatia(RJK)"},
{value:"RKZ", label:"Rikaze/RIKAZE, China(RKZ)"},
{value:"RMI", label:"Rimini/RIMINI, Italy(RMI)"},
{value:"RBR", label:"Rio Branco/RIO BRANCO, Brazil(RBR)"},
{value:"GIG", label:"Rio De Janeiro Intl/RIO DE JANEIRO, Brazil(GIG)"},
{value:"SDU", label:"Rio De Janeiro Santos Dumont/RIO DE JANEIRO, Brazil(SDU)"},
{value:"RGL", label:"Rio Gallegos/RIO GALLEGOS, Argentina(RGL)"},
{value:"RUH", label:"Riyadh/King Khalid/RIYADH, Saudi Arabia(RUH)"},
{value:"OHA", label:"Rnzaf Base Ohakea/BULLS NEW ZEALAND, New Zealand(OHA)"},
{value:"ROA", label:"Roanoke/ROANOKE, United States(ROA)"},
{value:"RTB", label:"Roatan/ROATAN, Honduras(RTB)"},
{value:"GRK", label:"Robert Grat Aaf/FT. HOOD REGIONAL, United States(GRK)"},
{value:"ROC", label:"Rochester Ny/ROCHESTER NY, United States(ROC)"},
{value:"RST", label:"Rochester-Mn/ROCHESTER MN, United States(RST)"},
{value:"ZRK", label:"Rockford Van Galder Stn/ROCKFORD VAN GALDER BUS STN, United States(ZRK)"},
{value:"ROK", label:"Rockhampton/ROCKHAMPTON, Australia(ROK)"},
{value:"RDZ", label:"Rodez/RODEZ, France(RDZ)"},
{value:"RMA", label:"Roma/ROMA, Australia(RMA)"},
{value:"FCO", label:"Rome/Fiumicino/ROME, Italy(FCO)"},
{value:"ROS", label:"Rosario/ROSARIO, Argentina(ROS)"},
{value:"RLG", label:"Rostock-Laage/ROSTOCK-LAAGE, Germany(RLG)"},
{value:"ROV", label:"Rostov/ROSTOV, Russian Federation(ROV)"},
{value:"ROW", label:"Roswell/ROSWELL, United States(ROW)"},
{value:"ROT", label:"Rotorua/ROTORUA, New Zealand(ROT)"},
{value:"RTM", label:"Rotterdam/ROTTERDAM, Netherlands(RTM)"},
{value:"RVN", label:"Rovaniemi/ROVANIEMI, Finland(RVN)"},
{value:"SCN", label:"Saarbrucken Ensheim Airport/SAARBRUCKEN, Germany(SCN)"},
{value:"SAW", label:"Sabiha Gokcen/Istanbu/ISTANBUL, Turkey(SAW)"},
{value:"SMF", label:"Sacramento Metropolitan/SACRAMENTO/EXECUTIVE, United States(SMF)"},
{value:"MBS", label:"Saginaw/BAY CITY, United States(MBS)"},
{value:"SPN", label:"Saipan/SAIPAN, Northern Mariana Islands(SPN)"},
{value:"SID", label:"Sal/SAL, Cape Verde(SID)"},
{value:"SLL", label:"Salalah/SALALAH, Oman(SLL)"},
{value:"SBY", label:"Salisbury/SALISBURY, United States(SBY)"},
{value:"SLC", label:"Salt Lake/SALT LAKE, United States(SLC)"},
{value:"SLA", label:"Salta/SALTA, Argentina(SLA)"},
{value:"SLW", label:"Saltillo/SALTILLO, Mexico(SLW)"},
{value:"SSA", label:"Salvador/SALVADOR, Brazil(SSA)"},
{value:"SZG", label:"Salzburg/SALZBURG, Austria(SZG)"},
{value:"KUF", label:"Samara/SAMARA, Russian Federation(KUF)"},
{value:"SMI", label:"Samos/SAMOS, Greece(SMI)"},
{value:"SJT", label:"San Angelo/SAN ANGELO, United States(SJT)"},
{value:"SAT", label:"San Antanio/SAN ANTONIO, United States(SAT)"},
{value:"BRC", label:"San Carlos De Bariloch/SAN CARLOS, Argentina(BRC)"},
{value:"SAN", label:"San Diego/SAN DIEGO, United States(SAN)"},
{value:"SFO", label:"San Francisco/SAN FRANCISCO, United States(SFO)"},
{value:"SJC", label:"San Jose/SAN JOSE, United States(SJC)"},
{value:"SJD", label:"San Jose Cabo/SAN JOSE CABO, Mexico(SJD)"},
{value:"SJO", label:"San Jose Santamaria/SAN JOSE, Costa Rica(SJO)"},
{value:"SJU", label:"San Juan/SAN JUAN, Puerto Rico(SJU)"},
{value:"SLP", label:"San Luis Potosi/SAN LUIS POTO, Mexico(SLP)"},
{value:"SAP", label:"San Pedro Sula/SAN PEDRO SUL, Honduras(SAP)"},
{value:"SAL", label:"San Salvador/SAN SALVADOR, El Salvador(SAL)"},
{value:"EAS", label:"San Sebastian/SAN SEBASTIAN, Spain And Canary Islands(EAS)"},
{value:"SAH", label:"Sanaa/SANAA, Yemen, Republic Of(SAH)"},
{value:"SDK", label:"Sandakan/SANDAKAN, Malaysia(SDK)"},
{value:"NDY", label:"Sanday/SANDAY, United Kingdom(NDY)"},
{value:"LED", label:"Sankt-Peterburg/SANKT-PETERBURG, Russian Federation(LED)"},
{value:"SNA", label:"Santa Ana John Wayne Intl/SANT ANA, United States(SNA)"},
{value:"SBA", label:"Santa Barbara/SANTA BARBARA, United States(SBA)"},
{value:"VVI", label:"Santa Cruz/SANTA CRUZ, Bolivia(VVI)"},
{value:"SPC", label:"Santa Cruz De La Palma/SANTA CRUZ, Spain And Canary Islands(SPC)"},
{value:"SRZ", label:"Santa Cruz El Tropmpillo/SANTA CRUZ, Bolivia(SRZ)"},
{value:"SAF", label:"Santa Fe/SNATA FE, United States(SAF)"},
{value:"SMX", label:"Santa Maria/SANTA MARIA, United States(SMX)"},
{value:"SMR", label:"Santa Marta/SANTA MARTA, Colombia(SMR)"},
{value:"STS", label:"Santa Rosa/SANTA ROSA, United States(STS)"},
{value:"RSA", label:"Santa Rosa Airport/SANTA ROSA, Argentina(RSA)"},
{value:"SDR", label:"Santander/SANTANDER, Spain And Canary Islands(SDR)"},
{value:"STM", label:"Santarem/SANTAREM, Brazil(STM)"},
{value:"SCQ", label:"Santiago De Compostela/SANTIAGO COMP, Spain And Canary Islands(SCQ)"},
{value:"ULC", label:"Santiago Los Cerrillos/SANTIAGO, Chile(ULC)"},
{value:"STI", label:"Santiago Municipal/SANTIAGO, Dominican Republic(STI)"},
{value:"SCL", label:"Santiago Pudahuel/SANTIAGO, Chile(SCL)"},
{value:"SDQ", label:"Santo Domingo/SANTO DOMINGO, Dominican Republic(SDQ)"},
{value:"HEX", label:"Santo Domingo Herrera Apt/SANTO DOMINGO HERRERA AIRPORT, Dominican Republic(HEX)"},
{value:"SYX", label:"Sanya/SANYA, China(SYX)"},
{value:"SJP", label:"Sao Jose R Preto/SAO JOSE R PRETO, Brazil(SJP)"},
{value:"SLZ", label:"Sao Luiz/SAO LUIZ, Brazil(SLZ)"},
{value:"SAO", label:"Sao Paulo Airport/SAO PAULO, Brazil(SAO)"},
{value:"VCP", label:"Sao Paulo Viraopos Airport/SAO PAULO, Brazil(VCP)"},
{value:"GRU", label:"Sao Paulo/Guarulhos Intl/SAO PAULO, Brazil(GRU)"},
{value:"SPK", label:"Sapporo/SAPPORO, Japan(SPK)"},
{value:"CTS", label:"Sapporo/Chitose/SAPPORO, Japan(CTS)"},
{value:"SJJ", label:"Sarajevo/SARAJEVO, Bosnia Hercegovina(SJJ)"},
{value:"CGH", label:"Sau Paulo Conghonhas/SAO PAULO, Brazil(CGH)"},
{value:"SAV", label:"Savannah International Apt/SAVANNAH, United States(SAV)"},
{value:"SVL", label:"Savonlinna/SAVONLINNA, Finland(SVL)"},
{value:"SEA", label:"Seattle/SEATTLE, United States(SEA)"},
{value:"PLX", label:"Semipalatinsk/SEMIPALATINSK, Kazakhstan(PLX)"},
{value:"SDJ", label:"Sendai/SENDAI, Japan(SDJ)"},
{value:"SEL", label:"Seoul/SEOUL, Korea, Republic Of(SEL)"},
{value:"GMP", label:"Seoul Gimpo/SEOUL, Korea, Republic Of(GMP)"},
{value:"SVQ", label:"Seville/SEVILLE, Spain And Canary Islands(SVQ)"},
{value:"SHA", label:"Shanghai/Hongqiao Int&acute;l/SHANGHAI, China(SHA)"},
{value:"PVG", label:"Shanghai/Pu Dong/SHANGHAI, China(PVG)"},
{value:"SNN", label:"Shannon/SHANNON, Ireland(SNN)"},
{value:"SWA", label:"Shantou/SHANTOU, China(SWA)"},
{value:"SHJ", label:"Sharjah/SHARJAH, United Arab Emirates(SHJ)"},
{value:"SSH", label:"Sharm El Sheikh/SHARM E SHEIK, Egypt(SSH)"},
{value:"SZD", label:"Sheffield/SHEFFIELD, United Kingdom(SZD)"},
{value:"SBX", label:"Shelby/SHELBY, United States(SBX)"},
{value:"SYA", label:"Shemya/SHEMYA, United States(SYA)"},
{value:"SHE", label:"Shenyang/SHENYANG, China(SHE)"},
{value:"SZX", label:"Shenzhen/SHENZHEN, China(SZX)"},
{value:"LWK", label:"Shetland Islands Lerwick/SHETLAND ISLANDS SUMBURGH, United Kingdom(LWK)"},
{value:"SCS", label:"Shetland Islands Scatsta/SHETLAND ISLANDS SUMBURGH, United Kingdom(SCS)"},
{value:"LSI", label:"Shetland Islands Sumburgh/SHETLAND ISLANDS SUMBURGH, United Kingdom(LSI)"},
{value:"SJW", label:"Shijiazhuang/SHIJIAZHUANG, China(SJW)"},
{value:"SYZ", label:"Shiraz/SHIRAZ, Iran (Islamic Republic Of)(SYZ)"},
{value:"FSZ", label:"Shizuoka/SHIZUOKA, Japan(FSZ)"},
{value:"SKT", label:"Sialkot/SIALKOT, Russian Federation(SKT)"},
{value:"SBW", label:"Sibu/SIBU, Malaysia(SBW)"},
{value:"REP", label:"Siem Reap/SIEM REAP, Cambodia(REP)"},
{value:"SYM", label:"Simao/SIMAO, China(SYM)"},
{value:"SIP", label:"Simferopol/SIMFEROPOL, Ukraine(SIP)"},
{value:"CNL", label:"Sindal/SINDAL, Denmark(CNL)"},
{value:"SIN", label:"Singapore/Changi/SINGAPORE, Singapore(SIN)"},
{value:"SUX", label:"Sioux City/SIOUX CITY, United States(SUX)"},
{value:"FSD", label:"Sioux Falls Foss Field/SIOUX FALLS, United States(FSD)"},
{value:"SIT", label:"Sitka/SITKA, United States(SIT)"},
{value:"JSI", label:"Skiathos/SKIATHOS, Greece(JSI)"},
{value:"SQW", label:"Skive/SKIVE, Denmark(SQW)"},
{value:"SKP", label:"Skopje/SKOPJE, Macedonia(SKP)"},
{value:"SZK", label:"Skukuza/SKUKUZA, South Africa(SZK)"},
{value:"SXL", label:"Sligo/SLIGO, Ireland(SXL)"},
{value:"AER", label:"Sochi/Adler/SOCHI/ADLER, Russian Federation(AER)"},
{value:"SOF", label:"Sofia/SOFIA, Bulgaria(SOF)"},
{value:"CLJ", label:"Someseni International Airport/CLUJ, Romania(CLJ)"},
{value:"JZH", label:"Song Pan/SONG PAN, China(JZH)"},
{value:"SBN", label:"South Bend/SOUTH BEND, United States(SBN)"},
{value:"SOU", label:"Southampton/SOUTHAMPTON, United Kingdom(SOU)"},
{value:"SEN", label:"Southend Airport/SOUTHEND, United Kingdom(SEN)"},
{value:"SPU", label:"Split/SPLIT, Croatia(SPU)"},
{value:"GEG", label:"Spokane/SPOKANE, United States(GEG)"},
{value:"SPI", label:"Springfield Capitol/SPRINGFIED IL, United States(SPI)"},
{value:"SGF", label:"Springfield Regional/SPRINGFIELD MO, United States(SGF)"},
{value:"SXR", label:"Srinagar/SRINAGAR, India(SXR)"},
{value:"STX", label:"St Croix Island/ST CORIX, Virgin Islands, (U.S.)(STX)"},
{value:"SKB", label:"St Kitts/ST KITTS, Saint Kitts And Nevis(SKB)"},
{value:"SLU", label:"St Lucia Castries Vigie/ST LUCIA, Saint Lucia(SLU)"},
{value:"UVF", label:"St Lucia Hewanorra/ST LUCIA, Saint Lucia(UVF)"},
{value:"SXM", label:"St Maarten/ST MAARTEN, Netherlands Antilles(SXM)"},
{value:"STT", label:"St Thomas Island/ST THOMAS, Virgin Islands, (U.S.)(STT)"},
{value:"STL", label:"St. Louis/Lambert Intl/ST LOUIS, United States(STL)"},
{value:"XSH", label:"St.Pierre Des Corps Rail St/SAINT-PIERRE DES CORPS RAIL, France(XSH)"},
{value:"SCE", label:"State College/STATE COLLEGE, United States(SCE)"},
{value:"SVG", label:"Stavanger/STAVANGER, Norway(SVG)"},
{value:"STW", label:"Stavropol/STAVROPOL, Russian Federation(STW)"},
{value:"BMA", label:"Stockholm Bromma/STOCKHOLM, Sweden(BMA)"},
{value:"ARN", label:"Stockholm/Arlanda/STOCKHOLM, Sweden(ARN)"},
{value:"SXB", label:"Strasbourg/STRASBOURG, France(SXB)"},
{value:"SYY", label:"Stronoway/STORNOWAY, United Kingdom(SYY)"},
{value:"SOY", label:"Stronsay/STRONSAY, United Kingdom(SOY)"},
{value:"STR", label:"Stuttgart Echterdingen Apt/STUTTGART, Germany(STR)"},
{value:"THS", label:"Sukhothai/SOKHOTHAI, Thailand(THS)"},
{value:"ISU", label:"Sulaymaniyah/SULAYMANIYAH, Iraq(ISU)"},
{value:"KBR", label:"Sultan Ismail Petra/KOTA BHARU, Malaysia(KBR)"},
{value:"SUN", label:"Sun Valley/SUN VALLEY, United States(SUN)"},
{value:"MCY", label:"Sunshine Coast/MAROOCHYDO, Australia(MCY)"},
{value:"SUB", label:"Surabaya/Juanda/SURABAYA, Indonesia(SUB)"},
{value:"SGC", label:"Surgut/SURGUT, Russian Federation(SGC)"},
{value:"SUV", label:"Suva Fiji Island/SUVA, Fiji(SUV)"},
{value:"SVX", label:"Sverdlovsk/SVERDLOVSK, Russian Federation(SVX)"},
{value:"SYD", label:"Sydney Kingsford Australia/SYDNEY, Australia(SYD)"},
{value:"SYR", label:"Syracuse/SYRACUSE, United States(SYR)"},
{value:"TCQ", label:"Tacna/TACNA, Peru(TCQ)"},
{value:"TAE", label:"Taegu/TAEGU, Korea, Republic Of(TAE)"},
{value:"RMQ", label:"Taichung/TAICHUNG, Taiwan(RMQ)"},
{value:"TIF", label:"Taif Airport/TAIF, Saudi Arabia(TIF)"},
{value:"TSA", label:"Taipei/Shungshan/TAIPEI, Taiwan(TSA)"},
{value:"TPE", label:"Taipei/Taoyuan/TAIPEI, Taiwan(TPE)"},
{value:"TYN", label:"Taiyuan Wusu/TAIYUAN, China(TYN)"},
{value:"TAK", label:"Takamatsu/TAKAMATSU, Japan(TAK)"},
{value:"TLH", label:"Tallahassee/TALLAHASS, United States(TLH)"},
{value:"TLL", label:"Tallinn/TALLINN, Estonia(TLL)"},
{value:"TPA", label:"Tampa/TAMPA, United States(TPA)"},
{value:"TMP", label:"Tampere/TAMPERE, Finland(TMP)"},
{value:"TAM", label:"Tampico/TAMPICO, Mexico(TAM)"},
{value:"TMW", label:"Tamworth/TAMWORTH, Australia(TMW)"},
{value:"TPP", label:"Tarapoto/TARAPOTO, Peru(TPP)"},
{value:"TRO", label:"Taree/TAREE, Australia(TRO)"},
{value:"TAS", label:"Tashkent Yuzhny/UZBEKISTAN, Uzbekistan(TAS)"},
{value:"TWU", label:"Tawau/TAWAU, Malaysia(TWU)"},
{value:"TBS", label:"Tbilisi/TBILISI, Georgia(TBS)"},
{value:"BER", label:"Tegel/BERLIN, Germany(BER)"},
{value:"THR", label:"Tehran/TEHRAN, Iran (Islamic Republic Of)(THR)"},
{value:"TLV", label:"Tel-Aviv/Ben Gurion/TEL AVIV YAFO, Israel(TLV)"},
{value:"ZCO", label:"Temuco/TEMUCO, Chile(ZCO)"},
{value:"TFS", label:"Tenerife Canary Island/TENERIFE, Spain And Canary Islands(TFS)"},
{value:"TFN", label:"Tenerife Norte Apt/TENERIFE, Spain And Canary Islands(TFN)"},
{value:"TCZ", label:"Tengchong/TENGCHONG, China(TCZ)"},
{value:"TGU", label:"Tequchigalpa/TEGUCIGALPA, Honduras(TGU)"},
{value:"THE", label:"Teresina Airport/TERESINA, Brazil(THE)"},
{value:"TXK", label:"Texarkana/TEXARKANA, United States(TXK)"},
{value:"SKG", label:"Thesaloniki/THESSALONIKI, Greece(SKG)"},
{value:"JTR", label:"Thira/THIRA, Greece(JTR)"},
{value:"TED", label:"Thisted/THISTED, Denmark(TED)"},
{value:"TIS", label:"Thursday Island/THURSDAY ISLAND, Australia(TIS)"},
{value:"TSN", label:"Tianjin/TIANJIN, China(TSN)"},
{value:"TIJ", label:"Tijuana/TIJUANA, Mexico(TIJ)"},
{value:"TSR", label:"Timisoara/TIMISOARA, Romania(TSR)"},
{value:"TIA", label:"Tirana/TIRANA, Albania(TIA)"},
{value:"TRE", label:"Tiree/TIREE, United Kingdom(TRE)"},
{value:"TGM", label:"Tirgu Mures/TIRGU MURES, Romania(TGM)"},
{value:"TRZ", label:"Tiruchirapally/TIRUCHIRAPALL, India(TRZ)"},
{value:"TIR", label:"Tirupati/TIRUPATI, India(TIR)"},
{value:"TNG", label:"Tnagier/TANGIER, Morocco(TNG)"},
{value:"TAB", label:"Tobago/TOBAGO, Trinidad And Tobago(TAB)"},
{value:"TKN", label:"Tokunoshima/TOKUNOSHIMA, Japan(TKN)"},
{value:"TKS", label:"Tokushima/TOKUSHIMA, Japan(TKS)"},
{value:"NRT", label:"Tokyo/Narita/TOKYO, Japan(NRT)"},
{value:"TOL", label:"Toledo/TOLEDO, United States(TOL)"},
{value:"TPR", label:"Tom Price/TOM PRICE, Australia(TPR)"},
{value:"TOF", label:"Tomsk/TOMSK, Russian Federation(TOF)"},
{value:"TNH", label:"Tonghua Sanyuanpu Airport/TONGHUA SANYUANPU, China(TNH)"},
{value:"TGO", label:"Tongliao/TONGLIAO, China(TGO)"},
{value:"TEN", label:"Tongren/Daxing/TONGREN, China(TEN)"},
{value:"YYZ", label:"Toronto/TORONTO, Canada(YYZ)"},
{value:"TRC", label:"Torreon/TORREON, Mexico(TRC)"},
{value:"TTJ", label:"Tottori/TOTTORI, Japan(TTJ)"},
{value:"TLN", label:"Toulon/TOULON, France(TLN)"},
{value:"TLS", label:"Toulouse/TOULOUSE, France(TLS)"},
{value:"TUF", label:"Tours/TOURS, France(TUF)"},
{value:"TSV", label:"Townsville/TOWNSVILLE, Australia(TSV)"},
{value:"TOY", label:"Toyama/TOYAMA, Japan(TOY)"},
{value:"TZX", label:"Trabzon/TRABZON, Turkey(TZX)"},
{value:"TDX", label:"Trat/TRAT, Thailand(TDX)"},
{value:"TVC", label:"Traverse City/TRAVERSE, United States(TVC)"},
{value:"PUU", label:"Tres De Mayo Apt/PUERTO ASIS, Colombia(PUU)"},
{value:"TRI", label:"Tri Cities Regional/BRISTOL, United States(TRI)"},
{value:"TRS", label:"Trieste/TRIESTE, Italy(TRS)"},
{value:"POS", label:"Trinidad/PORT OF SPAIN, Trinidad And Tobago(POS)"},
{value:"TIP", label:"Tripoli/TRIPOLI, Libyan Arab Jamahiriya(TIP)"},
{value:"TRV", label:"Trivandrum/TRIVANDRUM, India(TRV)"},
{value:"TOS", label:"Tromso/TROMSO, Norway(TOS)"},
{value:"TRU", label:"Trujillo/TRUJILLO, Peru(TRU)"},
{value:"TUS", label:"Tucson/TUCSON, United States(TUS)"},
{value:"TUC", label:"Tucuman/TUCUMAN, Argentina(TUC)"},
{value:"TCE", label:"Tulcea Airport/TULCEA, Romania(TCE)"},
{value:"TUL", label:"Tulsa/TULSA, United States(TUL)"},
{value:"TBP", label:"Tumbes/TUMBES, Peru(TBP)"},
{value:"TUN", label:"Tunis/TUNIS, Tunisia(TUN)"},
{value:"TXN", label:"Tunxi/TUNXI, China(TXN)"},
{value:"TRN", label:"Turin/TURIN, Italy(TRN)"},
{value:"TKU", label:"Turku/TURKU, Finland(TKU)"},
{value:"TGZ", label:"Tuxtla Gutier/TUXTLA GUTIER, Mexico(TGZ)"},
{value:"TYR", label:"Tyler/TYLER, United States(TYR)"},
{value:"TJM", label:"Tyumen/TYUMEN, Russian Federation(TJM)"},
{value:"UBJ", label:"Ube Yamaguchi/YAMAGUCHI, Japan(UBJ)"},
{value:"UDI", label:"Uberlandia/UBERLANDIA, Brazil(UDI)"},
{value:"UDR", label:"Udaipur/UDAIPUR, India(UDR)"},
{value:"UTH", label:"Udon Thani/UDON THANI, Thailand(UTH)"},
{value:"UFA", label:"Ufa/UFA, Russian Federation(UFA)"},
{value:"ULN", label:"Ulan Bator Buyant Ukhaa/ULAN BATOR, Mongolia(ULN)"},
{value:"UUD", label:"Ulan-Ude/ULAN-UDE, Russian Federation(UUD)"},
{value:"HLH", label:"Ulanhot/ULANHOT, China(HLH)"},
{value:"UNT", label:"Unst/UNST SHETLAND ISLAND, United Kingdom(UNT)"},
{value:"UGC", label:"Urgench/URGENCH, Uzbekistan(UGC)"},
{value:"URC", label:"Urumqi/URUMQI, China(URC)"},
{value:"USH", label:"Ushuaia/USHUAIA, Argentina(USH)"},
{value:"VAA", label:"Vaasa/VAASA, Finland(VAA)"},
{value:"BDQ", label:"Vadodara/VADODARA, India(BDQ)"},
{value:"ZAL", label:"Valdivia/VALDIVIA, Chile(ZAL)"},
{value:"VLC", label:"Valencia/VALENCIA, Spain And Canary Islands(VLC)"},
{value:"EGE", label:"Vali Eagle/VAIL EAGLE, United States(EGE)"},
{value:"VLL", label:"Valladolid/VALLADOLID, Spain And Canary Islands(VLL)"},
{value:"YVR", label:"Vancouver/VANCOUVER, Canada(YVR)"},
{value:"VVC", label:"Vanguardia Airport/VILLAVICENCIO, Colombia(VVC)"},
{value:"VRA", label:"Varadero/VARADERO, Cuba(VRA)"},
{value:"VNS", label:"Varanasi/VARANASI, India(VNS)"},
{value:"VRK", label:"Varkaus/VARKAUS, Finland(VRK)"},
{value:"VAR", label:"Varna/VARNA, Bulgaria(VAR)"},
{value:"VCE", label:"Venice/VENICE, Italy(VCE)"},
{value:"VER", label:"Veracruz/VERACRUZ, Mexico(VER)"},
{value:"VRN", label:"Verona/VERONA, Italy(VRN)"},
{value:"YYJ", label:"Victoria Intl Airport/VICTORIA, Canada(YYJ)"},
{value:"VFA", label:"Victorua Falls/VICTORIA FALLS, Zimbabwe(VFA)"},
{value:"VIE", label:"Vienna/Schwechat/VIENNA, Austria(VIE)"},
{value:"VTE", label:"Vientiane/VIENTIANE, Lao People's Democratic Republic(VTE)"},
{value:"VGO", label:"Vigo/VIGO, Spain And Canary Islands(VGO)"},
{value:"RGS", label:"Vilafria Airport Burgos/BURGOS, Spain And Canary Islands(RGS)"},
{value:"VSA", label:"Villahermosa/VILLAHERMOSA, Mexico(VSA)"},
{value:"VNO", label:"Vilnius/VILNIUS, Lithuania(VNO)"},
{value:"KNA", label:"Vina Del Mar/VINA DEL MAR, Chile(KNA)"},
{value:"VTZ", label:"Vishakhapatnam/VISHAKHAPATNA, India(VTZ)"},
{value:"VIT", label:"Vitoria/VITORIA, Spain And Canary Islands(VIT)"},
{value:"VIX", label:"Vitoria/VITORIA, Brazil(VIX)"},
{value:"OGZ", label:"Vladikavkaz/VLADIKAVKAZ, Russian Federation(OGZ)"},
{value:"VVO", label:"Vladivostok/VLADIVOSTOK, Russian Federation(VVO)"},
{value:"VOG", label:"Volgograd/VOLGOGRAD, Russian Federation(VOG)"},
{value:"VOL", label:"Volos/VOLOS, Greece(VOL)"},
{value:"ACT", label:"Waco/WACO, United States(ACT)"},
{value:"CNW", label:"Waco James Connall Airport/WACO JAMES CONNALL, United States(CNW)"},
{value:"WGA", label:"Wagga Wagga/WAGGA WAGGA, Australia(WGA)"},
{value:"ALW", label:"Walla Walla/WALLA WALL, United States(ALW)"},
{value:"WXN", label:"Wanxian/WANXIAN, China(WXN)"},
{value:"WAW", label:"Warsaw/WARSAW, Poland(WAW)"},
{value:"DCA", label:"Washington DC / Baltimore/WASHINGTON, United States(DCA)"},
{value:"IAD", label:"Washington Dulles Dc/WASHINGTON, United States(IAD)"},
{value:"WAT", label:"Waterford/WATERFORD, Ireland(WAT)"},
{value:"ALO", label:"Waterloo/WATERLOO, United States(ALO)"},
{value:"ART", label:"Watertown/WATERTOWN NY, United States(ART)"},
{value:"NRN", label:"Weeze/WEEZE, Germany(NRN)"},
{value:"WEF", label:"Weifang/WEIFANG, China(WEF)"},
{value:"WEH", label:"Weihai/WEIHAI, China(WEH)"},
{value:"WEI", label:"Weipa/WEIPA, Australia(WEI)"},
{value:"WLG", label:"Wellington/WELLINGTON, New Zealand(WLG)"},
{value:"EAT", label:"Wenatchee/WENATCHEE, United States(EAT)"},
{value:"WNH", label:"Wenshan/WENSHAN, China(WNH)"},
{value:"WNZ", label:"Wenzhou/WENZHOU, China(WNZ)"},
{value:"PBI", label:"West Palm Beach/WEST PALM BEACH, United States(PBI)"},
{value:"HPN", label:"Westchester County/WESTCHESTER, United States(HPN)"},
{value:"GWT", label:"Westerland/WESTERLAND, Germany(GWT)"},
{value:"WRY", label:"Westray/WESTRAY, United Kingdom(WRY)"},
{value:"SPS", label:"Wichita Falls/WICHITA FALLS, United States(SPS)"},
{value:"ICT", label:"Wichita/Mid-Continent/WICHITA, United States(ICT)"},
{value:"WIC", label:"Wick/WICK, United Kingdom(WIC)"},
{value:"AVP", label:"Wilkes-Barre Scranton Apt/SCRANTON, United States(AVP)"},
{value:"IPT", label:"Williamsport/WILLIAMSPORT, United States(IPT)"},
{value:"NTL", label:"Williamtown Newcastle/NEWCASTLE, Australia(NTL)"},
{value:"ILM", label:"Wilmington/WILMINGTON, United States(ILM)"},
{value:"WDH", label:"Windhoek International/WINDHOEK, Namibia(WDH)"},
{value:"YWG", label:"Winnipeg Intl Airport/WINNIPEG, Canada(YWG)"},
{value:"INT", label:"Winston - Salem/GREENSBORO, United States(INT)"},
{value:"WOL", label:"Wollongong/WOLLONGONG, Australia(WOL)"},
{value:"ORH", label:"Worcester/WORCESTER, United States(ORH)"},
{value:"WRG", label:"Wrangell/WRANGELL, United States(WRG)"},
{value:"WUA", label:"Wu Hai/WU HAI, China(WUA)"},
{value:"WUH", label:"Wuhan/WUHAN, China(WUH)"},
{value:"JIQ", label:"Wulingshan/QIANJIANG, China(JIQ)"},
{value:"WUX", label:"Wuxi/WUXI, China(WUX)"},
{value:"WUS", label:"Wuyishan/WUYISHAN, China(WUS)"},
{value:"XIY", label:"Xi'An Xianyang/XI'AN, China(XIY)"},
{value:"XMN", label:"Xiamen/XIAMEN, China(XMN)"},
{value:"XFN", label:"Xiangfan/XIANGFAN, China(XFN)"},
{value:"XIL", label:"Xilinhot/XILINHOT, China(XIL)"},
{value:"ACX", label:"Xingyi/XINGYI, China(ACX)"},
{value:"XNN", label:"Xining/XINING, China(XNN)"},
{value:"XUZ", label:"Xuzhou/XUZHOU, China(XUZ)"},
{value:"YKM", label:"Yakima Air Terminal/YAKIMA, United States(YKM)"},
{value:"YAK", label:"Yakutat/YAKUTAT, United States(YAK)"},
{value:"YKS", label:"Yakutsk/KAYES, Russian Federation(YKS)"},
{value:"GAJ", label:"Yamagata/YAMAGATA, Japan(GAJ)"},
{value:"YNZ", label:"Yancheng/YANCHENG, China(YNZ)"},
{value:"YTY", label:"Yangzhou Taizhou Airport/YANGZHOU, China(YTY)"},
{value:"YNJ", label:"Yanji/YANJI, China(YNJ)"},
{value:"HRB", label:"Yanjiagang Harbin/HARBIN, China(HRB)"},
{value:"YNT", label:"Yantai/YANTAI, China(YNT)"},
{value:"EVN", label:"Yerevan/EREVAN, Armenia(EVN)"},
{value:"YBP", label:"Yibin/YIBIN, China(YBP)"},
{value:"YIH", label:"Yichang/YICHANG, China(YIH)"},
{value:"LDS", label:"Yichun Lindu Airport/YICHUN HEILONGJIANG, China(LDS)"},
{value:"INC", label:"Yinchuan/YINCHUAN, China(INC)"},
{value:"YIN", label:"Yining/YINING, China(YIN)"},
{value:"YIW", label:"Yiwu/YIWU, China(YIW)"},
{value:"OGN", label:"Yonaguni Jima/YONAGUNI JIMA, Japan(OGN)"},
{value:"RNJ", label:"Yoronjima/YORONJIMA, Japan(RNJ)"},
{value:"UYN", label:"Yulin/YULIN, China(UYN)"},
{value:"YUM", label:"Yuma International Airport/YUMA, United States(YUM)"},
{value:"YUS", label:"Yushu Batang/YUSHU, China(YUS)"},
{value:"FYJ", label:"Yuyuan/FUYUAN, China(FYJ)"},
{value:"UUS", label:"Yuzhno-Sakhalinsk/YUZHNO/SAKHALINSK, Russian Federation(UUS)"},
{value:"ZCL", label:"Zacatecas/ZACATECAS, Mexico(ZCL)"},
{value:"ZAG", label:"Zagreb/ZAGREB, Croatia(ZAG)"},
{value:"ZTH", label:"Zakinthos/ZAKINTHOS ISLAND, Greece(ZTH)"},
{value:"ZNZ", label:"Zanzibar/ZANZIBAR, Tanzania, United Republic(ZNZ)"},
{value:"ZAZ", label:"Zaragoza/ZARAGOZA, Spain And Canary Islands(ZAZ)"},
{value:"ZQZ", label:"Zhangjiakou/ZHANGJIAKOU, China(ZQZ)"},
{value:"ZHA", label:"Zhangjiang/ZHANJIANG, China(ZHA)"},
{value:"ZAT", label:"Zhaotong/ZHAOTONG, China(ZAT)"},
{value:"CGO", label:"Zhengzhou/ZHENGZHOU, China(CGO)"},
{value:"HSN", label:"Zhoushan/ZHONGSHAN, China(HSN)"},
{value:"ZUH", label:"Zhuhai Sanzao/ZHUHAI, China(ZUH)"},
{value:"ZYI", label:"Zunyi Xinzhou Airport/ZUNYI, China(ZYI)"},
{value:"ZRH", label:"Zurich/ZURICH, Switzerland(ZRH)"},
{value:"ZQW", label:"Zweibrucken/ZWEIBRUCKEN, Germany(ZQW)"},
]