var airportDesc=[
    "Aalborg Airport/AALBORG, Denmark(AAL)",
    "Aarhus Tirstrup Airport/AARHUS, Denmark(AAR)",
    "Abadan/ABADAN, Iran (Islamic Republic Of)(ABD)",
    "Abakan/ABAKAN, Russian Federation(ABA)",
    "Aberdeen/ABERDEEN, United Kingdom(ABZ)",
    "Abha Regional Airport/ABHA, Saudi Arabia(AHB)",
    "Abidjan/ABIDJAN, Cote Divoire(ABJ)",
    "Abilene/ABILENE, United States(ABI)",
    "Abu Dhabi/ABU DHABI, United Arab Emirates(AUH)",
    "Abuja/ABUJA, Nigeria(ABV)",
    "Acapulco/ACAPULCO, Mexico(ACA)",
    "Accra/ACCRA, Ghana(ACC)",
    "Adana/ADANA, Turkey(ADA)",
    "Addis Ababa Bole Intl/ADDIS ABABA, Ethiopia(ADD)",
    "Adelaide/ADELAIDE, Australia(ADL)",
    "Aden/ADEN, Yemen, Republic Of(ADE)",
    "Adnan Menderesapt Izmir/IZMIR, Turkey(ADB)",
    "Agadir/AGADIR, Morocco(AGA)",
    "Agartala/AGARTALA, India(IXA)",
    "Ahmedabad/AHMEDABAD, India(AMD)",
    "Ajaccio/AJACCIO, France(AJA)",
    "Akita/AKITA, Japan(AXT)",
    "Akron Canton/AKRON, United States(CAK)",
    "Aksu/AKSU, China(AKU)",
    "Al - Fujairah/AL-FUJAIRAH, United Arab Emirates(FJR)",
    "Al Ain/AL AIN, United Arab Emirates(AAN)",
    "Al Arish/AL-ARISH, Egypt(AAC)",
    "Al Maktoum Intl Airport/DUBAI, United Arab Emirates(DWC)",
    "Al Muthana Baghdad/BAGHDAD, Iraq(BGW)",
    "Al-Ahsa Domestic Airport/HOFUF, Saudi Arabia(HOF)",
    "Albany County Usa/ALBANY COUNTY NY, United States(ALB)",
    "Albi/ALBI, France(LBI)",
    "Albuquerque/ALBUQUERQU, United States(ABQ)",
    "Albury/ALBURY, Australia(ABX)",
    "Aleppo/ALEPPO, Syrian Arab Republic(ALP)",
    "Alexandria Borg El Arab/ALEXANDRIA, Egypt(HBE)",
    "Alexandria Egypt/ALEXANDRIA, Egypt(ALY)",
    "Alexandria England Afb Usa/ALEXANDRIA ENGLAND AFB, United States(AEX)",
    "Alfonso Lopez Pumarego Apt/VALLEDUPAR, Colombia(VUP)",
    "Alfredo Vasquez Cobo Intl Apt/LETICIA, Colombia(LET)",
    "Algiers/ALGIERS, Algeria(ALG)",
    "Alicante/ALICANTE, Spain And Canary Islands(ALC)",
    "Alice Spring/ALICE SPRINGS, Australia(ASP)",
    "Alikunsha/SHIQUANHE, China(NGQ)",
    "Allentown Bethlehem Easton/ALLENTOWN, United States(ABE)",
    "Almaty/ALMATY, Kazakhstan(ALA)",
    "Almeria/ALMERIA, Spain And Canary Islands(LEI)",
    "Alor Setar/ALOR SETAR, Malaysia(AOR)",
    "Amami/AMAMI O SHIMA, Japan(ASJ)",
    "Amarillo/AMARILLO, United States(AMA)",
    "Amman/Queen Alia Intl/AMMAN, Jordan(AMM)",
    "Amritsar/AMRITSAR, India(ATQ)",
    "Amsterdam/Schiphol/AMSTERDAM, Netherlands(AMS)",
    "Anapa/ANAPA, Russian Federation(AAQ)",
    "Anchorage/ANCHORAGE, United States(ANC)",
    "Anguilla/ANGUILLA, Anguilla(AXA)",
    "Ankara/ANKARA, Turkey(ANK)",
    "Ankara Esenboga/ANKARA, Turkey(ESB)",
    "Annecy/ANNECY, France(NCY)",
    "Anqing/ANQING, China(AQG)",
    "Antalya/ANTALYA, Turkey(AYT)",
    "Antique/ANTIGUA, Antigua And Barbuda(ANU)",
    "Antofagasta/ANTOFAGASTA, Chile(ANF)",
    "Antwerp Deurne Airport/ANTWERP, Belgium(ANR)",
    "Aomori/AOMORI, Japan(AOJ)",
    "Apartado Airport/APARTADO, Colombia(APO)",
    "Aqaba/AQABA, Jordan(AQJ)",
    "Aracaju/ARACAJU, Brazil(AJU)",
    "Arcata Eureka/ARCATA, United States(ACV)",
    "Arequipa/AREQUIPA, Peru(AQP)",
    "Arica/ARICA, Chile(ARI)",
    "Armidale/ARMIDALE, Australia(ARM)",
    "Aruba/ARUBA, Aruba(AUA)",
    "Arvidsjaur/ARVIDSJAUR, Sweden(AJR)",
    "Asahikawa/ASAHIKAWA, Japan(AKJ)",
    "Asheville/ASHEVILLE, United States(AVL)",
    "Ashkabad/KHUDZHAND, Tadjikistan(LBD)",
    "Ashkhabad/ASHKHABAD, Turkmenistan(ASB)",
    "Asmara Yohanes Iv/ASMARA YOHANES IV, Eritrea(ASM)",
    "Aspen/ASPEN, United States(ASE)",
    "Astrakhan/ASTRAKHAN, Russian Federation(ASF)",
    "Asturias/ASTURIAS, Spain And Canary Islands(OVD)",
    "Asuncion/ASUNCION, Paraguay(ASU)",
    "Athens/ATHENS, Greece(ATH)",
    "Atlanta/ATLANTA, United States(ATL)",
    "Atqasuk/ATQASUK, United States(ATK)",
    "Auckland/AUCKLAND, New Zealand(AKL)",
    "Augusta Bush Field/AUGUSTA GA, United States(AGS)",
    "Aurangabad/AURANGABAD, India(IXU)",
    "Aurillac/AURILLAC, France(AUR)",
    "Austin/AUSTIN, United States(AUS)",
    "Avalon/AVALON, Australia(AVV)",
    "Ayacucho/AYACUCHO, Peru(AYP)",
    "Ayers Rock/AYERS ROCK, Australia(AYQ)",
    "Badajoz/BADAJOZ, Spain And Canary Islands(BJZ)",
    "Bagdogra/BAGDOGRA, India(IXB)",
    "Baghdad/BAGHDAD, Iraq(SDA)",
    "Bahia Blanca Airport/BAHIA BLANCA, Argentina(BHI)",
    "Bahrain/BAHRAIN, Bahrain(BAH)",
    "Baishan/BAISHAN, China(NBS)",
    "Bakersfield/BAKERSFIELD, United States(BFL)",
    "Baku/BAKU, Azerbaijan(BAK)",
    "Baku/BAKU, Azerbaijan(GYD)",
    "Bali/Denpasar/DENPASAR/BALI, Indonesia(DPS)",
    "Ballina/BALLINA NS, Australia(BNK)",
    "Balmaceda/BALMACEDA, Chile(BBA)",
    "Baltimore/BALTIMORE, United States(BWI)",
    "Bandar Seri Begawan/BANDAR SERI BEGAWAN, Brunei Darussalam(BWN)",
    "Bangalore/BENGALURU, India(BLR)",
    "Bangkok/Suvarnabhumi/BANGKOK, Thailand(BKK)",
    "Bangor/BANGOR, United States(BGR)",
    "Bao Vista Intl Airport/BOA VISTA, Brazil(BVB)",
    "Baoshan/BAOSHAN, China(BSD)",
    "Baotou/BAOTOU, China(BAV)",
    "Barcelona/BARCELONA, Spain And Canary Islands(BCN)",
    "Bari/BARI, Italy(BRI)",
    "Barnaul/BARNAUL, Russian Federation(BAX)",
    "Barra/BARRA, United Kingdom(BRR)",
    "Barrabguilla/BARRANQUILLA, Colombia(BAQ)",
    "Barrow/BARROW, United States(BRW)",
    "Barrow Island/BARROW ISLAND, Australia(BWB)",
    "Basle/BASLE, Switzerland(BSL)",
    "Basrah International/BASRA, Iraq(BSR)",
    "Bastia/BASTIA, France(BIA)",
    "Batam/Hang Nadim/BATAM, Indonesia(BTH)",
    "Baton Rouge Ryan Apt/BATON ROUGE, United States(BTR)",
    "Battle Creek/BATTLE CREEK, United States(BTL)",
    "Batumi/BATUMI, Georgia(BUS)",
    "Bayannur/BAYANNUR, China(RLK)",
    "Beaumont/BEAUMONT, United States(BPT)",
    "Beef Island/BEEF ISLAND, Virgin Islands, (British)(EIS)",
    "Beihai/BEIHAI, China(BHY)",
    "Beijing(Peking)/BEIJING, China(PEK)",
    "Beirut Intl/BEIRUT, Lebanon(BEY)",
    "Belem/BELEM, Brazil(BEL)",
    "Belfast/BELFAST INTERNATIONAL, United Kingdom(BFS)",
    "Belfast City Apt/BELFAST INTERNATIONAL, United Kingdom(BHD)",
    "Belize/BELIZE, Belize(BZE)",
    "Bellingham/BELLINGHAM, United States(BLI)",
    "Belo Horizonte/BELO HORIZONTE, Brazil(CNF)",
    "Benbecula/BENBECULA, United Kingdom(BEB)",
    "Benghazi/BENGHAZI, Libyan Arab Jamahiriya(BEN)",
    "Benito Sales Airport/NEIVA, Colombia(NVA)",
    "Bergen/BERGEN, Norway(BGO)",
    "Berlin Schonefeld/BERLIN, Germany(SXF)",
    "Berlin Tempelhof/BERLIN, Germany(THF)",
    "Berlin/Tegel/BERLIN, Germany(TXL)",
    "Bermuda/BERMUDA, Bermuda(BDA)",
    "Berne Belp/BERNE, Switzerland(BRN)",
    "Bethel Municipal Apt/BETHEL, United States(BET)",
    "Bhavnagar/BHAVNAGAR, India(BHU)",
    "Bhopal/BHOPAL, India(BHO)",
    "Bhubaneswar/BHUBANESWAR, India(BBI)",
    "Bhuj/BHUJ, India(BHJ)",
    "Bilbao/BILBAO, Spain And Canary Islands(BIO)",
    "Billings/BILLINGS, United States(BIL)",
    "Billund/BILLUND, Denmark(BLL)",
    "Binghamton/BINGHAMTON, United States(BGM)",
    "Bintulu/BINTULU, Malaysia(BTU)",
    "Birmingham Intl Uk/BIRMINGHAM, United Kingdom(BHX)",
    "Birmingham Usa/BIRMINGHAM, United States(BHM)",
    "Bishkek/FRUNZE, Kyrgstan(FRU)",
    "Bismarck/BISMARCK, United States(BIS)",
    "Blackpool/BLACKPOOL, United Kingdom(BLK)",
    "Blackwater/BLACKWATER, Australia(BLT)",
    "Blagoveshchensk/BLAGOVESHCHENSK, Russian Federation(BQS)",
    "Blenheim/BLENHEIM, New Zealand(BHE)",
    "Bloomington - Nromal/BLOOMINGTON-NORMAL, United States(BMI)",
    "Bodo/BODO, Norway(BOO)",
    "Bodrum/BODRUM, Turkey(BJV)",
    "Bogota/BOGOTA, Colombia(BOG)",
    "Boise/BOISE, United States(BOI)",
    "Bologna/BOLOGNA, Italy(BLQ)",
    "Bonaire/BONAIRE, Netherlands Antilles(BON)",
    "Bordeaux/BORDEAUX, France(BOD)",
    "Boston/BOSTON, United States(BOS)",
    "Bourgas/BOURGAS, Bulgaria(BOJ)",
    "Bournemouth/BOURNEMOUTH, United Kingdom(BOH)",
    "Bozeman/BOZEMAN, United States(BZN)",
    "Bradenton/BRADENTON, United States(SRQ)",
    "Brasilia/BRASILIA, Brazil(BSB)",
    "Bratislava/BRATISLAVA, Slovakia(BTS)",
    "Bratsk/BRATSK, Russian Federation(BTK)",
    "Braunschweig/BRAUNSCHWEG, Germany(BWE)",
    "Bremen/BREMEN, Germany(BRE)",
    "Brest/BREST, France(BES)",
    "Bridgeport/BRIDGEPORT, United States(BDR)",
    "Bridgetown/BARBADOS, Barbados(BGI)",
    "Brindisi/BRINDISI, Italy(BDS)",
    "Brisbane/BRISBANE, Australia(BNE)",
    "Bristol/BRISTOL, United Kingdom(BRS)",
    "Brive - La - Gaillarde/BRIVE-LA-GAIL, France(BVE)",
    "Broome/BROOME, Australia(BME)",
    "Brownsville/BROWNSVILLE, United States(BRO)",
    "Brussels/BRUSSELS, Belgium(BRU)",
    "Bucaramanga/BUCARAMANGA, Colombia(BGA)",
    "Bucharest/Baneasa/BUCHAREST, Romania(BBU)",
    "Bucharest/Otopeni/BUCHAREST, Romania(OTP)",
    "Budapest/Ferihegy/BUDAPEST, Hungary(BUD)",
    "Buenos Aires Airport/BUENOS AIRES, Argentina(BUE)",
    "Buenos Aires, Argentina/BUENOS AIRES, Argentina(AEP)",
    "Buffalo/BUFFALO, United States(BUF)",
    "Bundaberg/BUNDABERG, Australia(BDB)",
    "Burbank/LOS ANGELES, United States(BUR)",
    "Burlington Intl/BURLINGTON VT, United States(BTV)",
    "Burlington Municipal/BURLINGTON, United States(BRL)",
    "Burnie/BURNIE, Australia(BWT)",
    "Busan/BUSAN, Korea, Republic Of(PUS)",
    "Butte/BUTTE, United States(BTM)",
    "Cagliari Elmas Italy/CAGLIARI, Italy(CAG)",
    "Cairns/CAIRNS, Australia(CNS)",
    "Cairo/CAIRO, Egypt(CAI)",
    "Cajamarca/CAJAMARCA, Peru(CJA)",
    "Calama/CALAMA, Chile(CJC)",
    "Calgary/CALGARY, Canada(YYC)",
    "Cali/CALI, Colombia(CLO)",
    "Calicut/CALICUT, India(CCJ)",
    "Calvi/CALVI, France(CLY)",
    "Cam Grande/CAM GRANDE, Brazil(CGR)",
    "Camilo Daza Intl Apt/CUCUTA, Colombia(CUC)",
    "Campbeltown/CAMPBELTOWN, United Kingdom(CAL)",
    "Canberra/CANBERRA, Australia(CBR)",
    "Cancun/CANCUN, Mexico(CUN)",
    "Canouan Island/CANOUAN ISLAND, Saint Vincent And The Grenadines(CIW)",
    "Cap Haitien/CAP HAITIEN, Haiti(CAP)",
    "Cape Girardeau Municipal/CAPE GIRARDEAU, United States(CGI)",
    "Cape Town/CAPE TOWN, South Africa(CPT)",
    "Caracas/CARACAS, Venezuela(CCS)",
    "Cardiff/CARDIFF, United Kingdom(CWL)",
    "Carlsbad/CARLSBAD CA, United States(CLD)",
    "Cartagena/CARTAGENA, Colombia(CTG)",
    "Casablanca Anfa/CASABLANCA, Morocco(CAS)",
    "Casablanca Mohamed V/CASABLANCA, Morocco(CMN)",
    "Castres/CASTRES, France(DCM)",
    "Catania/CATANIA, Italy(CTA)",
    "Cayenne/CAYENNE, French Guiana(CAY)",
    "Cebu/CEBU, Philippines(CEB)",
    "Cedar Rapids/CEDAR RAPI, United States(CID)",
    "Chambery/CHAMBERY, France(CMF)",
    "Champaign/CHAMPAIGN, United States(CMI)",
    "Chandigarh/CHANDIGARH, India(IXC)",
    "Changchun/CHANGCHUN, China(CGQ)",
    "Changsha/CHANGSHA, China(CSX)",
    "Changzhi/CHANGZHI, China(CIH)",
    "Changzhou/CHANGZHOU, China(CZX)",
    "Chania/CHANIA, Greece(CHQ)",
    "Chaoyang/CHAOYANG, China(CHG)",
    "Charleston Municipal/CHARLESTON SC, United States(CHS)",
    "Charleston Yeager/CHARLESTON WV, United States(CRW)",
    "Charleville/CHARLEVIL, Australia(CTL)",
    "Charlotte/CHARLOTTE, United States(CLT)",
    "Charlottesville/CHARLOTTES, United States(CHO)",
    "Chattanooga/CHATTANOOG, United States(CHA)",
    "Cheju/JEJU, Korea, Republic Of(CJU)",
    "Chelyabinsk/CHELYABINSK, Russian Federation(CEK)",
    "Chengdu/Shuangliu/CHENGDU, China(CTU)",
    "Chennai/CHENNAI, India(MAA)",
    "Cheong Ju City/CHEONG JU CITY, Korea, Republic Of(CJJ)",
    "Chetumal/CHETUMAI, Mexico(CTM)",
    "Chiang Mai/CHIANG MAI, Thailand(CNX)",
    "Chiang Rai/CHIANG RAI, Thailand(CEI)",
    "Chicago/O&acute;Hare Intl/CHICAGO, United States(ORD)",
    "Chiclayo/CHICLAYO, Peru(CIX)",
    "Chifeng/CHIFENG, China(CIF)",
    "Chihuahua/CHIHUAHUA, Mexico(CUU)",
    "Chillan/CHILLAN, Chile(YAI)",
    "Chimkent/CHIMKENT, Kazakhstan(CIT)",
    "Chita/CHITA, Russian Federation(HTA)",
    "Chongqing/CHONGQING, China(CKG)",
    "Christchurch/CHRISTCHURCH, New Zealand(CHC)",
    "Cincinnati/CINCINNATI, United States(CVG)",
    "Ciudad Del Carmen/CIUDAD DEL CARMEN, Mexico(CME)",
    "Ciudad Pred Stroessner/CIUDAD D ESTE, Paraguay(AGT)",
    "Clark/Luzon Island/CLARK/LUZON ISLAND, Philippines(CRK)",
    "Clermont-Ferrand/CLERMONT-FERRAND, France(CFE)",
    "Cleveland Hopkins/CLEVELAND, United States(CLE)",
    "Cochin/COCHIN, India(COK)",
    "Coffs Harbour/COFFS HARBOUR, Australia(CFS)",
    "Coimbatore/COIMBATORE, India(CJB)",
    "College Station/COLLEGE STATION, United States(CLL)",
    "Cologne/COLOGNE, Germany(CGN)",
    "Colombo/Katunayake/COLOMBO, Sri Lanka(CMB)",
    "Colorado Springs/COLORADO SPRINGS, United States(COS)",
    "Columbia Metropolitan Apt/COLUMBIA SC, United States(CAE)",
    "Columbia Regional/COLUMBIA MO, United States(COU)",
    "Columbus/COLUMBUS OH, United States(CMH)",
    "Columbus Metroplitan Apt/COLUMBIA GA, United States(CSG)",
    "Comodoro Rivadavia/COMODORO RIVA, Argentina(CRD)",
    "Concepcion/CONCEPCION, Chile(CCP)",
    "Coolangatta/Gold Coast/COOLANGATTA/GOLD COAST, Australia(OOL)",
    "Copenhagen/COPENHAGEN, Denmark(CPH)",
    "Copiapo/COPIAPO, Chile(CPO)",
    "Cordoba/CORDOBA, Argentina(COR)",
    "Cordova Mudhole Smith Apt/CORDOVA, United States(CDV)",
    "Cork/CORK, Ireland(ORK)",
    "Corpus Christi/CORPUS CHRISTI, United States(CRP)",
    "Coventry/COVENTRY, United Kingdom(CVT)",
    "Cozumel/COZUMEL, Mexico(CZM)",
    "Cuenca/CUENCA, Spain And Canary Islands(CUE)",
    "Cuiaba/CUIBA, Brazil(CGB)",
    "Culiacan/CULIACAN, Mexico(CUL)",
    "Cullaton Lake/YUN CHENG, China(YCU)",
    "Curacao/CURACAO, Netherlands Antilles(CUR)",
    "Curitiba/CURITIBA, Brazil(CWB)",
    "Cushing/CUSHING, United States(CUH)",
    "Cuzco/CUSCO, Peru(CUZ)",
    "Dakar/DAKAR, Senegal(DKR)",
    "Dalaman/DALAMAN, Turkey(DLM)",
    "Dali City/DALI CITY, China(DLU)",
    "Dalian/DALIAN, China(DLC)",
    "Dallas/Fort Worth/DALLAS/FORTWORTH, United States(DFW)",
    "Damascus Intl/DAMASCUS, Syrian Arab Republic(DAM)",
    "Dammam King Fahd Intl/DAMMAM, Saudi Arabia(DMM)",
    "Danang/DA NANG, Vietnam(DAD)",
    "Dandong/DANDONG, China(DDG)",
    "Daocheng Yading Airport/DAOCHENG, China(DCY)",
    "Daqing/DAQING, China(DQA)",
    "Dar Es Salaam/DAR ES SALAAM, Tanzania, United Republic(DAR)",
    "Darwin/DARWIN, Australia(DRW)",
    "Datong/DATONG, China(DAT)",
    "Daxian/DAXIAN, China(DAX)",
    "Dayong/DAYONG, China(DYG)",
    "Dayton/DAYTON, United States(DAY)",
    "Daytona Beach/DAYTONA BEACH, United States(DAB)",
    "Decatur/DECATUR, United States(DEC)",
    "Dehradun/DEHRA DUN, India(DED)",
    "Delhi/DELHI, India(DEL)",
    "Denver/DENVER, United States(DEN)",
    "Der-Muenster/MUENSTER, Germany(FMO)",
    "Des Moines/DES MOINES, United States(DSM)",
    "Detroit/Metropolitan/DETROIT, United States(DTW)",
    "Devonport/DEVONPORT, Australia(DPO)",
    "Dhahran/DHAHRAN, Saudi Arabia(DHA)",
    "Dhaka/DHAKA, Bangladesh(DAC)",
    "Dili/DILI, Indonesia(DIL)",
    "Dillingham/DILLINGHAM, United States(DLG)",
    "Dimapur/DIMAPUR, India(DMU)",
    "Diqing/DIQING, China(DIG)",
    "Diu/DIU, India(DIU)",
    "Djerba/DJERBA, Tunisia(DJE)",
    "Djibouti/DJIBOUTI, Djibouti(JIB)",
    "Doha/DOHA, Qatar(DOH)",
    "Dominica/DOMINICA, Dominica(DOM)",
    "Donegal/CARRICKFINN, Ireland(CFN)",
    "Dongsheng/DONGSHENG, China(DSN)",
    "Dongying/DONGYING, China(DOY)",
    "Dortmund/DORTMUND, Germany(DTM)",
    "Dresden/DRESEDN, Germany(DRS)",
    "Dubai/DUBAI, United Arab Emirates(DXB)",
    "Dubbo/DUBBO, Australia(DBO)",
    "Dublin/DUBLIN, Ireland(DUB)",
    "Dubrovnik/DUBROVNIK, Croatia(DBV)",
    "Dubuque/DUBUQUE, United States(DBQ)",
    "Duluth/DULUTH, United States(DLH)",
    "Dunedin/DUNEDIN, New Zealand(DUD)",
    "Dunhuang/DUNHUANG, China(DNH)",
    "Durango/DURANGO, United States(DRO)",
    "Durban/DURBAN, South Africa(DUR)",
    "Dushanbe/DUSHANBE, Tadjikistan(DYU)",
    "Dusseldorf/DUSSELDORF, Germany(DUS)",
    "Dutch Harbour/DUTCH HARB, United States(DUT)",
    "Easter Island/EASTER ISLAND, Chile(IPC)",
    "Eceport Regional Apt/SHREVEPORT, United States(SHV)",
    "Eday/EDAY ISLAND, United Kingdom(EOI)",
    "Edinburgh/EDINBURGH, United Kingdom(EDI)",
    "Edmonton/EDMONTON, Canada(YEG)",
    "Eindhoven Airport/EINDHOVEN, Netherlands(EIN)",
    "El Alcaravan Airport/EL YOPAL, Colombia(EYP)",
    "El Calafate/EL CALAFATE, Argentina(FTE)",
    "El Carano Apt/QUIBDO, Colombia(UIB)",
    "El Paso/EL PASO, United States(ELP)",
    "El Salvador/EL SALVADOR, Chile(ESR)",
    "Elmira Corning/CORNING, United States(ELM)",
    "Emerald/EMERALD, Australia(EMD)",
    "Enfidha/ENFIDHA, Tunisia(NBE)",
    "Enontekio/ENONTEKIO, Finland(ENF)",
    "Enrique Olaya Herrera Apt/MEDELLIN, Colombia(EOH)",
    "Enshi/ENSHI, China(ENH)",
    "Entebbe/ENTEBBE, Uganda(EBB)",
    "Erbil/ERBIL, Iraq(EBL)",
    "Erfurt/ERFURT, Germany(ERF)",
    "Erie/ERIE, United States(ERI)",
    "Esbjerg Airport/ESBJERG, Denmark(EBJ)",
    "Esfahan/ISFAHAN, Iran (Islamic Republic Of)(IFN)",
    "Eugene/EUGENE, United States(EUG)",
    "Euroairport/BASLE, Switzerland(EAP)",
    "Evansville/EVANSVILLE, United States(EVV)",
    "Exeter/EXETER, United Kingdom(EXT)",
    "Fair Isle/FAIR ISLE, United Kingdom(FIE)",
    "Fairbanks/FAIRBANKS, United States(FAI)",
    "Faisalabad/FAISALABAD, Pakistan(LYP)",
    "Fargo/FARGO, United States(FAR)",
    "Faro/FARO, Portugal(FAO)",
    "Faroe Islands/FAROE ISLAND, Denmark(FAE)",
    "Fayetteville/FAYETTEVI, United States(FYV)",
    "Fayetteville Municipal Apt/FAYETTEVIL, United States(FAY)",
    "Fayetteville Northwest/FAYETTEVI, United States(XNA)",
    "Fergana/FERGANA, Uzbekistan(FEG)",
    "Figari/FIGARI CORSIC, France(FSC)",
    "Fiji Nandi International/NADI/FIJI, Fiji(NAN)",
    "Flint/FLINT, United States(FNT)",
    "Florence/FLORENCE SC, United States(FLO)",
    "Florence Amerigo Vespucci/FLORENCE, Italy(FLR)",
    "Florianopolis H Luz/FLORIANOPOLIS H LUZ, Brazil(FLN)",
    "Forli/FORLI, Italy(FRL)",
    "Fort De France/FT DE FRANCE, Martinique(FDF)",
    "Fort Lauderdale/FORT LAUDERDALE, United States(FLL)",
    "Fort Leonard Wood Forney/FORT LEONARD WOOD, United States(TBN)",
    "Fort Meyers/FT MYERS, United States(FMY)",
    "Fort Myers/FT MYERS, United States(RSW)",
    "Fort Smith Municipal/FT SMITH, United States(FSM)",
    "Fort Walton Beach/EGLIN AIR FORCE BASE, United States(VPS)",
    "Fort Wayne/FORT WAYNE, United States(FWA)",
    "Fortaleza/FORTALEZA, Brazil(FOR)",
    "Foula/FOULA, Italy(FOA)",
    "Frankfurt/FRANKFURT, Germany(FRA)",
    "Freeport/FREEPORT, Bahamas(FPO)",
    "Freetown Lungi Intl Apt/FREETOWN, Sierra Leone(FNA)",
    "Fresno/FRESNO, United States(FAT)",
    "Friedrichshafen/FRIEDRICHSHAF, Germany(FDH)",
    "Fu Zhou/FUZHOU, China(FOC)",
    "Fuerteventura/FUERTEVENTURA, Spain And Canary Islands(FUE)",
    "Fukuoka/FUKUOKA, Japan(FUK)",
    "Fukushima/FUKUSHIMA, Japan(FKS)",
    "Funchal/FUNCHAL, Portugal(FNC)",
    "Fuyang/FUYANG, China(FUG)",
    "Gaborone Sir Seretse Khama/GABORONE, Botswana(GBE)",
    "Gainesville/GAINESVILLE, United States(GNV)",
    "Galapagos/GALAPAGOS, Ecuador(GPS)",
    "Galapagos San Cristobal/GALAPAGOS, Ecuador(SCY)",
    "Galway/GALWAY, Ireland(GWY)",
    "Gander/GANDER, Canada(YQX)",
    "Ganzhou/GANZHOU, China(KOW)",
    "Ganzhou/ZHANGYE, China(YZY)",
    "Garden City/GARDEN CITY KS, United States(GCK)",
    "Gare De Valence Tgv/VALENCE, France(XHK)",
    "Gassim/GASSIM, Saudi Arabia(ELQ)",
    "Gauhati/GAWAHATI, India(GAU)",
    "Gazipasa/GAZIPASA, Turkey(GZP)",
    "Gbadolite/GBADOLITE, Zaire(BDT)",
    "Gdansk/GDANSK, Poland(GDN)",
    "Geilo/GEILO, Norway(DLD)",
    "Gen Mitchell Intl/MILWAUKEE, United States(MKE)",
    "Geneva/GENEVA, Switzerland(GVA)",
    "Genova/GENOA, Italy(GOA)",
    "George/GEORGE, South Africa(GRJ)",
    "George Town/GEORGE TOWN, Bahamas(GGT)",
    "Geraldton/GERALDTOWN, Australia(GET)",
    "Gerona/GERONA, Spain And Canary Islands(GRO)",
    "Gibraltar/GIBRALTAR, Gibraltar(GIB)",
    "Ginbata Airpor/JIMBLEBAR MINE, Australia(GBW)",
    "Gladstone/GLADSTONE, Australia(GLT)",
    "Glasgow/GLASGOW, United Kingdom(GLA)",
    "Goa/GOA, India(GOI)",
    "Goiania/GOIANIA, Brazil(GYN)",
    "Golmud/GOLMUD, China(GOQ)",
    "Goteborg/Landvetter/GOTHENBURG, Sweden(GOT)",
    "Gove/GOVE, Australia(GOV)",
    "Grafton/GRAFTON, Australia(GFN)",
    "Granada/GRANADA, Spain And Canary Islands(GRX)",
    "Grand Canyon Pulliam Field/GRAND CANYON, United States(FLG)",
    "Grand Cayman/GRAND CAYMAN, Caynan Islands(GCM)",
    "Grand Island Army Airfield/GRAND ISLAND, United States(GRI)",
    "Grand Junction/GRAND JUNCTION, United States(GJT)",
    "Grand Rapids/GRAND RAPIDS MI, United States(GRR)",
    "Graz/GRAZ, Austria(GRZ)",
    "Great Falls Intl Apt/GREAT FALLS, United States(GTF)",
    "Green Bay/GREEN BAY, United States(GRB)",
    "Greensboro/GREENSBORO, United States(GSO)",
    "Greenville/GREENVILLE SC, United States(GSP)",
    "Grenada/GRENOBLE, France(GND)",
    "Grenoble/GRENOBLE, France(GNB)",
    "Greville/GREENVILLE NC, United States(PGV)",
    "Guadalajara/GUADALAJARA, Mexico(GDL)",
    "Guam/GUAM, Guam(GUM)",
    "Guang Yuan/GUANG YUAN, China(GYS)",
    "Guangzhou(Canton)/GUANGZHOU, China(CAN)",
    "Guatemala City/GUATEMALA CTY, Guatemala(GUA)",
    "Guayaguil/GUAYAQUIL, Ecuador(GYE)",
    "Guernsey/GUERNSEY, United Kingdom(GCI)",
    "Guilin/GUILIN, China(KWL)",
    "Guiyang/GUIYANG, China(KWE)",
    "Gulfport Biloxi/GULFPORT, United States(GPT)",
    "Gunnison/GUNNISON, United States(GUC)",
    "Gustavo Rojas Pinilla/SAN ANDRES, Colombia(ADZ)",
    "Gyoumri/GYOUMRI, Armenia(LWN)",
    "Haikou/HAIKOU, China(HAK)",
    "Hailar/HAILAR, China(HLD)",
    "Hakodate/HAKODATE, Japan(HKD)",
    "Halifax/HALIFAX, Canada(YHZ)",
    "Hamburg/HAMBURG, Germany(HAM)",
    "Hami Airport/HAMI, China(HMI)",
    "Hamilton/HAMILTON, New Zealand(HLZ)",
    "Hamilton Island/HAMILTON ISLAND, Australia(HTI)",
    "Hamilton Vic/HAMILTON, Australia(HLT)",
    "Handan/HANDAN, China(HDG)",
    "Haneda/TOKYO, Japan(HND)",
    "Hangzhou/Xiaoshan/HANGZHOU, China(HGH)",
    "Hanoi/HANOI, Vietnam(HAN)",
    "Hanover/HANOVER, Germany(HAJ)",
    "Hanzhong Airport/HANZHONG, China(HZG)",
    "Harare/HARARE, Zimbabwe(HRE)",
    "Hargeisa/HARGEISA, Somalia(HGA)",
    "Harigbury/Raleigh/HARIGBURY/RALEIGH, United States(HSB)",
    "Harligen/HARLINGEN, United States(HRL)",
    "Harrisburg Skyport Airport/HARRISBURG, United States(HAR)",
    "Hartford Bradley Intl/HARTFORD, United States(BDL)",
    "Hassi Messaou/HASSI MESSAOU, Algeria(HME)",
    "Havana/HAVANA, Cuba(HAV)",
    "Hayden Yampa Valley/STEAMBT SPRINGS, United States(HDN)",
    "Hayman Island/HAYMAN ISLAND, Australia(HIS)",
    "Hefei/HEFEI, China(HFE)",
    "Heihe/HEIHE, China(HEK)",
    "Helena/HELENA, United States(HLN)",
    "Helsinki/HELSINKI, Finland(HEL)",
    "Heraklion/HERAKLION, Greece(HER)",
    "Heringsdorf/HERINGSDORF, Germany(HDF)",
    "Hermosillo/HERMOSILLO, Mexico(HMO)",
    "Hervey Bay/HERVEY BAY, Australia(HVB)",
    "Hilo/HILO, United States(ITO)",
    "Hilton Head Island/HILTON HEAD, United States(HHH)",
    "Hiroshima/HIROSHIMA, Japan(HIJ)",
    "Hiroshima West/HIROSHIMA, Japan(HIW)",
    "Ho Chi Minh City/HO CHI MINH CITY, Vietnam(SGN)",
    "Hobart/HOBART, Australia(HBA)",
    "Hoedspruit/HOEDSPRUIT, South Africa(HDS)",
    "Hohhot/HOHHOT, China(HET)",
    "Hong Kong/HONG KONG, Hong Kong,SAR(HKG)",
    "Hongyuan/HONGYUAN, China(AHJ)",
    "Honolulu/HONOLULU HI, United States(HNL)",
    "Horn Island/HORN ISLAND, Australia(HID)",
    "Hotan/HOTAN, China(HTN)",
    "Houston Ellington Field/HOUSTON, United States(EFD)",
    "Houston/Hobby/HOUSTON, United States(HOU)",
    "Houston/Intercontinental/HOUSTON, United States(IAH)",
    "Huaian/HUAIAN, China(HIA)",
    "Huanghua/Changsha, China(HHA)",
    "Huangyan/HUANGYAN, China(HYN)",
    "Huatulco/STA CRUZ HUAT, Mexico(HUX)",
    "Humberside/HUMBERSIDE, United Kingdom(HUY)",
    "Huntington/HUNTINGTON, United States(HTS)",
    "Huntsville/HUNTSVILLE, United States(HSV)",
    "Hurghada/HURGHADA, Egypt(HRG)",
    "Hyderabad/HYDERABAD, India(HYD)",
    "Iasi/IASI, Romania(IAS)",
    "Ibiza/IBIZA, Spain And Canary Islands(IBZ)",
    "Idaho Falls/IDAHO FALLS, United States(IDA)",
    "Iguassu Falls/IGUASSU FALLS, Brazil(IGU)",
    "Iguazu, Argentina/IGUAZU, Argentina(IGR)",
    "Ile Municipal Airport/MOBILE, United States(MOB)",
    "Ilheus/ILHEUS, Brazil(IOS)",
    "Imam Khomeini/TEHRAN, Iran (Islamic Republic Of)(IKA)",
    "Imperatriz Airport/IMPERATRIZ, Brazil(IMP)",
    "Incheon/SEOUL, Korea, Republic Of(ICN)",
    "Indianapolis/INDIANAPOLIS, United States(IND)",
    "Indore/INDORE, India(IDR)",
    "Innsbruck/INNSBRUCK, Austria(INN)",
    "Invercargill/INVERCARGILL, New Zealand(IVC)",
    "Inverness/INVERNESS, United Kingdom(INV)",
    "Ioannies Kapodistrias/CORFU, Greece(CFU)",
    "Iquique/IQUIQUE, Chile(IQQ)",
    "Iquitos/IQUITOS, Peru(IQT)",
    "Irkutsk/IRKUTSK, Russian Federation(IKT)",
    "Ishigaki/ISHIGAKI, Japan(ISG)",
    "Islamabad/ISLAMABAD, Pakistan(ISB)",
    "Islay/ISLAY, United Kingdom(ILY)",
    "Isle Of Man/ISLE OF MAN, United Kingdom(IOM)",
    "Islip/ISLIP, United States(ISP)",
    "Istanbul/ISTANBUL, Turkey(IST)",
    "Itami/OSAKA, Japan(ITM)",
    "Ithaca/ITHACA, United States(ITH)",
    "Ivalo/IVALO, Finland(IVL)",
    "Ixtapa/Zihuatanejo/ZIHUATANEJO, Mexico(ZIH)",
    "Izumo/IZUMO, Japan(IZO)",
    "Jackson/JACKSON WY, United States(JAC)",
    "Jackson/JACKSON, United States(MKL)",
    "Jackson Thompson Field/JACKSON MS, United States(JAN)",
    "Jacksonville/JACKSONVILLE NC, United States(OAJ)",
    "Jacksonville International/JACKSONVILLE FL, United States(JAX)",
    "Jaipur/JAIPUR, India(JAI)",
    "Jakarta/JAKARTA, Indonesia(CGK)",
    "Jammu/JAMMU, India(IXJ)",
    "Jeddah/King Abdul Aziz Intl/JEDDAH, Saudi Arabia(JED)",
    "Jerez De La Frontera/JEREZ DE LA FRONTERA, Spain And Canary Islands(XRY)",
    "Jersey/JERSEY, United Kingdom(JER)",
    "Ji An/Jing Gang Shan/JI AN/JING GANG SHAN, China(JGS)",
    "Jiagedaqi/JIAGEDAQI, China(JGD)",
    "Jiamusi/JIAMUSI, China(JMU)",
    "Jiayuquan/JIAYUGUAN, China(JGN)",
    "Jinan/JINAN, China(TNA)",
    "Jingdezhen/JINGDEZHEN, China(JDZ)",
    "Jinghong/JINGHONG, China(JHG)",
    "Jining/JINING, China(JNG)",
    "Jinjiang/JINJIANG, China(JJN)",
    "Jinzhou/JINZHOU, China(JNZ)",
    "Joa Pessoa/JOA PESSOA, Brazil(JPA)",
    "Jodhpur/JODHPUR, India(JDH)",
    "Joensuu/JOENSUU, Finland(JOE)",
    "Johannesburg/JOHANNESBURG, South Africa(JNB)",
    "Johor Baru/JOHOR BAHRU, Malaysia(JHB)",
    "Joinville/JOINVILLE, Brazil(JOI)",
    "Joplin Municipal/JOPLIN, United States(JLN)",
    "Jorhat/JORHAT, India(JRH)",
    "Juliaca/JULIACA, Peru(JUL)",
    "Juneau/JUNEAU, United States(JNU)",
    "Juzhow/JUZHOU, China(JUZ)",
    "Jyvaskyla/JYVASKYLA, Finland(JYV)",
    "Kagoshima/KAGOSHIMA, Japan(KOJ)",
    "Kahului/KAHULUI, United States(OGG)",
    "Kajaani/KAJAANI, Finland(KAJ)",
    "Kalamata/KALAMATA, Greece(KLX)",
    "Kalamazoo/KALAMAZOO, United States(AZO)",
    "Kalgoorlie/KALGOORLIE, Australia(KGI)",
    "Kaliningrad/KALININGRAD, Russian Federation(KGD)",
    "Kalispell/KALISPELL, United States(FCA)",
    "Kamenogorsk/UST-KAMENOGORSK, Kazakhstan(UKK)",
    "Kamloops/KAMLOOPS, Canada(YKA)",
    "Kangding/KANGDING, China(KGT)",
    "Kangerlussuaq/SONDRE STROMF, Greenland(SFJ)",
    "Kano/KANO, Nigeria(KAN)",
    "Kansas/KANSAS CITY DOWN TOWN, United States(MCI)",
    "Kansas City Downtown Apt/KANSAS CITY DOWN TOWN, United States(MKC)",
    "Kaohsiung(Gaoxiong)/KAOHSIUNG, Taiwan(KHH)",
    "Kaoma/KAOMA, Zambia(KMZ)",
    "Karachi/KARACHI, Pakistan(KHI)",
    "Karlsruhe/Baden/KARLSRUHE/BADEN, Germany(FKB)",
    "Karpathos/KARPATHOS, Greece(AOK)",
    "Karratha/KARRATHA, Australia(KTA)",
    "Kashi/KASHI, China(KHG)",
    "Kassel/KASSEL, Germany(KSF)",
    "Kathmandu/KATHMANDU, Nepal(KTM)",
    "Katowice/KATOWICE, Poland(KTW)",
    "Kauai Island/KAUAI ISLAND, United States(LIH)",
    "Kavala/KAVALA, Greece(KVA)",
    "Kayseri/KAYSERI, Turkey(ASR)",
    "Kazan/KAZAN, Russian Federation(KZN)",
    "Kefalhnia/KEFALLINIA, Greece(EFL)",
    "Kelowna/KELOWNA, Canada(YLW)",
    "Kemerovo/KEMEROVO, Russian Federation(KEJ)",
    "Kemi/Tornio/KEMI, Finland(KEM)",
    "Kempsey/KEMPSEY, Australia(KPS)",
    "Kerry Country/KERRY COUNTY, Ireland(KIR)",
    "Ketchikan/KETCHIKAN, United States(KTN)",
    "Key West/KEY WEST, United States(EYW)",
    "Khabarovsk/KHABAROVSK, Russian Federation(KHV)",
    "Khajuraho/HKAJURAHO, India(HJR)",
    "Khartoum/KHARTOUM, Sudan(KRT)",
    "Kiev/UKRAINE, Ukraine(KBP)",
    "Kigali/KIGALI, Rwanda(KGL)",
    "Kilimanjaro/KILIMANJARO, Tanzania, United Republic(JRO)",
    "Killeen/KILLEEN, United States(ILE)",
    "King Salmon/KING SALMON, United States(AKN)",
    "Kingscote/KINGSCOTE, Australia(KGC)",
    "Kingston/KINGSTON, Jamaica(KIN)",
    "Kirkenes/KIRKENES, Norway(KKN)",
    "Kirksville Municipal/KIRKSVILLE, United States(IRK)",
    "Kirkwall/KIRKWALL, United Kingdom(KOI)",
    "Kishinev/KISHIEV, Moldova, Republic Of(KIV)",
    "Kitchener/KITCHENER/WATERLOO, Canada(YKF)",
    "Kittila/KITTILA, Finland(KTT)",
    "Klagenfurt/KLAGENFURT, Austria(KLU)",
    "Klamath Falls/KLAMATH FALLS, United States(LMT)",
    "Knock/CONNAUGHT, Ireland(NOC)",
    "Knoxville/KNOXVILLE, United States(TYS)",
    "Kobe/KOBE, Japan(UKB)",
    "Kochi/KOCHI, Japan(KCZ)",
    "Kodiak Airport/KODIAK MUNICIPAL, United States(ADQ)",
    "Koh Samui/KOH SAMUI, Thailand(USM)",
    "Kokkola/Pietarsaari/KOKKOLA, Finland(KOK)",
    "Kokura/KITA KYUSHU, Japan(KKJ)",
    "Kolkata/KOLKATA, India(CCU)",
    "Komatsu/KOMATSU, Japan(KMQ)",
    "Kona/KONA, United States(KOA)",
    "Kopitnari/KUTAISI, Georgia(KUT)",
    "Korla/KORLA, China(KRL)",
    "Kos/KOS, Greece(KGS)",
    "Kota Kinabalu/KOTA KINABALU, Malaysia(BKI)",
    "Kotzebue/KOTZEBUE, United States(OTZ)",
    "Krabi/KRABI, Thailand(KBV)",
    "Krakow/KRAKOW, Poland(KRK)",
    "Krasnodar/KRASNODAR, Russian Federation(KRR)",
    "Krasnoyarsk/KRASNOYARSK, Russian Federation(KJA)",
    "Kruger Mpumalanga Nelspruit/NELSPRUIT, South Africa(MQP)",
    "Kuala Lumpur/KUALA LUMPUR, Malaysia(KUL)",
    "Kuala Namu Intl Airport/MEDAN, Indonesia(KNO)",
    "Kuala Terengganu/KUALA TERENGG, Malaysia(TGG)",
    "Kuantan/KUANTAN, Malaysia(KUA)",
    "Kuching/KUCHING, Malaysia(KCH)",
    "Kulob/KULOB, Tadjikistan(TJU)",
    "Kumamoto/KUMAMOTO, Japan(KMJ)",
    "Kume Jima/KUMEJIMA, Japan(UEO)",
    "Kunming Wujiaba/KUNMING, China(KMG)",
    "Kununurra/KUNUNURRA, Australia(KNX)",
    "Kuopio/KUOPIO, Finland(KUO)",
    "Kushiro/KUSHIRO, Japan(KUH)",
    "Kuusamo/KUUSAMO, Finland(KAO)",
    "Kuwait/KUWAIT, Kuwait(KWI)",
    "Kwanju/KWANGJU, Korea, Republic Of(KWJ)",
    "La Coruna/LA CORUNA, Spain And Canary Islands(LCG)",
    "La Crosse/LA CROSSE, United States(LSE)",
    "La Paz El Alto/LA PAZ, Bolivia(LPB)",
    "La Paz Leon/LA PAZ MEX, Mexico(LAP)",
    "La Rochelle/LA ROCHELLE, France(LRH)",
    "La Romana/LA ROMANA, Dominican Republic(LRM)",
    "La Serena/LA SERENA, Chile(LSC)",
    "Labuan/LABUAN, Malaysia(LBU)",
    "Lafayette Regional/LAFAYETTE LA, United States(LFT)",
    "Lafayette Usa/LAFAYETTE IN, United States(LAF)",
    "Lagos/LAGOS, Nigeria(LOS)",
    "Lahore/LAHORE, Pakistan(LHE)",
    "Lake Charles/LAKE CHARLES, United States(LCH)",
    "Lakselv/LAKSELV, Norway(LKL)",
    "Lamezia Terme/LAMEZIA-TERME, Italy(SUF)",
    "Lampang/LAMPANG, Thailand(LPT)",
    "Lanal City/LANAI, United States(LNY)",
    "Langkawi/LANGKAWI, Malaysia(LGK)",
    "Lannion/LANNION, France(LAI)",
    "Lansing/LANSING, United States(LAN)",
    "Lanzarote/Canary Island/LANZAROTE, Spain And Canary Islands(ACE)",
    "Lanzhou/LANZHOU, China(LHW)",
    "Lappeenranta/LAPPEENRANTA, Finland(LPP)",
    "Laredo/LAREDO, United States(LRD)",
    "Larnaca Intl/Nicosia/LARNACA, Cyprus(LCA)",
    "Las Palmas/GRAN CANARIA, Spain And Canary Islands(LPA)",
    "Las Vegas/LAS VEGAS, United States(LAS)",
    "Launceston/LAUNCESTON, Australia(LST)",
    "Laurel/Pine Belt Regional/LAUREL, United States(PIB)",
    "Lawton/LAWTON, United States(LAW)",
    "Learmonth/LEARMONTH, Australia(LEA)",
    "Leeds Bradford/LEEDS, United Kingdom(LBA)",
    "Leh/LEH, India(IXL)",
    "Leinster/LEINSTER, Australia(LER)",
    "Leipzig/LEIPZIG, Germany(LEJ)",
    "Leon/LEON, Spain And Canary Islands(LEN)",
    "Leon-Guanajuato/LEON GUANAJUATO, Mexico(BJX)",
    "Lewiston/LEWISTON, United States(LWS)",
    "Lexington Blue Grass Apt/LEXINGTON, United States(LEX)",
    "Lhasa/LHASA, China(LXA)",
    "Liancheng/LIANCHENG, China(LCX)",
    "Lianyungang/LIANYUNGANG, China(LYG)",
    "Liberia/LIBERIA, Costa Rica(LIR)",
    "Lijiang/LIJIANG, China(LJG)",
    "Lille Lesquin Airport/LILLE, France(LIL)",
    "Lille Rail Service/LILLE RAIL SERVICE, France(XDB)",
    "Lilongwe/LILONGWE, Malawi(LLW)",
    "Lima/LIMA, Peru(LIM)",
    "Lincang/LINCANG, China(LNJ)",
    "Lincoln/LINCOLN, United States(LNK)",
    "Lingling/YONGZHOU, China(LLF)",
    "Linyi/LINYI, China(LYI)",
    "Linz/LINZ, Austria(LNZ)",
    "Linzhi/LINZHI, China(LZY)",
    "Lisbon/LISBON, Portugal(LIS)",
    "Little Rock/LITTLE ROCK, United States(LIT)",
    "Liuzhou/LIUZHOU, China(LZH)",
    "Liverpool/LIVERPOOL, United Kingdom(LPL)",
    "Livingstone/LIVINGSTONE, Zambia(LVI)",
    "Ljubljana/LJUBLJANA, Slovenia(LJU)",
    "Logrono/LOGRONO, Spain And Canary Islands(RJL)",
    "London City Airport/LONDON, United Kingdom(LCY)",
    "London Luton Airport/LONDON, United Kingdom(LTN)",
    "London/Gatwick/LONDON, United Kingdom(LGW)",
    "London/Heathrow/LONDON, United Kingdom(LHR)",
    "London/Stansted/LONDON, United Kingdom(STN)",
    "Londonderry/LONDONDERRY, United Kingdom(LDY)",
    "Long Beach/LONG BEACH, United States(LGB)",
    "Longrina/LONGRINA, Brazil(LDB)",
    "Longview/LONGVIEW, United States(GGG)",
    "Longyearbyen/LONGYEARBYEN, Norway(LYR)",
    "Lord Howe Island/LORD HOWE ISLAND, Australia(LDH)",
    "Loreto/LORETO, Mexico(LTO)",
    "Los Angeles/LOS ANGELES, United States(LAX)",
    "Los Garzones Monteria/MONTERIA, Colombia(MTR)",
    "Louisville/LOUISVILLE, United States(SDF)",
    "Lourdes Tarbes/LOURDES/TARBE, France(LDE)",
    "Luanda/LUANDA, Angola(LAD)",
    "Luang Prabang/LUANG PRABANG, Lao People's Democratic Republic(LPQ)",
    "Lubbock/LUBBOCK, United States(LBB)",
    "Lucknow/LUCKNOW, India(LKO)",
    "Lugano/LUGANO, Switzerland(LUG)",
    "Luis Obispo/SAN LUIS, United States(SBP)",
    "Luoyang/LUOYANG, China(LYA)",
    "Lusaka/LUSAKA, Zambia(LUN)",
    "Luxembourg/LUXEMBOURG, Luxembourg(LUX)",
    "Luxi/LUXI, China(LUM)",
    "Luxor/LUXOR, Egypt(LXR)",
    "Luzhou/LUZHOU, China(LZO)",
    "Lynchburg/LYNCHBURG, United States(LYH)",
    "Lyon Part-Dieu Rail Station/LYON PART-DIEU RAIL STATION, France(XYD)",
    "Lyon Satolas Apt/LYON, France(LYS)",
    "Maastricht Aachen De Apt/MAASTRICHT, Netherlands(MST)",
    "Macapa Intl Airport/MACAPA, Brazil(MCP)",
    "Macau/MACAU, Macau, SAR(MFM)",
    "Maceio/MACEIO, Brazil(MCZ)",
    "Mackay/MACKAY, Australia(MKY)",
    "Madinah/MEDINA, Saudi Arabia(MED)",
    "Madison/MADISON, United States(MSN)",
    "Madrid/Barajas/MADRID, Spain And Canary Islands(MAD)",
    "Madurai/MADURAI, India(IXM)",
    "Magodan/MAGODAN, Russian Federation(GDX)",
    "Mahe Seychelles Intl/MAHE ISLAND, Seychelles(SEZ)",
    "Malabo/MALABO, Equatorial Guinea(SSG)",
    "Malaga/MALAGA, Spain And Canary Islands(AGP)",
    "Male Intl/Maldives/MALE, Maldives(MLE)",
    "Malta/MALTA, Malta(MLA)",
    "Mammoth Lakes Airport/MAMMOTH LAKES, United States(MMH)",
    "Managua/MANAGUA, Nicaragua(MGA)",
    "Manaus/MANAUS, Brazil(MAO)",
    "Manchester Municipal Usa/MANCHESTER, United States(MHT)",
    "Manchester Uk/MANCHESTER, United Kingdom(MAN)",
    "Mandalay/Annisaton/MANDALAY, Myanmar(MDL)",
    "Mangalore/MANGALORE, India(IXE)",
    "Manhattan/MANHATTAN, United States(MHK)",
    "Manila/MANILA, Philippines(MNL)",
    "Manzanillo/MANZANILLO, Mexico(ZLO)",
    "Manzhouli/MANZHOULI, China(NZH)",
    "Manzini/MANZINI, Swaziland(MTS)",
    "Maputo Intl/MAPUTO, Mozambique(MPM)",
    "Maraba Airport/MARABA, Brazil(MAB)",
    "Maracaibo/MARACAIBO, Venezuela(MAR)",
    "Marathon/MARATHON, United States(MTH)",
    "Maribor Int'L Airport/MARIBOR, Slovenia(MBX)",
    "Mariehamn/MARIEHAMN, Finland(MHQ)",
    "Marion/MARION, United States(MWA)",
    "Marquette Country Airport/MARQUETTE, United States(MQT)",
    "Marrakech/MARRAKECH, Morocco(RAK)",
    "Marsa Alam/MARSA ALAM, Egypt(RMF)",
    "Marseille/MARSEILLE, France(MRS)",
    "Marsh Harbour/MARSH HARBOUR, Bahamas(MHH)",
    "Maryborough/MARYBOROUGH, Australia(MBH)",
    "Mashad/MASHAD, Iran (Islamic Republic Of)(MHD)",
    "Matsumoto/MATSUMOTO, Japan(MMJ)",
    "Matsuyama/MATSUYAMA, Japan(MYJ)",
    "Mattala Rajapaksa Intl Apt/MATTALA RAJAPAKSA, Sri Lanka(HRI)",
    "Mauritius/MAURITIUS, Mauritus(MRU)",
    "Mayaguez/MAYAGUEZ, Puerto Rico(MAZ)",
    "Mazatlan/MAZATLAN, Mexico(MZT)",
    "Medan/Polonia/MEDAN, Indonesia(MES)",
    "Medellin/MEDELLIN, Colombia(MDE)",
    "Medford/MEDFORD, United States(MFR)",
    "Melbourne/MELBOURNE, Australia(MEL)",
    "Melbourne Beach/MELBOURNE BEACH, United States(MLB)",
    "Melilla/MELILLA, Spain And Canary Islands(MLN)",
    "Memanbetsu/MEMANBETSU, Japan(MMB)",
    "Memmingen/MEMMINGEN, Germany(FMM)",
    "Memphis/MEMPHIS, United States(MEM)",
    "Mendoza/MENDOZA, Argentina(MDZ)",
    "Menorca/MAHON, Spain And Canary Islands(MAH)",
    "Merida/MERIDA, Mexico(MID)",
    "Meridian/MERIDIAN, United States(MEI)",
    "Metz Nancy/METZ/NANCY, France(ETZ)",
    "Mexicall/MEXICALI, Mexico(MXL)",
    "Mexico/MEXICO CITY, Mexico(MEX)",
    "Miami/MIAMI, United States(MIA)",
    "Middletown/HARRISBURG, United States(MDT)",
    "Midi Railway Station/MIDI RAILWAY STATION, Belgium(ZYR)",
    "Midland/MIDLAND, United States(MAF)",
    "Midway-Chicago/CHICAGO, United States(MDW)",
    "Mihail Kogalniceanu/CONSTANTA, Romania(CND)",
    "Mikonos/MIKONOS, Greece(JMK)",
    "Milan Linate/MILAN, Italy(LIN)",
    "Milan Orio Serio/MILAN, Italy(BGY)",
    "Milan/Malpensa/MILAN, Italy(MXP)",
    "Mildura/MILDURA, Australia(MQL)",
    "Minatitlan/MINATITLAN, Mexico(MTT)",
    "Mineralnye Vody/MINERALNYE, Russian Federation(MRV)",
    "Ministro Pistarini/BUENOS AIRES, Argentina(EZE)",
    "Minniapolis/MINNEAPOL, United States(MSP)",
    "Minsk/MINSK, Belarus(MSQ)",
    "Minterrey/MONTERREY, Mexico(MTY)",
    "Miri/MIRI, Malaysia(MYY)",
    "Mirny/MIRNY, Russian Federation(MJZ)",
    "Misawa/MISAWA, Japan(MSJ)",
    "Mission/MC ALLEN, United States(MFE)",
    "Missoula/MISSOULA, United States(MSO)",
    "Miyako Jima/MIYAKO, Japan(MMY)",
    "Miyazaki/MIYAZAKI, Japan(KMI)",
    "Moline/MOLINE, United States(MLI)",
    "Mombasa/MOMBASA, Kenya(MBA)",
    "Monastir/MONASTIR, Tunisia(MIR)",
    "Monroe/MONROE, United States(MLU)",
    "Monrovia Roberts International/MONROVIA, Liberia(ROB)",
    "Monterey/MONTEREY, United States(MRY)",
    "Montevideo/MONTEVIDEO, Uruguay(MVD)",
    "Montgomery/MONTGOMERY, United States(MGM)",
    "Montpellier/MONTPELLIER, France(MPL)",
    "Montreal Mirabel/MONTREAL, Canada(YMX)",
    "Montreal/Dorval/MONTREAL, Canada(YUL)",
    "Montrose/MONTROSE, United States(MTJ)",
    "Moranbah/MORANBAH, Australia(MOV)",
    "Moree/MOREE, Australia(MRZ)",
    "Morelia/MORELIA, Mexico(MLM)",
    "Morikora/MORIOKA, Japan(HNA)",
    "Moscow Domodedovo Airport/MOSCOW, Russian Federation(DME)",
    "Moscow/Sheremetyevo/MOSCOW, Russian Federation(SVO)",
    "Moscow/Vnukovo/MOSCOW, Russian Federation(VKO)",
    "Mosinee/WAUSAU, United States(CWA)",
    "Motego Bay/MONTEGO BAY, Jamaica(MBJ)",
    "Mount Isa/MOUNT ISA, Australia(ISA)",
    "Mount Keith/MOUNT KEITH, Australia(WME)",
    "Mount Pleasant/MOUNT PLEASANT, Falkland Islands(MPN)",
    "Muan/MUAN, Korea, Republic Of(MWX)",
    "Mudanjiang/MUDANJIANG, China(MDG)",
    "Multan/MULTAN, Pakistan(MUX)",
    "Mumbai/MUMBAI, India(BOM)",
    "Munich/MUNICH, Germany(MUC)",
    "Munich Neubiberg Ab/MIAN YANG, China(MIG)",
    "Murica/MURCIA, Spain And Canary Islands(MJV)",
    "Murmansk/MURMANSK, Russian Federation(MMK)",
    "Muscat/MUSCAT, Oman(MCT)",
    "Myrtle Beach Afb/MYRTLE BEACH, United States(MYR)",
    "Mytilene/MYTILENE, Greece(MJT)",
    "Nador/NADOR, Morocco(NDR)",
    "Nadym/NADYM, Russian Federation(NYM)",
    "Nagasaki/NAGASAKI, Japan(NGS)",
    "Nagoya Chubu Centrair/NAGOYA, Japan(NGO)",
    "Nagoya Komaki Airport/NAGOYA, Japan(NKM)",
    "Nagpur/NAGPUR, India(NAG)",
    "Nairobi/NAIROBI, Kenya(NBO)",
    "Najaf/NAJAF, Iraq(NJF)",
    "Nanchang/NANCHANG, China(KHN)",
    "Nanchong/NANCHONG, China(NAO)",
    "Nanjing/NANJING, China(NKG)",
    "Nanki-Shirahama/SHIRAHAMA, Japan(SHM)",
    "Nanning Wuxu/NANNING, China(NNG)",
    "Nantes Atlantique Airport/NANTES, France(NTE)",
    "Nantong/NANTONG, China(NTG)",
    "Nantucket/NANTUCKET, United States(ACK)",
    "Naples/NAPLES, United States(APF)",
    "Naples/Capodichino Mil/NAPLES, Italy(NAP)",
    "Narrabri/NARRABRI, Australia(NAA)",
    "Nashville/NASHVILLE, United States(BNA)",
    "Nassau/NASSAU, Bahamas(NAS)",
    "Natal/NATAL, Brazil(NAT)",
    "Nates Rail Station/NANTES RAILWAY STATION, France(QJZ)",
    "Navegantes/NAVEGANTES, Brazil(NVT)",
    "Nay Pyi Daw Airport/NAY PYI TAW, Myanmar(NYT)",
    "Ndola/NDOLA, Zambia(NLA)",
    "Nelson/NELSON, New Zealand(NSN)",
    "Neuquen/NEUQUEN, Argentina(NQN)",
    "New Bern/NEW BERN, United States(EWN)",
    "New Haven/NEW HAVEN, United States(HVN)",
    "New Orleans/NEW ORLEANS, United States(MSY)",
    "New York/J.F. Kennedy/NEW YORK, United States(JFK)",
    "New York/La Guardia/NEW YORK, United States(LGA)",
    "New York/Newark Intl/NEW YORK, United States(EWR)",
    "Newburge/NEWBURGH, United States(SWF)",
    "Newcastle Airport/Nevis Island/NEVIS, Saint Kitts And Nevis(NEV)",
    "Newcastle Uk/NEWCASTLE, United Kingdom(NCL)",
    "Newman/NEWMAN, Australia(ZNE)",
    "Newport News/NEWPOER NEW HAMP, United States(PHF)",
    "Newquay/NEWQUAY, United Kingdom(NQY)",
    "Nice/NICE, France(NCE)",
    "Niigata/NIIGATA, Japan(KIJ)",
    "Nimes/NIMES, France(FNI)",
    "Ningbo/NINGBO, China(NGB)",
    "Nizhnekamsk/NIZHNEKAMSK, Russian Federation(NBC)",
    "Nizhnevartovsk/NIZHNEVARTOVSK, Russian Federation(NJC)",
    "Nizhniy Novogorod/NIZHNIY NOVGOROD, Russian Federation(GOJ)",
    "Nome/NOME, United States(OME)",
    "Norfolk/NORFOLK VA, United States(ORF)",
    "Norfolk/QUERETARO, United States(ORF)",
    "Norilsk/NORILSK, Russian Federation(NSK)",
    "North Bend/NORTH BEND, United States(OTH)",
    "North Eleuthera/NORTH ELEUTHERA, United States(ELH)",
    "North Ronaldsay/N RONALDSAY, United Kingdom(NRL)",
    "Noumea/NOUMEA, New Caledonia(NOU)",
    "Novokuznetsk/NOVOKUZNETSK, Russian Federation(NOZ)",
    "Novosibirsk/NOVOSIBIRSK, Russian Federation(OVB)",
    "Novyj Urengoj/NOVYJ URENGOJ, Russian Federation(NUX)",
    "Nuevo Lavedo/NUEVO LAREDO, Mexico(NLD)",
    "Nurnberg/NUREMBERG, Germany(NUE)",
    "Oakland/OAKLAND, United States(OAK)",
    "Oaxaca/OAXACA, Mexico(OAX)",
    "Oberpfaffenhofen/OBERPFAFFENHO, Germany(OBF)",
    "Obihiro/OBIHIRO, Japan(OBO)",
    "Odense Airport/ODENSE, Denmark(ODE)",
    "Odessa/ODESSA, Ukraine(ODS)",
    "Oita/OITA, Japan(OIT)",
    "Okalahoma/OKLAHOMA CITY, United States(OKC)",
    "Okayama/OKAYAMA, Japan(OKJ)",
    "Oki Island/OKI ISLAND, Japan(OKI)",
    "Okinawa Naha/OKINAWA, Japan(OKA)",
    "Olbia/OLBIA, Italy(OLB)",
    "Old Harbour/OLD HARBOR, United States(OLH)",
    "Olympic Dam/OLYMPIC DAM, Australia(OLP)",
    "Omaha/OMAHA, United States(OMA)",
    "Omsk/OMSK, Russian Federation(OMS)",
    "Ontario/ONTARIO CA, United States(ONT)",
    "Orenburg Tsentralny/ORENBURG, Russian Federation(REN)",
    "Orlando Herndon Airport/ORLANDO, United States(ORL)",
    "Orlando/International/ORLANDO, United States(MCO)",
    "Osaka/Kansai/OSAKA, Japan(KIX)",
    "Osh/OSH, Kazakhstan(OSS)",
    "Oslo Airport/OSLO, Norway(OSL)",
    "Osorno/OSORNO, Chile(ZOS)",
    "Ottawa/OTTAWA, Canada(YOW)",
    "Oulu/OULU, Finland(OUL)",
    "Outer Skerries/OUTER SKEERIES, United Kingdom(OUK)",
    "Oviedo/OVIEDO, United States(OVL)",
    "Owensboro/OWENSBORO, United States(OWB)",
    "Paderborn/PADERBORN, Germany(PAD)",
    "Paducah/PADUCAH, United States(PAH)",
    "Palermo/PALERMO, Italy(PMO)",
    "Palm Springs/PALM SPRINGS, United States(PSP)",
    "Palmas/PALMAS, Brazil(PMW)",
    "Palmerston North/PALMERSTON, New Zealand(PMR)",
    "Pamplona/PAMPLONA, Spain And Canary Islands(PNA)",
    "Pan Zhi Hua/PAN ZHI HUA, China(PZI)",
    "Panama City/PANAMA CITY, Panama(PTY)",
    "Papa Stour/PAPA STOUR, Brazil(PSV)",
    "Papa Westray/PAPA WESTRAY, United Kingdom(PPW)",
    "Papeete/Tahiti Faaa/PAPEETE, French Polynesia(PPT)",
    "Paphos/PAPHOS, Cyprus(PFO)",
    "Paraburdoo/PARABURDOO, Australia(PBO)",
    "Paris/Charles De Gaulle/PARIS, France(CDG)",
    "Paris/Orly/PARIS, France(ORY)",
    "Pasco/PASCO, United States(PSC)",
    "Patna/PATNA, India(PAT)",
    "Patras/PATRAS, Greece(GPA)",
    "Pavlodar/PAVLODAR, Kazakhstan(PWQ)",
    "Penang/PENANG, Malaysia(PEN)",
    "Pendleton/PENDLETON, United States(PDT)",
    "Pensacola Municipal Apt/PENSACOLA, United States(PNS)",
    "Perales Airport/IBAGUE, Colombia(IBE)",
    "Pereira/PEREIRA, Colombia(PEI)",
    "Perm/PERM, Russian Federation(PEE)",
    "Peroria/PERORIA, United States(PIA)",
    "Perpignan/PERPIGNAN, France(PGF)",
    "Perth/PERTH, Australia(PER)",
    "Peshawar/PESHAWAR, Pakistan(PEW)",
    "Petersburg/PETERSBURG, United States(PSG)",
    "Petropavlovsk/PETROPAVLOVSK-KAMCHATSKY, Russian Federation(PKC)",
    "Petrozavodsk/PETROPALOVSK, Russian Federation(PES)",
    "Philadelphia/PHILADELPHIA, United States(PHL)",
    "Phnom-Penh/PHNOM PENH, Cambodia(PNH)",
    "Phoenix/PHOENIX, United States(PHX)",
    "Phuket/PHUKET, Thailand(HKT)",
    "Pisa/PISA, Italy(PSA)",
    "Pittsburgh/PITTSBURGH, United States(PIT)",
    "Piura/PIURA, Peru(PIU)",
    "Plama Mallorca/PALMA MALLORC, Spain And Canary Islands(PMI)",
    "Plovdiv/PLOVDIV, Bulgaria(PDV)",
    "Plymouth/PLYMOUTH, United Kingdom(PLH)",
    "Pocatello/POCATELLO, United States(PIH)",
    "Pointe A Pitre/POINTE A PITRE, Guadeloupe(PTP)",
    "Poitiers/POITIERS, France(XOP)",
    "Poitiers Biard Airport/POITIERS, France(PIS)",
    "Ponta Delgada/PARNDANA, Portugal(PDL)",
    "Porbandar/PORBANDAR, India(PBD)",
    "Pori/PORI, Finland(POR)",
    "Port Angeles/PORT ANGELES, United States(CLM)",
    "Port Au Prince/PORT AU PRINC, Haiti(PAP)",
    "Port Blair/PORT BLAIR, India(IXZ)",
    "Port Elizabeth/PT ELIZABETH, South Africa(PLZ)",
    "Port Headland/PORT HEADLAND, Australia(PHE)",
    "Port Lincoln/PORT LINCOLN, Australia(PLO)",
    "Port Macquarie/PORT MACQUARIE, Australia(PQQ)",
    "Port Moresby/PORT MORESBY, Papua New Guinea(POM)",
    "Port Vila Vanuatu/PORT VILA, Vanuatu(VLI)",
    "Portland Intl Me Usa/PORTLAND ME, United States(PWM)",
    "Portland Intl Or Usa/PORTLAND OR, United States(PDX)",
    "Porto/PORTO, Portugal(OPO)",
    "Porto Alegre/PORTO ALEGRE, Brazil(POA)",
    "Porto Seguro Airport/PTO SEGURO, Brazil(BPS)",
    "Porto Velho/PORTO VELHO, Brazil(PVH)",
    "Poznan/POZNAN, Poland(POZ)",
    "Prague/PRAGUE, Czech Republic(PRG)",
    "Prescott/PRESCOTT, United States(PRC)",
    "Prestwick/GLASGOW, United Kingdom(PIK)",
    "Preveza/Lefkas/PREVEZA/LEFKA, Greece(PVK)",
    "Proserpine/PROSERPINE, Australia(PPP)",
    "Providence/PROVIDENCE, United States(PVD)",
    "Providenciales/PROVIDENCIALE, Turks And Caicos Islands(PLS)",
    "Prudhoe Bay/Deadhorse/DEADHORSE, United States(SCC)",
    "Pucallpa/PUCALLPA, Peru(PCL)",
    "Pucon/PUCON, Chile(ZPC)",
    "Puebla/PUEBLA, Mexico(PBC)",
    "Puerto Maldon/PUERTO MALDON, Peru(PEM)",
    "Puerto Monti/PUERTO MONTT, Chile(PMC)",
    "Puerto Plata/PUERTO PLATA, Dominican Republic(POP)",
    "Puerto Vallarta/PURETO VALLAR, Mexico(PVR)",
    "Pula/PULA, Croatia(PUY)",
    "Pullman/PULLMAN, United States(PUW)",
    "Pune/PUNE, India(PNQ)",
    "Punta Arenas/PUNTA ARENAS, Chile(PUQ)",
    "Punta Cana/PUNTA CANA, Dominican Republic(PUJ)",
    "Puoto Escond/PUERTO ESCOND, Mexico(PXM)",
    "Pyongyang/PYONGYANG, Korea, Democratic People's Republic(FNJ)",
    "Qingdao/QINGDAO, China(TAO)",
    "Qingshan/XICHANG, China(XIC)",
    "Qinhuangdao/QINHUANGDAO, China(SHP)",
    "Qiqihaer/QIQIHAR, China(NDG)",
    "Quebec Intl Airport/QUEBEC, Canada(YQB)",
    "Queenstown/QUEENSTOWN, New Zealand(ZQN)",
    "Queretaro/QUERETARO, Mexico(QRO)",
    "Quincy/QUINCY, United States(UIN)",
    "Quito/QUITO, Ecuador(UIO)",
    "Rabat/RABAT, United Kingdom(RBA)",
    "Raipur/RAIPUR, India(RPR)",
    "Rajahmundry/RAJAHMUNDRY, India(RJA)",
    "Rajkot/RAJKOT, India(RAJ)",
    "Raleigh/Durham/RALEIGH DURHAM, United States(RDU)",
    "Ranchi/RANCHI, India(IXR)",
    "Rangoon/YANGON, Myanmar(RGN)",
    "Rapid City Municipal Apt/RAPID CITY, United States(RAP)",
    "Ras Al Khaimah/RAS AL KHAIMA, United Arab Emirates(RKT)",
    "Rayong/Utapao/UTAPAO, Thailand(UTP)",
    "Recife/RECIFE, Brazil(REC)",
    "Red Wing/RED WING, United States(RGK)",
    "Redding/REDDING, United States(RDD)",
    "Redmond/REDMOND, United States(RDM)",
    "Rennes/RENNES, France(RNS)",
    "Reno/RENO, United States(RNO)",
    "Reus/REUS, Spain And Canary Islands(REU)",
    "Reykjavik Keflavik Airport/REYKJAVIK, Iceland(KEF)",
    "Reynosa/REYNOSA, Mexico(REX)",
    "Rhodos/RHODES, Greece(RHO)",
    "Ribeirao Preto/RIBEIRAO PRETO, Brazil(RAO)",
    "Richards Bay/RICHARDS BAY, South Africa(RCB)",
    "Richmond/RICHMOND, United States(RIC)",
    "Riga/RIGA, Latvia(RIX)",
    "Rijeka/RIJEKA, Croatia(RJK)",
    "Rikaze/RIKAZE, China(RKZ)",
    "Rimini/RIMINI, Italy(RMI)",
    "Rio Branco/RIO BRANCO, Brazil(RBR)",
    "Rio De Janeiro Intl/RIO DE JANEIRO, Brazil(GIG)",
    "Rio De Janeiro Santos Dumont/RIO DE JANEIRO, Brazil(SDU)",
    "Rio Gallegos/RIO GALLEGOS, Argentina(RGL)",
    "Riyadh/King Khalid/RIYADH, Saudi Arabia(RUH)",
    "Rnzaf Base Ohakea/BULLS NEW ZEALAND, New Zealand(OHA)",
    "Roanoke/ROANOKE, United States(ROA)",
    "Roatan/ROATAN, Honduras(RTB)",
    "Robert Grat Aaf/FT. HOOD REGIONAL, United States(GRK)",
    "Rochester Ny/ROCHESTER NY, United States(ROC)",
    "Rochester-Mn/ROCHESTER MN, United States(RST)",
    "Rockford Van Galder Stn/ROCKFORD VAN GALDER BUS STN, United States(ZRK)",
    "Rockhampton/ROCKHAMPTON, Australia(ROK)",
    "Rodez/RODEZ, France(RDZ)",
    "Roma/ROMA, Australia(RMA)",
    "Rome/Fiumicino/ROME, Italy(FCO)",
    "Rosario/ROSARIO, Argentina(ROS)",
    "Rostock-Laage/ROSTOCK-LAAGE, Germany(RLG)",
    "Rostov/ROSTOV, Russian Federation(ROV)",
    "Roswell/ROSWELL, United States(ROW)",
    "Rotorua/ROTORUA, New Zealand(ROT)",
    "Rotterdam/ROTTERDAM, Netherlands(RTM)",
    "Rovaniemi/ROVANIEMI, Finland(RVN)",
    "Saarbrucken Ensheim Airport/SAARBRUCKEN, Germany(SCN)",
    "Sabiha Gokcen/Istanbu/ISTANBUL, Turkey(SAW)",
    "Sacramento Metropolitan/SACRAMENTO/EXECUTIVE, United States(SMF)",
    "Saginaw/BAY CITY, United States(MBS)",
    "Saipan/SAIPAN, Northern Mariana Islands(SPN)",
    "Sal/SAL, Cape Verde(SID)",
    "Salalah/SALALAH, Oman(SLL)",
    "Salisbury/SALISBURY, United States(SBY)",
    "Salt Lake/SALT LAKE, United States(SLC)",
    "Salta/SALTA, Argentina(SLA)",
    "Saltillo/SALTILLO, Mexico(SLW)",
    "Salvador/SALVADOR, Brazil(SSA)",
    "Salzburg/SALZBURG, Austria(SZG)",
    "Samara/SAMARA, Russian Federation(KUF)",
    "Samos/SAMOS, Greece(SMI)",
    "San Angelo/SAN ANGELO, United States(SJT)",
    "San Antanio/SAN ANTONIO, United States(SAT)",
    "San Carlos De Bariloch/SAN CARLOS, Argentina(BRC)",
    "San Diego/SAN DIEGO, United States(SAN)",
    "San Francisco/SAN FRANCISCO, United States(SFO)",
    "San Jose/SAN JOSE, United States(SJC)",
    "San Jose Cabo/SAN JOSE CABO, Mexico(SJD)",
    "San Jose Santamaria/SAN JOSE, Costa Rica(SJO)",
    "San Juan/SAN JUAN, Puerto Rico(SJU)",
    "San Luis Potosi/SAN LUIS POTO, Mexico(SLP)",
    "San Pedro Sula/SAN PEDRO SUL, Honduras(SAP)",
    "San Salvador/SAN SALVADOR, El Salvador(SAL)",
    "San Sebastian/SAN SEBASTIAN, Spain And Canary Islands(EAS)",
    "Sanaa/SANAA, Yemen, Republic Of(SAH)",
    "Sandakan/SANDAKAN, Malaysia(SDK)",
    "Sanday/SANDAY, United Kingdom(NDY)",
    "Sankt-Peterburg/SANKT-PETERBURG, Russian Federation(LED)",
    "Santa Ana John Wayne Intl/SANT ANA, United States(SNA)",
    "Santa Barbara/SANTA BARBARA, United States(SBA)",
    "Santa Cruz/SANTA CRUZ, Bolivia(VVI)",
    "Santa Cruz De La Palma/SANTA CRUZ, Spain And Canary Islands(SPC)",
    "Santa Cruz El Tropmpillo/SANTA CRUZ, Bolivia(SRZ)",
    "Santa Fe/SNATA FE, United States(SAF)",
    "Santa Maria/SANTA MARIA, United States(SMX)",
    "Santa Marta/SANTA MARTA, Colombia(SMR)",
    "Santa Rosa/SANTA ROSA, United States(STS)",
    "Santa Rosa Airport/SANTA ROSA, Argentina(RSA)",
    "Santander/SANTANDER, Spain And Canary Islands(SDR)",
    "Santarem/SANTAREM, Brazil(STM)",
    "Santiago De Compostela/SANTIAGO COMP, Spain And Canary Islands(SCQ)",
    "Santiago Los Cerrillos/SANTIAGO, Chile(ULC)",
    "Santiago Municipal/SANTIAGO, Dominican Republic(STI)",
    "Santiago Pudahuel/SANTIAGO, Chile(SCL)",
    "Santo Domingo/SANTO DOMINGO, Dominican Republic(SDQ)",
    "Santo Domingo Herrera Apt/SANTO DOMINGO HERRERA AIRPORT, Dominican Republic(HEX)",
    "Sanya/SANYA, China(SYX)",
    "Sao Jose R Preto/SAO JOSE R PRETO, Brazil(SJP)",
    "Sao Luiz/SAO LUIZ, Brazil(SLZ)",
    "Sao Paulo Airport/SAO PAULO, Brazil(SAO)",
    "Sao Paulo Viraopos Airport/SAO PAULO, Brazil(VCP)",
    "Sao Paulo/Guarulhos Intl/SAO PAULO, Brazil(GRU)",
    "Sapporo/SAPPORO, Japan(SPK)",
    "Sapporo/Chitose/SAPPORO, Japan(CTS)",
    "Sarajevo/SARAJEVO, Bosnia Hercegovina(SJJ)",
    "Sau Paulo Conghonhas/SAO PAULO, Brazil(CGH)",
    "Savannah International Apt/SAVANNAH, United States(SAV)",
    "Savonlinna/SAVONLINNA, Finland(SVL)",
    "Seattle/SEATTLE, United States(SEA)",
    "Semipalatinsk/SEMIPALATINSK, Kazakhstan(PLX)",
    "Sendai/SENDAI, Japan(SDJ)",
    "Seoul/SEOUL, Korea, Republic Of(SEL)",
    "Seoul Gimpo/SEOUL, Korea, Republic Of(GMP)",
    "Seville/SEVILLE, Spain And Canary Islands(SVQ)",
    "Shanghai/Hongqiao Int&acute;l/SHANGHAI, China(SHA)",
    "Shanghai/Pu Dong/SHANGHAI, China(PVG)",
    "Shannon/SHANNON, Ireland(SNN)",
    "Shantou/SHANTOU, China(SWA)",
    "Sharjah/SHARJAH, United Arab Emirates(SHJ)",
    "Sharm El Sheikh/SHARM E SHEIK, Egypt(SSH)",
    "Sheffield/SHEFFIELD, United Kingdom(SZD)",
    "Shelby/SHELBY, United States(SBX)",
    "Shemya/SHEMYA, United States(SYA)",
    "Shenyang/SHENYANG, China(SHE)",
    "Shenzhen/SHENZHEN, China(SZX)",
    "Shetland Islands Lerwick/SHETLAND ISLANDS SUMBURGH, United Kingdom(LWK)",
    "Shetland Islands Scatsta/SHETLAND ISLANDS SUMBURGH, United Kingdom(SCS)",
    "Shetland Islands Sumburgh/SHETLAND ISLANDS SUMBURGH, United Kingdom(LSI)",
    "Shijiazhuang/SHIJIAZHUANG, China(SJW)",
    "Shiraz/SHIRAZ, Iran (Islamic Republic Of)(SYZ)",
    "Shizuoka/SHIZUOKA, Japan(FSZ)",
    "Sialkot/SIALKOT, Russian Federation(SKT)",
    "Sibu/SIBU, Malaysia(SBW)",
    "Siem Reap/SIEM REAP, Cambodia(REP)",
    "Simao/SIMAO, China(SYM)",
    "Simferopol/SIMFEROPOL, Ukraine(SIP)",
    "Sindal/SINDAL, Denmark(CNL)",
    "Singapore/Changi/SINGAPORE, Singapore(SIN)",
    "Sioux City/SIOUX CITY, United States(SUX)",
    "Sioux Falls Foss Field/SIOUX FALLS, United States(FSD)",
    "Sitka/SITKA, United States(SIT)",
    "Skiathos/SKIATHOS, Greece(JSI)",
    "Skive/SKIVE, Denmark(SQW)",
    "Skopje/SKOPJE, Macedonia(SKP)",
    "Skukuza/SKUKUZA, South Africa(SZK)",
    "Sligo/SLIGO, Ireland(SXL)",
    "Sochi/Adler/SOCHI/ADLER, Russian Federation(AER)",
    "Sofia/SOFIA, Bulgaria(SOF)",
    "Someseni International Airport/CLUJ, Romania(CLJ)",
    "Song Pan/SONG PAN, China(JZH)",
    "South Bend/SOUTH BEND, United States(SBN)",
    "Southampton/SOUTHAMPTON, United Kingdom(SOU)",
    "Southend Airport/SOUTHEND, United Kingdom(SEN)",
    "Split/SPLIT, Croatia(SPU)",
    "Spokane/SPOKANE, United States(GEG)",
    "Springfield Capitol/SPRINGFIED IL, United States(SPI)",
    "Springfield Regional/SPRINGFIELD MO, United States(SGF)",
    "Srinagar/SRINAGAR, India(SXR)",
    "St Croix Island/ST CORIX, Virgin Islands, (U.S.)(STX)",
    "St Kitts/ST KITTS, Saint Kitts And Nevis(SKB)",
    "St Lucia Castries Vigie/ST LUCIA, Saint Lucia(SLU)",
    "St Lucia Hewanorra/ST LUCIA, Saint Lucia(UVF)",
    "St Maarten/ST MAARTEN, Netherlands Antilles(SXM)",
    "St Thomas Island/ST THOMAS, Virgin Islands, (U.S.)(STT)",
    "St. Louis/Lambert Intl/ST LOUIS, United States(STL)",
    "St.Pierre Des Corps Rail St/SAINT-PIERRE DES CORPS RAIL, France(XSH)",
    "State College/STATE COLLEGE, United States(SCE)",
    "Stavanger/STAVANGER, Norway(SVG)",
    "Stavropol/STAVROPOL, Russian Federation(STW)",
    "Stockholm Bromma/STOCKHOLM, Sweden(BMA)",
    "Stockholm/Arlanda/STOCKHOLM, Sweden(ARN)",
    "Strasbourg/STRASBOURG, France(SXB)",
    "Stronoway/STORNOWAY, United Kingdom(SYY)",
    "Stronsay/STRONSAY, United Kingdom(SOY)",
    "Stuttgart Echterdingen Apt/STUTTGART, Germany(STR)",
    "Sukhothai/SOKHOTHAI, Thailand(THS)",
    "Sulaymaniyah/SULAYMANIYAH, Iraq(ISU)",
    "Sultan Ismail Petra/KOTA BHARU, Malaysia(KBR)",
    "Sun Valley/SUN VALLEY, United States(SUN)",
    "Sunshine Coast/MAROOCHYDO, Australia(MCY)",
    "Surabaya/Juanda/SURABAYA, Indonesia(SUB)",
    "Surgut/SURGUT, Russian Federation(SGC)",
    "Suva Fiji Island/SUVA, Fiji(SUV)",
    "Sverdlovsk/SVERDLOVSK, Russian Federation(SVX)",
    "Sydney Kingsford Australia/SYDNEY, Australia(SYD)",
    "Syracuse/SYRACUSE, United States(SYR)",
    "Tacna/TACNA, Peru(TCQ)",
    "Taegu/TAEGU, Korea, Republic Of(TAE)",
    "Taichung/TAICHUNG, Taiwan(RMQ)",
    "Taif Airport/TAIF, Saudi Arabia(TIF)",
    "Taipei/Shungshan/TAIPEI, Taiwan(TSA)",
    "Taipei/Taoyuan/TAIPEI, Taiwan(TPE)",
    "Taiyuan Wusu/TAIYUAN, China(TYN)",
    "Takamatsu/TAKAMATSU, Japan(TAK)",
    "Tallahassee/TALLAHASS, United States(TLH)",
    "Tallinn/TALLINN, Estonia(TLL)",
    "Tampa/TAMPA, United States(TPA)",
    "Tampere/TAMPERE, Finland(TMP)",
    "Tampico/TAMPICO, Mexico(TAM)",
    "Tamworth/TAMWORTH, Australia(TMW)",
    "Tarapoto/TARAPOTO, Peru(TPP)",
    "Taree/TAREE, Australia(TRO)",
    "Tashkent Yuzhny/UZBEKISTAN, Uzbekistan(TAS)",
    "Tawau/TAWAU, Malaysia(TWU)",
    "Tbilisi/TBILISI, Georgia(TBS)",
    "Tegel/BERLIN, Germany(BER)",
    "Tehran/TEHRAN, Iran (Islamic Republic Of)(THR)",
    "Tel-Aviv/Ben Gurion/TEL AVIV YAFO, Israel(TLV)",
    "Temuco/TEMUCO, Chile(ZCO)",
    "Tenerife Canary Island/TENERIFE, Spain And Canary Islands(TFS)",
    "Tenerife Norte Apt/TENERIFE, Spain And Canary Islands(TFN)",
    "Tengchong/TENGCHONG, China(TCZ)",
    "Tequchigalpa/TEGUCIGALPA, Honduras(TGU)",
    "Teresina Airport/TERESINA, Brazil(THE)",
    "Texarkana/TEXARKANA, United States(TXK)",
    "Thesaloniki/THESSALONIKI, Greece(SKG)",
    "Thira/THIRA, Greece(JTR)",
    "Thisted/THISTED, Denmark(TED)",
    "Thursday Island/THURSDAY ISLAND, Australia(TIS)",
    "Tianjin/TIANJIN, China(TSN)",
    "Tijuana/TIJUANA, Mexico(TIJ)",
    "Timisoara/TIMISOARA, Romania(TSR)",
    "Tirana/TIRANA, Albania(TIA)",
    "Tiree/TIREE, United Kingdom(TRE)",
    "Tirgu Mures/TIRGU MURES, Romania(TGM)",
    "Tiruchirapally/TIRUCHIRAPALL, India(TRZ)",
    "Tirupati/TIRUPATI, India(TIR)",
    "Tnagier/TANGIER, Morocco(TNG)",
    "Tobago/TOBAGO, Trinidad And Tobago(TAB)",
    "Tokunoshima/TOKUNOSHIMA, Japan(TKN)",
    "Tokushima/TOKUSHIMA, Japan(TKS)",
    "Tokyo/Narita/TOKYO, Japan(NRT)",
    "Toledo/TOLEDO, United States(TOL)",
    "Tom Price/TOM PRICE, Australia(TPR)",
    "Tomsk/TOMSK, Russian Federation(TOF)",
    "Tonghua Sanyuanpu Airport/TONGHUA SANYUANPU, China(TNH)",
    "Tongliao/TONGLIAO, China(TGO)",
    "Tongren/Daxing/TONGREN, China(TEN)",
    "Toronto/TORONTO, Canada(YYZ)",
    "Torreon/TORREON, Mexico(TRC)",
    "Tottori/TOTTORI, Japan(TTJ)",
    "Toulon/TOULON, France(TLN)",
    "Toulouse/TOULOUSE, France(TLS)",
    "Tours/TOURS, France(TUF)",
    "Townsville/TOWNSVILLE, Australia(TSV)",
    "Toyama/TOYAMA, Japan(TOY)",
    "Trabzon/TRABZON, Turkey(TZX)",
    "Trat/TRAT, Thailand(TDX)",
    "Traverse City/TRAVERSE, United States(TVC)",
    "Tres De Mayo Apt/PUERTO ASIS, Colombia(PUU)",
    "Tri Cities Regional/BRISTOL, United States(TRI)",
    "Trieste/TRIESTE, Italy(TRS)",
    "Trinidad/PORT OF SPAIN, Trinidad And Tobago(POS)",
    "Tripoli/TRIPOLI, Libyan Arab Jamahiriya(TIP)",
    "Trivandrum/TRIVANDRUM, India(TRV)",
    "Tromso/TROMSO, Norway(TOS)",
    "Trujillo/TRUJILLO, Peru(TRU)",
    "Tucson/TUCSON, United States(TUS)",
    "Tucuman/TUCUMAN, Argentina(TUC)",
    "Tulcea Airport/TULCEA, Romania(TCE)",
    "Tulsa/TULSA, United States(TUL)",
    "Tumbes/TUMBES, Peru(TBP)",
    "Tunis/TUNIS, Tunisia(TUN)",
    "Tunxi/TUNXI, China(TXN)",
    "Turin/TURIN, Italy(TRN)",
    "Turku/TURKU, Finland(TKU)",
    "Tuxtla Gutier/TUXTLA GUTIER, Mexico(TGZ)",
    "Tyler/TYLER, United States(TYR)",
    "Tyumen/TYUMEN, Russian Federation(TJM)",
    "Ube Yamaguchi/YAMAGUCHI, Japan(UBJ)",
    "Uberlandia/UBERLANDIA, Brazil(UDI)",
    "Udaipur/UDAIPUR, India(UDR)",
    "Udon Thani/UDON THANI, Thailand(UTH)",
    "Ufa/UFA, Russian Federation(UFA)",
    "Ulan Bator Buyant Ukhaa/ULAN BATOR, Mongolia(ULN)",
    "Ulan-Ude/ULAN-UDE, Russian Federation(UUD)",
    "Ulanhot/ULANHOT, China(HLH)",
    "Unst/UNST SHETLAND ISLAND, United Kingdom(UNT)",
    "Urgench/URGENCH, Uzbekistan(UGC)",
    "Urumqi/URUMQI, China(URC)",
    "Ushuaia/USHUAIA, Argentina(USH)",
    "Vaasa/VAASA, Finland(VAA)",
    "Vadodara/VADODARA, India(BDQ)",
    "Valdivia/VALDIVIA, Chile(ZAL)",
    "Valencia/VALENCIA, Spain And Canary Islands(VLC)",
    "Vali Eagle/VAIL EAGLE, United States(EGE)",
    "Valladolid/VALLADOLID, Spain And Canary Islands(VLL)",
    "Vancouver/VANCOUVER, Canada(YVR)",
    "Vanguardia Airport/VILLAVICENCIO, Colombia(VVC)",
    "Varadero/VARADERO, Cuba(VRA)",
    "Varanasi/VARANASI, India(VNS)",
    "Varkaus/VARKAUS, Finland(VRK)",
    "Varna/VARNA, Bulgaria(VAR)",
    "Venice/VENICE, Italy(VCE)",
    "Veracruz/VERACRUZ, Mexico(VER)",
    "Verona/VERONA, Italy(VRN)",
    "Victoria Intl Airport/VICTORIA, Canada(YYJ)",
    "Victorua Falls/VICTORIA FALLS, Zimbabwe(VFA)",
    "Vienna/Schwechat/VIENNA, Austria(VIE)",
    "Vientiane/VIENTIANE, Lao People's Democratic Republic(VTE)",
    "Vigo/VIGO, Spain And Canary Islands(VGO)",
    "Vilafria Airport Burgos/BURGOS, Spain And Canary Islands(RGS)",
    "Villahermosa/VILLAHERMOSA, Mexico(VSA)",
    "Vilnius/VILNIUS, Lithuania(VNO)",
    "Vina Del Mar/VINA DEL MAR, Chile(KNA)",
    "Vishakhapatnam/VISHAKHAPATNA, India(VTZ)",
    "Vitoria/VITORIA, Spain And Canary Islands(VIT)",
    "Vitoria/VITORIA, Brazil(VIX)",
    "Vladikavkaz/VLADIKAVKAZ, Russian Federation(OGZ)",
    "Vladivostok/VLADIVOSTOK, Russian Federation(VVO)",
    "Volgograd/VOLGOGRAD, Russian Federation(VOG)",
    "Volos/VOLOS, Greece(VOL)",
    "Waco/WACO, United States(ACT)",
    "Waco James Connall Airport/WACO JAMES CONNALL, United States(CNW)",
    "Wagga Wagga/WAGGA WAGGA, Australia(WGA)",
    "Walla Walla/WALLA WALL, United States(ALW)",
    "Wanxian/WANXIAN, China(WXN)",
    "Warsaw/WARSAW, Poland(WAW)",
    "Washington DC / Baltimore/WASHINGTON, United States(DCA)",
    "Washington Dulles Dc/WASHINGTON, United States(IAD)",
    "Waterford/WATERFORD, Ireland(WAT)",
    "Waterloo/WATERLOO, United States(ALO)",
    "Watertown/WATERTOWN NY, United States(ART)",
    "Weeze/WEEZE, Germany(NRN)",
    "Weifang/WEIFANG, China(WEF)",
    "Weihai/WEIHAI, China(WEH)",
    "Weipa/WEIPA, Australia(WEI)",
    "Wellington/WELLINGTON, New Zealand(WLG)",
    "Wenatchee/WENATCHEE, United States(EAT)",
    "Wenshan/WENSHAN, China(WNH)",
    "Wenzhou/WENZHOU, China(WNZ)",
    "West Palm Beach/WEST PALM BEACH, United States(PBI)",
    "Westchester County/WESTCHESTER, United States(HPN)",
    "Westerland/WESTERLAND, Germany(GWT)",
    "Westray/WESTRAY, United Kingdom(WRY)",
    "Wichita Falls/WICHITA FALLS, United States(SPS)",
    "Wichita/Mid-Continent/WICHITA, United States(ICT)",
    "Wick/WICK, United Kingdom(WIC)",
    "Wilkes-Barre Scranton Apt/SCRANTON, United States(AVP)",
    "Williamsport/WILLIAMSPORT, United States(IPT)",
    "Williamtown Newcastle/NEWCASTLE, Australia(NTL)",
    "Wilmington/WILMINGTON, United States(ILM)",
    "Windhoek International/WINDHOEK, Namibia(WDH)",
    "Winnipeg Intl Airport/WINNIPEG, Canada(YWG)",
    "Winston - Salem/GREENSBORO, United States(INT)",
    "Wollongong/WOLLONGONG, Australia(WOL)",
    "Worcester/WORCESTER, United States(ORH)",
    "Wrangell/WRANGELL, United States(WRG)",
    "Wu Hai/WU HAI, China(WUA)",
    "Wuhan/WUHAN, China(WUH)",
    "Wulingshan/QIANJIANG, China(JIQ)",
    "Wuxi/WUXI, China(WUX)",
    "Wuyishan/WUYISHAN, China(WUS)",
    "Xi'An Xianyang/XI'AN, China(XIY)",
    "Xiamen/XIAMEN, China(XMN)",
    "Xiangfan/XIANGFAN, China(XFN)",
    "Xilinhot/XILINHOT, China(XIL)",
    "Xingyi/XINGYI, China(ACX)",
    "Xining/XINING, China(XNN)",
    "Xuzhou/XUZHOU, China(XUZ)",
    "Yakima Air Terminal/YAKIMA, United States(YKM)",
    "Yakutat/YAKUTAT, United States(YAK)",
    "Yakutsk/KAYES, Russian Federation(YKS)",
    "Yamagata/YAMAGATA, Japan(GAJ)",
    "Yancheng/YANCHENG, China(YNZ)",
    "Yangzhou Taizhou Airport/YANGZHOU, China(YTY)",
    "Yanji/YANJI, China(YNJ)",
    "Yanjiagang Harbin/HARBIN, China(HRB)",
    "Yantai/YANTAI, China(YNT)",
    "Yerevan/EREVAN, Armenia(EVN)",
    "Yibin/YIBIN, China(YBP)",
    "Yichang/YICHANG, China(YIH)",
    "Yichun Lindu Airport/YICHUN HEILONGJIANG, China(LDS)",
    "Yinchuan/YINCHUAN, China(INC)",
    "Yining/YINING, China(YIN)",
    "Yiwu/YIWU, China(YIW)",
    "Yonaguni Jima/YONAGUNI JIMA, Japan(OGN)",
    "Yoronjima/YORONJIMA, Japan(RNJ)",
    "Yulin/YULIN, China(UYN)",
    "Yuma International Airport/YUMA, United States(YUM)",
    "Yushu Batang/YUSHU, China(YUS)",
    "Yuyuan/FUYUAN, China(FYJ)",
    "Yuzhno-Sakhalinsk/YUZHNO/SAKHALINSK, Russian Federation(UUS)",
    "Zacatecas/ZACATECAS, Mexico(ZCL)",
    "Zagreb/ZAGREB, Croatia(ZAG)",
    "Zakinthos/ZAKINTHOS ISLAND, Greece(ZTH)",
    "Zanzibar/ZANZIBAR, Tanzania, United Republic(ZNZ)",
    "Zaragoza/ZARAGOZA, Spain And Canary Islands(ZAZ)",
    "Zhangjiakou/ZHANGJIAKOU, China(ZQZ)",
    "Zhangjiang/ZHANJIANG, China(ZHA)",
    "Zhaotong/ZHAOTONG, China(ZAT)",
    "Zhengzhou/ZHENGZHOU, China(CGO)",
    "Zhoushan/ZHONGSHAN, China(HSN)",
    "Zhuhai Sanzao/ZHUHAI, China(ZUH)",
    "Zunyi Xinzhou Airport/ZUNYI, China(ZYI)",
    "Zurich/ZURICH, Switzerland(ZRH)",
    "Zweibrucken/ZWEIBRUCKEN, Germany(ZQW)"
]