var ticketTypeList = [
    {label:"Companion Ticket",	value:"companion"},
    {label:"One-way Ticket",	value:"one_way"},
    {label:"One-way Priority Awards Tier 1",value:"one_way_pt1"},
    {label:"One-way Priority Awards Tier 2",value:"one_way_pt2"},
    {label:"One-way Upgrade",value:"one_way_upgrade"},
    {label:"Round-trip Ticket",value:"round_trip"},
    {label:"Round-trip Priority Awards Tier 1",value:"round_trip_pt1"},
    {label:"Round-trip Priority Awards Tier 2",value:"round_trip_pt2"},
    {label:"Round-trip Upgrade",value:"round_trip_upgrade"},
]

var ticketClassList = [
    { ticketType_Id:"companion",label:"First", value:"FCC"},
    { ticketType_Id:"companion",label:"Business", value:"BCB"},
    { ticketType_Id:"one_way", label:"First", value:"OWFC"},
    { ticketType_Id:"one_way", label:"Business", value:"OWBC"},
    { ticketType_Id:"one_way", label:"Premium Economy", value:"OWPEC"},
    { ticketType_Id:"one_way", label:"Economy", value:"OWEC"},
    { ticketType_Id:"one_way_pt1", label:"Premium Economy", value:"OWPPT1"},
    { ticketType_Id:"one_way_pt1", label:"Economy", value:"OWEPT1"},
    { ticketType_Id:"one_way_pt2", label:"Premium Economy", value:"OWPPT2"},
    { ticketType_Id:"one_way_pt2", label:"Economy", value:"OWEPT2"},
    { ticketType_Id:"one_way_upgrade", label:"From Economy To Premium Econ", value:"OWUYP"},
    { ticketType_Id:"one_way_upgrade", label:"From Economy To Business", value:"OWUC"},
    { ticketType_Id:"one_way_upgrade", label:"From Premium Econ To Business", value:"OWUPC"},
    { ticketType_Id:"one_way_upgrade", label:"From Business To First", value:"OWUF"},
    { ticketType_Id:"round_trip", label:"First", value:"RTFC"},
    { ticketType_Id:"round_trip", label:"Business", value:"RTBC"},
    { ticketType_Id:"round_trip", label:"Premium Economy", value:"RTPEC"},
    { ticketType_Id:"round_trip", label:"Economy", value:"RTEC"},
    { ticketType_Id:"round_trip_pt1", label:"Premium Economy", value:"RTPPT1"},
    { ticketType_Id:"round_trip_pt1", label:"Economy", value:"RTEPT1"},
    { ticketType_Id:"round_trip_pt2", label:"Premium Economy", value:"RTPPT2"},
    { ticketType_Id:"round_trip_pt2", label:"Economy", value:"RTEPT2"},
    { ticketType_Id:"round_trip_upgrade", label:"From Economy To Premium Econ", value:"UGYP"},
    { ticketType_Id:"round_trip_upgrade", label:"From Economy To Business", value:"UGEC"},
    { ticketType_Id:"round_trip_upgrade", label:"From Premium Econ To Business", value:"UGPC"},
    { ticketType_Id:"round_trip_upgrade", label:"From Business To First", value:"UGCF"},
]

