var t_n_c_mapping = new Object();
t_n_c_mapping['en'] = new Object();
t_n_c_mapping['en']['interpretation'] = '1';
t_n_c_mapping['en']['general'] = '2';
t_n_c_mapping['en']['memberEnrol'] = '3';
t_n_c_mapping['en']['memberTerminate'] = '4';
t_n_c_mapping['en']['mileageCredit'] = '5';
t_n_c_mapping['en']['mileageCredit_air'] = '6';
t_n_c_mapping['en']['mileageCredit_nonair'] = '7';
t_n_c_mapping['en']['amDining'] = '8';
t_n_c_mapping['en']['memberStatement'] = '9';
t_n_c_mapping['en']['mileageRequest'] = '10';
t_n_c_mapping['en']['redeemGroup'] = '11';
t_n_c_mapping['en']['redeemAir_general'] = '12';
t_n_c_mapping['en']['redeemAir'] = '13';
t_n_c_mapping['en']['airAward_requirement'] = '14';
t_n_c_mapping['en']['airAward_priority'] = '15';
t_n_c_mapping['en']['airAward_companion'] = '16';
t_n_c_mapping['en']['airAward_upgrade'] = '17';
t_n_c_mapping['en']['airAward_baggage'] = '18';
t_n_c_mapping['en']['redeemNAR_general'] = '19';
t_n_c_mapping['en']['redeemNAR'] = '20';
t_n_c_mapping['en']['amGift'] = '21';
t_n_c_mapping['en']['amCharity'] = '22';
t_n_c_mapping['en']['amTopup'] = '23';
t_n_c_mapping['en']['amTransferRenew'] = '24';
t_n_c_mapping['en']['amFee'] = '25';
t_n_c_mapping['en']['amAuction'] = '26';
t_n_c_mapping['en']['ishop'] = '27';
t_n_c_mapping['en']['earnPromo'] = '28';
t_n_c_mapping['en']['privacyMisc'] = '29';
t_n_c_mapping['en']['liability'] = '30';
t_n_c_mapping['en']['law'] = '31';

t_n_c_mapping['zh'] = new Object();
t_n_c_mapping['zh']['interpretation'] = '1';
t_n_c_mapping['zh']['general'] = '2';
t_n_c_mapping['zh']['memberEnrol'] = '3';
t_n_c_mapping['zh']['memberTerminate'] = '4';
t_n_c_mapping['zh']['mileageCredit'] = '5';
t_n_c_mapping['zh']['mileageCredit_air'] = '6';
t_n_c_mapping['zh']['mileageCredit_nonair'] = '7';
t_n_c_mapping['zh']['amDining'] = '8';
t_n_c_mapping['zh']['memberStatement'] = '9';
t_n_c_mapping['zh']['mileageRequest'] = '10';
t_n_c_mapping['zh']['redeemGroup'] = '11';
t_n_c_mapping['zh']['redeemAir_general'] = '12';
t_n_c_mapping['zh']['redeemAir'] = '13';
t_n_c_mapping['zh']['airAward_requirement'] = '14';
t_n_c_mapping['zh']['airAward_priority'] = '15';
t_n_c_mapping['zh']['airAward_companion'] = '16';
t_n_c_mapping['zh']['airAward_upgrade'] = '17';
t_n_c_mapping['zh']['airAward_baggage'] = '18';
t_n_c_mapping['zh']['redeemNAR_general'] = '19';
t_n_c_mapping['zh']['redeemNAR'] = '20';
t_n_c_mapping['zh']['amGift'] = '21';
t_n_c_mapping['zh']['amCharity'] = '22';
t_n_c_mapping['zh']['amTopup'] = '23';
t_n_c_mapping['zh']['amTransferRenew'] = '24';
t_n_c_mapping['zh']['amFee'] = '25';
t_n_c_mapping['zh']['amAuction'] = '26';
t_n_c_mapping['zh']['ishop'] = '27';
t_n_c_mapping['zh']['earnPromo'] = '28';
t_n_c_mapping['zh']['privacyMisc'] = '29';
t_n_c_mapping['zh']['liability'] = '30';
t_n_c_mapping['zh']['law'] = '31';

t_n_c_mapping['sc'] = new Object();
t_n_c_mapping['sc']['interpretation'] = '1';
t_n_c_mapping['sc']['general'] = '2';
t_n_c_mapping['sc']['memberEnrol'] = '3';
t_n_c_mapping['sc']['memberTerminate'] = '4';
t_n_c_mapping['sc']['mileageCredit'] = '5';
t_n_c_mapping['sc']['mileageCredit_air'] = '6';
t_n_c_mapping['sc']['mileageCredit_nonair'] = '7';
t_n_c_mapping['sc']['amDining'] = '8';
t_n_c_mapping['sc']['memberStatement'] = '9';
t_n_c_mapping['sc']['mileageRequest'] = '10';
t_n_c_mapping['sc']['redeemGroup'] = '11';
t_n_c_mapping['sc']['redeemAir_general'] = '12';
t_n_c_mapping['sc']['redeemAir'] = '13';
t_n_c_mapping['sc']['airAward_requirement'] = '14';
t_n_c_mapping['sc']['airAward_priority'] = '15';
t_n_c_mapping['sc']['airAward_companion'] = '16';
t_n_c_mapping['sc']['airAward_upgrade'] = '17';
t_n_c_mapping['sc']['airAward_baggage'] = '18';
t_n_c_mapping['sc']['redeemNAR_general'] = '19';
t_n_c_mapping['sc']['redeemNAR'] = '20';
t_n_c_mapping['sc']['amGift'] = '21';
t_n_c_mapping['sc']['amCharity'] = '22';
t_n_c_mapping['sc']['amTopup'] = '23';
t_n_c_mapping['sc']['amTransferRenew'] = '24';
t_n_c_mapping['sc']['amFee'] = '25';
t_n_c_mapping['sc']['amAuction'] = '26';
t_n_c_mapping['sc']['ishop'] = '27';
t_n_c_mapping['sc']['earnPromo'] = '28';
t_n_c_mapping['sc']['privacyMisc'] = '29';
t_n_c_mapping['sc']['liability'] = '30';
t_n_c_mapping['sc']['law'] = '31';


t_n_c_mapping['ja'] = new Object();
t_n_c_mapping['ja']['interpretation'] = '1';
t_n_c_mapping['ja']['general'] = '2';
t_n_c_mapping['ja']['memberEnrol'] = '3';
t_n_c_mapping['ja']['memberTerminate'] = '4';
t_n_c_mapping['ja']['mileageCredit'] = '5';
t_n_c_mapping['ja']['mileageCredit_air'] = '6';
t_n_c_mapping['ja']['mileageCredit_nonair'] = '7';
t_n_c_mapping['ja']['amDining'] = '8';
t_n_c_mapping['ja']['memberStatement'] = '9';
t_n_c_mapping['ja']['mileageRequest'] = '10';
t_n_c_mapping['ja']['redeemGroup'] = '11';
t_n_c_mapping['ja']['redeemAir_general'] = '12';
t_n_c_mapping['ja']['redeemAir'] = '13';
t_n_c_mapping['ja']['airAward_requirement'] = '14';
t_n_c_mapping['ja']['airAward_priority'] = '15';
t_n_c_mapping['ja']['airAward_companion'] = '16';
t_n_c_mapping['ja']['airAward_upgrade'] = '17';
t_n_c_mapping['ja']['airAward_baggage'] = '18';
t_n_c_mapping['ja']['redeemNAR_general'] = '19';
t_n_c_mapping['ja']['redeemNAR'] = '20';
t_n_c_mapping['ja']['amGift'] = '21';
t_n_c_mapping['ja']['amCharity'] = '22';
t_n_c_mapping['ja']['amTopup'] = '23';
t_n_c_mapping['ja']['amTransferRenew'] = '24';
t_n_c_mapping['ja']['amFee'] = '25';
t_n_c_mapping['ja']['amAuction'] = '26';
t_n_c_mapping['ja']['ishop'] = '27';
t_n_c_mapping['ja']['earnPromo'] = '28';
t_n_c_mapping['ja']['privacyMisc'] = '29';
t_n_c_mapping['ja']['liability'] = '30';
t_n_c_mapping['ja']['law'] = '31';


t_n_c_mapping['ko'] = new Object();
t_n_c_mapping['ko']['interpretation'] = '1';
t_n_c_mapping['ko']['general'] = '2';
t_n_c_mapping['ko']['memberEnrol'] = '3';
t_n_c_mapping['ko']['memberTerminate'] = '4';
t_n_c_mapping['ko']['mileageCredit'] = '5';
t_n_c_mapping['ko']['mileageCredit_air'] = '6';
t_n_c_mapping['ko']['mileageCredit_nonair'] = '7';
t_n_c_mapping['ko']['amDining'] = '8';
t_n_c_mapping['ko']['memberStatement'] = '9';
t_n_c_mapping['ko']['mileageRequest'] = '10';
t_n_c_mapping['ko']['redeemGroup'] = '11';
t_n_c_mapping['ko']['redeemAir_general'] = '12';
t_n_c_mapping['ko']['redeemAir'] = '13';
t_n_c_mapping['ko']['airAward_requirement'] = '14';
t_n_c_mapping['ko']['airAward_priority'] = '15';
t_n_c_mapping['ko']['airAward_companion'] = '16';
t_n_c_mapping['ko']['airAward_upgrade'] = '17';
t_n_c_mapping['ko']['airAward_baggage'] = '18';
t_n_c_mapping['ko']['redeemNAR_general'] = '19';
t_n_c_mapping['ko']['redeemNAR'] = '20';
t_n_c_mapping['ko']['amGift'] = '21';
t_n_c_mapping['ko']['amCharity'] = '22';
t_n_c_mapping['ko']['amTopup'] = '23';
t_n_c_mapping['ko']['amTransferRenew'] = '24';
t_n_c_mapping['ko']['amFee'] = '25';
t_n_c_mapping['ko']['amAuction'] = '26';
t_n_c_mapping['ko']['ishop'] = '27';
t_n_c_mapping['ko']['earnPromo'] = '28';
t_n_c_mapping['ko']['privacyMisc'] = '29';
t_n_c_mapping['ko']['liability'] = '30';
t_n_c_mapping['ko']['law'] = '31';


// Function to allow promotion having partner logo name without partner association
function insertPartnerIntoPromotion(partnerName, partnerLogo) {
	cleanWhitespace(document.getElementById('insertPartnerIntoPromotion').parentNode);
    var holderDiv = document.getElementById('insertPartnerIntoPromotion').parentNode.childNodes[0];

	cleanWhitespace(holderDiv);
    holderDiv.removeChild(holderDiv.childNodes[holderDiv.childNodes.length - 1]);
        
    var imgTag = document.createElement("img");
    var h3Tag = document.createElement("h3");

    imgSrcAttr=document.createAttribute("src");
    imgSrcAttr.nodeValue=partnerLogo; //Path of the partner logo image
    imgTag.setAttributeNode(imgSrcAttr);

    h3Tag.innerHTML=partnerName;

    holderDiv.appendChild(imgTag);
    holderDiv.appendChild(h3Tag);
}